### ISSUE TITLE
网吧电脑无法注册

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#106]
### **问题描述：**
无法进行注册（试了3个注册码），估计是因为网吧电脑不能在系统目录写入数据。
![12 02](https://user-images.githubusercontent.com/48675877/56196109-ce913980-6068-11e9-9860-c1cc28f7b43d.png)

### **来源**
win7 64位 专业版

**Comment by pisceshsu** [comment]
错误原因，测试组用Mac上的注册码来注册Windows版本
