### ISSUE TITLE
设置菜单中切换语言，程序关闭后没有重启，需要手动启动。

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#107]
### **问题描述**
设置菜单——切换语言，点Yes，程序关闭后没有重启，需要手动启动。

### **来源**
测试

**Comment by vgawen** [comment]
2.6.1 已解决

**Comment by hpuzj** [comment]
跟测完成
菜单栏->设置->切换语言->提示重新启动程序->选择yes->程序重新启动
