### ISSUE TITLE
导出时会导致视频图像卡住问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#112]
### **问题描述**
导出时会导致视频图像卡住问题

**Comment by hpuzj** [comment]
### **问题描述**
目前测试到的问题和切换视频模式有关；比如：UHD 2160p 60fps，切换成HD1080p 24fps（25fps、30fps等)

**Comment by vgawen** [comment]
解决方法：切换视频模式时强制重启程序
