### ISSUE TITLE
工具栏中的「添加滤镜」按钮，点击无效

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#141]
### **问题描述**
工具栏中的「添加滤镜」按钮，点击无效

### **来源**
Mac 0.2.7测试
Windows 0.2.7测试

**Comment by hpuzj** [comment]
Mac 2.5.7正式版本测试
点击时间线上的「添加滤镜」功能，弹出的窗口只是闪一下

**Comment by Dragon-S** [comment]
从目前的研究以及咨询wyl来看是qt的bug，需要使用xcode9编译才可以。xcode9才能支持低版本的qt。
https://stackoverflow.com/questions/54348071/black-window-with-qt-quick-5-6-2-on-macosx-10-14

https://bugreports.qt.io/browse/QTBUG-71206

https://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/

**Comment by vgawen** [comment]
解决方法：使用xcode 9的mac os x 10.13 sdk重新编译，参考
https://bugreports.qt.io/browse/QTBUG-71206
https://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/
