### ISSUE TITLE
clip加上淡入淡出滤镜后，切分后效果不对。

### ISSUE THREAD

**Issue by wyl1987527** [hansewu/MovieMator#162]

**Comment by wyl1987527** [comment]
这个是滤镜的，但是与关键帧应该有些关系filter in out

**Comment by pisceshsu** [comment]
与 https://github.com/hansewu/MovieMator/issues/56 重复

**Comment by wyl1987527** [comment]
确认与 “添加淡入淡出滤镜，切分后前后两段clip效果不同 #56 ” 重复
