### ISSUE TITLE
Windows用安裝包安裝的程序，旧的贴图资源没有删除

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#164]
在windows上用新的安装包安装moviemator，如果新的moviemator中的贴图资源和旧的贴图资源不重名，安装时就不会覆盖旧的贴图资源，同时会存在新旧图片资源

**Comment by pisceshsu** [comment]
与#166重复，

**Comment by Dragon-S** [comment]
目前的解决方法是在安装新程序前，卸载掉旧的程序
