### ISSUE TITLE
2.5.7beta 贴图质量仍然不合格

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#166]
2.5.7beta 贴图质量仍然不合格

贴图质量要达到：1 MAGREX MP4-MP7 所带资源水准
                             2 达到超越一般设计的80%-90%的水平。没有竞争力的东西拿给用户没有意义。（一般水平http://www.51miz.com/png/    ）

建议：考虑精度问题，可以尝试将矢量文件转成SVG。

![图片](https://user-images.githubusercontent.com/17918660/57962338-2cef5780-7948-11e9-8b40-4054ca16c677.png)

![图片](https://user-images.githubusercontent.com/17918660/57962344-38db1980-7948-11e9-972b-0e39932db4c2.png)

**Comment by hansewu** [comment]
我删掉了老版本重装的，上面截图就是2.5.7BETA带的图片。

**Comment by hansewu** [comment]
PNG图片要求横向不大于 1920 竖向不大于1080
其他要求见下面


FRAME:（长宽有一个不能小于800）

窗棂_1.png
水墨复古_1.png
炫彩边框_1
炫彩边框_4
雪花_1
3D立体剪纸_3.svg


氛围：（长宽有一个不能小于800）

光效，烟，云彩将图片缩小成1920以下，小于1M 的都要




点缀：

PNG 长宽有一个不能小于不小于400

SVG  小于500KB的都要

装饰  再找20张
暂时不要用途过窄的，尽量用途比较广泛的。

如用于点缀的花纹，符号，箭头，爱心，表情等。

**Comment by gengxiaofeng** [comment]
[贴图资源.zip](https://github.com/hansewu/MovieMator/files/3210021/default.zip)

**Comment by hpuzj** [comment]
2.5.7 Mac正式版，新加的部分贴图，仍需要优化一下，例如adron_13
![屏幕快照 2019-05-24 下午4 27 26](https://user-images.githubusercontent.com/48675877/58313741-dd75c380-7e40-11e9-98f6-19d848a94da4.png)

**Comment by gengxiaofeng** [comment]
已处理：
效果图：
![51miz-E769921-F3BB9822](https://user-images.githubusercontent.com/37355589/58317168-d56d5200-7e47-11e9-8a1d-50ce70202bee.jpg)


资源图片：
![51miz-E769921-F3BB9822](https://user-images.githubusercontent.com/37355589/58317181-dbfbc980-7e47-11e9-95d2-ecbd6edb17da.png)

另一张svg不显示，已处理：
