### ISSUE TITLE
2.5.7beta 滤镜图片不符合界面质量要求

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#167]
滤镜图片不符合界面质量要求，没有分辨意义，不整洁。

界面图片界面质量要达到：

1 FILMORA, MOVAVI的界面图片水准
2 MAGREX MP4-MP7 界面图片水准

![滤镜列表](https://user-images.githubusercontent.com/17918660/57962116-60c97d80-7946-11e9-9599-c99696a26280.JPG)

![音频滤镜](https://user-images.githubusercontent.com/17918660/57962170-b43bcb80-7946-11e9-9b94-f72dd15f6fe0.jpg)

**Comment by gengxiaofeng** [comment]
1 完成常用滤镜25个，以及通用滤镜1个图标优化
2 完成艺术分类所有滤镜图片制作，黑&白分类所有滤镜图片制作

首屏滤镜效果图：
![xiaoguotu](https://user-images.githubusercontent.com/37355589/58294815-a54d9100-7dfe-11e9-99e3-b87199aab7a3.jpg)


常用滤镜及通用滤镜下载包：
[滤镜_icon.zip](https://github.com/hansewu/MovieMator/files/3214583/_icon.zip)


艺术分类滤镜下载包：
[艺术_icon.zip](https://github.com/hansewu/MovieMator/files/3214584/_icon.zip)


黑&白类滤镜下载包：
[黑&白_icon.zip](https://github.com/hansewu/MovieMator/files/3214585/_icon.zip)

注：暂时参考的中文的，所以里面图片命名都是以中文拼音为主
