### ISSUE TITLE
2.5.7beta 滤镜按钮贴图不符合界面质量要求

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#168]
滤镜按钮贴图图片不符合界面质量要求，粗糙，看不清。

界面图片界面质量要达到：

1 FILMORA, MOVAVI的界面图片水准
2 MAGREX MP4-MP7 界面图片水准

![图片](https://user-images.githubusercontent.com/17918660/57962279-9ae74f00-7947-11e9-878e-4cd582ef5c62.png)

**Comment by gengxiaofeng** [comment]
音频滤镜状态图：左边为常规状态，右边为鼠标经过状态
![音频效果](https://user-images.githubusercontent.com/37355589/58217342-f729e480-7d34-11e9-9751-8b0d2fc7f31f.png)

软件里效果图：
![音频效果图](https://user-images.githubusercontent.com/37355589/58217354-0315a680-7d35-11e9-9bf5-2e1cb74b3957.jpg)

**Comment by vvyan** [comment]
1.效果图

![音频按钮效果图](https://user-images.githubusercontent.com/37361188/58219877-1299ed00-7d3f-11e9-9a2b-31df91abc847.jpg)

2.切图
![背景](https://user-images.githubusercontent.com/37361188/58219886-1af22800-7d3f-11e9-9bf8-5c650e1e702b.png)
![添加按钮](https://user-images.githubusercontent.com/37361188/58219888-1b8abe80-7d3f-11e9-8cf8-f792c9e047e4.png)
![外框1](https://user-images.githubusercontent.com/37361188/58219889-1c235500-7d3f-11e9-90bd-00bc59e12bff.png)

**Comment by vvyan** [comment]
音频按钮效果图
![523yinpinfangda](https://user-images.githubusercontent.com/37361188/58221400-044ecf80-7d45-11e9-8fe0-2dff644ea26c.png)

![523yinpin](https://user-images.githubusercontent.com/37361188/58221391-fe58ee80-7d44-11e9-8d77-fa56e96e02fd.jpg)

切图
1.![beijing](https://user-images.githubusercontent.com/37361188/58221429-16307280-7d45-11e9-87b4-eef285b20147.png)
2.![jiahao_down](https://user-images.githubusercontent.com/37361188/58221430-16307280-7d45-11e9-8852-23cc629d7326.png)
3.![jiahao](https://user-images.githubusercontent.com/37361188/58221431-16307280-7d45-11e9-9172-881cb5f6d207.png)
