### ISSUE TITLE
2.5.7beta 右边滤镜按钮使能按钮贴图不符合界面质量要求

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#169]
2.5.7beta 右边滤镜按钮使能按钮贴图不符合界面质量要求 

右边滤镜按钮使能按钮贴图图片不符合界面质量要求，遮挡，破坏主要目标。

界面图片界面质量要达到：

1 FILMORA, MOVAVI的界面图片水准
2 MAGREX MP4-MP7 界面图片水准

![图片](https://user-images.githubusercontent.com/17918660/57962459-5c529400-7949-11e9-96d6-5be589534983.png)

**Comment by vvyan** [comment]
效果图：
从左至右：常态下不打钩、常态下打钩、鼠标点击不打钩、鼠标点击打钩

![屏幕快照 2019-05-23 15 26 51](https://user-images.githubusercontent.com/37361188/58233655-3f65f880-7d6f-11e9-9bcd-8f985264a73d.png)
 
![效果图](https://user-images.githubusercontent.com/37361188/58233278-34f72f00-7d6e-11e9-9d30-b7471df44346.jpg)

切图：
常态下不打钩
![changtai](https://user-images.githubusercontent.com/37361188/58233706-5b699a00-7d6f-11e9-8131-fc49b6678d14.png)

常态下打钩
![changtai_dagou](https://user-images.githubusercontent.com/37361188/58233721-66242f00-7d6f-11e9-9c53-1289dac77541.png)

鼠标点击不打钩
![shubiaojingguo](https://user-images.githubusercontent.com/37361188/58233733-6c1a1000-7d6f-11e9-82e6-da896f660248.png)

鼠标点击打钩
![shubiaojingguo_dagou](https://user-images.githubusercontent.com/37361188/58233797-9370dd00-7d6f-11e9-91cd-3fbfb3fc4f49.png)

三角
![sanjiao](https://user-images.githubusercontent.com/37361188/58233814-9e2b7200-7d6f-11e9-905b-47d870711141.png)

注：图片尺寸为宽80px 高45px
