### ISSUE TITLE
无效的时间码

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#17]
### 问题描述：
1）版本2.5.4（steam用户），打开视频后，点击选择视频，软件会未响应然后退出。偶尔不退出时，尝试“增加”或“插入”还是提示“无效的时间码”
2）吴总反馈2.5.6：优酷下载的MP4视频文件，可以播放，但是无法添加到轨道上

### 来源: 
Steam，Windows网站版

### 版本: 
Steam MovieMator 2.5.4
Windows MovieMator Pro 2.5.6 

截图：
![image_2019_04_03T02_31_12_333Z](https://user-images.githubusercontent.com/6078647/55448810-dd550680-55fb-11e9-8e02-56385b801282.png)

**Comment by pisceshsu** [comment]
修改建议：遇到无法获取时间码的文件时，提示用户转化一下格式或者软件内置转换

**Comment by hansewu** [comment]
https://discussions.apple.com/thread/2373364
的确有这样的视频

**Comment by Dragon-S** [comment]
目前未找到无效时间码的资源，暂时没有想到跟踪问题的方法，暂时解决方法是提示用户，提示信息如下（测试部门提供）
文件的时间码无法读取，可以转换成mp4格式后再导入；
推荐：Total Video Converter(附带超链接) http://www.effectmatrix.com/total-video-converter/
