### ISSUE TITLE
2.5.7Beta 导入丢失文件的工程，不替换文件，点击OK，程序崩溃

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#171]
创建一个工程文件，轨道上有clip，保存工程文件后，将clip对应的电脑上的文件删除，打开工程文件，不替换文件，直接点击ok,程序崩溃。 且不会启动发送错误报告程序。

**Comment by pisceshsu** [comment]
据推广部反映，有的工程会崩，有的工程不会蹦：

会崩溃的工程：
[会崩溃的工程.zip](https://github.com/hansewu/MovieMator/files/3283856/default.zip)

不会崩溃的工程：
[不会崩溃的工程.zip](https://github.com/hansewu/MovieMator/files/3283858/default.zip)

**Comment by hpuzj** [comment]
Mac 网站版   和steam版本
win7 steam版本
1.直接将视频拖动到轨道上，然后保存工程（任意格式的视频：MP4、flv、avi、m4v、3gp等等)
2.关闭程序后，修改视频的路径，再次打开工程文件，
3.不替换文件，直接点击ok,程序崩溃 100%
3.将视频添加到资源库再拖动到轨道上，保存工程，修改视频路径，重新打开工程文件，程序不会崩溃。

**Comment by Dragon-S** [comment]
底层assert崩溃
Assertion failed!
File: producer_avformat.c, Line 2853

**Comment by Dragon-S** [comment]
主要是mlt中的assert引起，为了保证无效的producer能显示在时间线上，就需要在一些接口中允许null值，那么就需要关闭一些assert，但是如果关闭assert，就是失去之前加入assert让错误提早暴露的意义。因此目前的处理方法是将mlt编译未release版本，解决assert问题。
mlt release编译，只通过配置--disabel-debug是无法关闭assert的，还需要使用-DNDEBUG参数才能关闭assert。
