### ISSUE TITLE
2.5.7Beta 程序启动时，标题栏被遮挡，不能最大/最小化，拖动后才可以

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#173]
启动程序后，默认大小时，程序最上方的标题栏超出屏幕范围，不能直接最大最小化程序，需要拖动后才可以

**Comment by hpuzj** [comment]
### **步骤：**
1.卸载win7电脑上moviemator相关的所有版本,重新安装2.5.7beta版本；
2.电脑最下方的任务栏，右击选择属性，勾选「自动隐藏任务栏」功能
3.尽量拉大程序界面，但不是「最大化」，重新运行程序，界面标题栏显示不全（如图）
4.上次安装2.5.7beta版本，运行时标题栏直接就不显示不全，并没有以上操作步骤
![标题栏](https://user-images.githubusercontent.com/48675877/58145288-17e63180-7c84-11e9-98fe-b5d89b57116a.jpg)
