### ISSUE TITLE
2.5.7Beta 崩溃报告发送窗口的文字描述需要优化

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#174]
![屏幕快照 2019-05-18 上午9 49 19](https://user-images.githubusercontent.com/6078647/57963118-5b723000-7952-11e9-8747-9741089e0128.png)

**Comment by hpuzj** [comment]
### **来源**
2.5.7正式版本，win7测试
### **描述**
 1）文字需要优化，界面文字排版不美观，且段落文字前无空格(可参考Mac系统崩溃提示界面)
 2）重启MovieMator,改为重启剪大师

**Comment by hpuzj** [comment]
Mac2.5.7正式版，崩溃报告界面也需要优化
另外，错误崩溃报告页面，输入错误描述时，输入中文的情况下，拼音与下面的文字重叠。（如图）
![Mac](https://user-images.githubusercontent.com/48675877/58308981-8a4a4380-7e35-11e9-99f7-469e355e46c9.png)

**Comment by hpuzj** [comment]
Mac 2.5.7回归测试1     崩溃报告界面未优化
![Mac](https://user-images.githubusercontent.com/48675877/58620169-07276280-82f9-11e9-8466-85ac57f45b7c.png)

**Comment by vgawen** [comment]
原因是Mac 2.5.7回归测试1 没有替换crashreporter。已解决。
