### ISSUE TITLE
添加符号信息后dll、exe文件变大

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#182]
生成符号文件需要添加符号信息，在pro中添加以下代码，这样生成的dll、exe文件会很大，导致程序整体扩大约112M。
win32-g++ {
    QMAKE_CFLAGS_RELEASE += -g
    QMAKE_CXXFLAGS_RELEASE += -g
    QMAKE_CFLAGS_RELEASE -= -O2
    QMAKE_CXXFLAGS_RELEASE -= -O2
    QMAKE_LFLAGS_RELEASE =
}

**Comment by hansewu** [comment]
发布版本一般不添加符号调试信息

**Comment by WanYuanCN** [comment]
忘记说明了，这个符号信息是为了准确定位崩溃代码用的，现在找到方法了，生成符号文件的时候添加这些符号信息，实际打包的时候只添加下面两句
QMAKE_CFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE -= -O2
这样生成的文件，所有的加起来只增加0.6M左右，但是能够使用带有符号信息生成的符号文件，而且也能准确定位到具体的代码行。
