### ISSUE TITLE
2.5.7beta 预览问题

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#185]
1.点击媒体库的视频进行预览——暂停，可以暂停——播放，从头开始播放，而不是暂停的地方开始播放
2.轨道上的视频无法预览，是黑屏，试了不同格式的都不行，音频可以听到
![捕获181](https://user-images.githubusercontent.com/37360104/57967631-e6274f00-7993-11e9-885e-8cd7c25aa52f.PNG)

系统：win10 专业版；64-bit

**Comment by vgawen** [comment]
2.轨道上的视频无法预览，是黑屏。 
原因是把轨道的可见关了，就是前面的那个眼睛图标的按钮。

**Comment by AliciaMoris** [comment]
嗯，没注意到，取消隐藏后可以看到画面了
