### ISSUE TITLE
界面规整和简化设计需求和设计初步方案

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#187]
界面规整和简化设计需求和设计方案
从设计细节上规整和简化当前界面，突出常用功能，包括常用菜单， 工具栏按钮等。

**Comment by hansewu** [comment]
注意暂时考虑是按钮，菜单，以及功能不明确的设计。
分析里面常用功能， 尽量设计让常用功能比较简单，明确。

版面上大的改动暂时不考虑。

**Comment by hansewu** [comment]
MovieMator界面简化和明确第一阶段目标文字草案


主菜单：

1 主菜单增加新建工程选项

2 主菜单设置-》视频模式， 不采用菜单， 采用对话框实现。



左上资源框：

3 左上资源框加入文字存放各种文字效果

4 左上资源框加入音效存放各种音效

5 左上资源框加入运动轨迹存放各种运动轨迹设置

6 左上资源调整顺序为： 1 导入文件 2 文字 3 贴图 4 音效 5 视频滤镜 6 音频滤镜 7 运动轨迹

7 左上资源框文件/文字/贴图/音效/运动轨迹，右上角都有按钮可以添加到时间线

8 左上资源框点击左上资源中各种文字效果，视频播放窗口要能预览播放

9 左上资源框点击视频滤镜， 要能播放为 1秒钟原图，4秒钟视频滤镜结果图

10 左上资源框点击音频滤镜， 自动播放两次音效，一种原声，一种处理后的声音

11 左上资源框文字效果和动画效果分离

12 左上资源框点击视频滤镜，滤镜分类要重新进行分类，初步分为：
常用（常用要和工具栏添加滤镜的常用保持一致），防抖动，调色，变换，裁剪，艺术，扭曲，特效，其他

13 左上资源框点击视频滤镜，滤镜分类顺序调整：常用-》防抖动-》调色-》变换-》裁剪-》艺术-》扭曲-》特效-》其他 等。


播放窗口：

14 播放窗口, 去掉快进，快退播放按钮

15 播放窗口， 原快进，快退按钮换成前一帧，后一帧按钮，更方便前一帧后一帧的预览

16 播放窗口  播放模式：合适的100%下拉框   改成三个按钮：合适， 1：1， 全屏

17 播放窗口  音频音量使用较少，将音频+SLIDER 改为音频按钮弹出SLIDER窗口


右上角属性框：

18 右上角属性框将开始时间点和结束时间点，因为不能修改，采用一般文本显示。

19 右上角属性框将开始时间点和结束时间点，调整到“速度”选项上面。

20 右上角属性框“速度”选项需要强调，将其和开始时间点和技术时间分隔开。另外增加ICON示明“速度”的含义。

21  应用按钮用图形化强调，修改速度后，需要闪烁，避免没有应用。

22 右上角滤镜关键帧窗口的版面需要再重度设计。需要功能：1 关键帧模板 2 开启和关闭部分参数关键帧 3 关键帧按钮的遍历，增删需要更直观


时间线窗口：

23 时间线工具栏，TOOLTIP 增加快捷键提示

24 时间线工具栏，删除专场设置，暂时用不上

25 时间线工具栏，缩放到合适按钮，和放大，缩小，放到右边

26 右键菜单，有快捷键的都要带快捷键信息。

27 时间线点击视频片段右键菜单，菜单增加和修改为：

切割
插入资源
分隔线
删除
删除并关闭空隙
分隔线
剪切
复制
粘贴
分隔线
缩放到合适
添加滤镜


28 时间线点击轨道空白处，右键菜单调整为
切割
追加资源
分隔线
粘贴
分隔线
增加视频轨道
增加音频轨道
删除轨道
分隔线
轨道关闭视频
轨道关闭音频    
29 轨道头上的文字V1和A2等信息， 采用图标分别对应视频轨道和音频轨道。

**Comment by vvyan** [comment]
![文字草案效果图20190603第二张](https://user-images.githubusercontent.com/37361188/58773706-b1043900-85f0-11e9-8609-8d902be9127b.png)
![文字草案效果图20190603](https://user-images.githubusercontent.com/37361188/58773707-b19ccf80-85f0-11e9-8b0e-cdfdde8259cf.png)
