### ISSUE TITLE
贴图根据类别自动添加size and position滤镜并设置位置参数

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#188]
1  贴图分为两大类： 一 A类是拉伸到整个画面，  一B类是保持纵横比 25% 画面大小。
A类用于框架及其整体氛围的衬托， 用SIZE AND POSITION 拉伸到整个画面
B类用于画面的点缀， 用SIZE AND POSITION保持纵横比 同时设置大小为 25% 画面。

**Comment by fuyunhuaxin** [comment]
在之前重设贴图的图片的地方，添加了判断是否为A类，是的话设置为全屏
