### ISSUE TITLE
Windows MovieMator2.5.6,被360拦截

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#19]
### 问题描述：
Windows MovieMator2.5.6 在安装过程中被360拦截

### 来源:
网站版本

### 版本:
Windows MovieMator Pro2.5.6

**Comment by pisceshsu** [comment]
### **问题描述**
360拦截问题依然存在，并不是在安装登录时，而是在使用浏览器打开菜单中的教程或者官网时 ，页面跳转到教程或官网网站时弹出360拦截。（猎豹浏览器，之前安装其他软件时，该浏览器为捆绑安装的浏览器）
![360](https://user-images.githubusercontent.com/6078647/56801136-55a39600-684f-11e9-9631-490c9535b27b.png)

### **来源**
win7  0.2.7版本测试

**Comment by hpuzj** [comment]
### **问题描述**
1.双击安装包，直接安装程序，创建桌面快捷方式
2.右击桌面快捷方式，然后选择「打开文件位置」，找到安装包目录，将整个安装包MovieMator Video Editor Pro 直接删除
3.重新安装过程中提示360拦截
![WechatIMG4](https://user-images.githubusercontent.com/48675877/57966994-d3108100-798b-11e9-8fb9-747858bc763b.jpeg)


测试版本：2.5.7 beta

**Comment by hpuzj** [comment]
1.老版本程序，通过右击桌面快捷方式，选择「打开文件位置」，找到安装目录后，直接删除安装目录，然后安装新版本程序时，会提示360拦截
2.正常情况下进行卸载，再安装新程序不会遇到360拦截
3.直接覆盖原来的程序进行安装，也不会遇到360拦截
win7 2.5.7正式版

**Comment by debelliszhu** [comment]
360的是不是每个版本都需要提交测试 才不会报错。之前都已经测试通过了的，我提交管家收录时，系统自动要求再测试一遍，

![屏幕快照 2019-06-10 上午8 23 38](https://user-images.githubusercontent.com/37359992/59166211-a1897080-8b59-11e9-8271-716b77edff5d.png)

**Comment by vgawen** [comment]
2.5.7 和2.5.3版本，在win10 上测试了360杀毒和360安全卫士，没有拦截

**Comment by vgawen** [comment]
win7 上测试也没有拦截问题。应该是跟360提交测试有关。
