### ISSUE TITLE
音视频不同步问题

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#192]
测试组测试结果：
DVD中的VOB视频音视频同步问题测试结果（2019.5.10）
第一段：VTS_01_2.VOB
1. 将.VOB格式的视频拷贝到电脑，导入到MovieMator播放，预览时音频和视频不同步，声音有几帧的延迟，（声音与口型对不上）
2.相同的视频使用其他播放器播放，没有音频和视频不同步问题
3.将视频导出后预览，仍然会有延迟，导出为MP4 、flv格式，(其中MP4格式有添加转场)

第二、三段：VTS_01_4.VOB、 VTS_01_3.VOB
1. 导入程序预览时，声音和视频正常
2. 添加转场，导出后预览，也正常
3. 添加转场、切分、添加滤镜、跨轨道拖动、导出，也没遇到什么问题。

注：
1.全部直接从DVD拷贝到电脑上
2.大小全部为1.07G
3.VTS_01_2.VOB时长为18：23分钟
   VTS_01_3.VOB时长为18：13分钟
   VTS_01_4.VOB时长为17：10分钟

音频存放地址：
afp://192.168.2.222/影片/音视频不同步.VOB

**Comment by AliciaMoris** [comment]
steam 2.5.7 win (QQ 124549634反馈) 音画不同步

导出MP4视频，用视频播放器看存在音画不同步，“也就差不到半秒吧”、“win上最明显”、“前半部分有不在重音上”、“后半部分调整了视频还好”。

视频“别外传呐.mp4”已发送给xjp
