### ISSUE TITLE
Text滤镜关键帧功能除位置不稳定

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#197]
Text滤镜关键帧功能除位置参数外，其他参数关键帧：
1 win10 上无法设置
2 MAC上不稳定

**Comment by hansewu** [comment]
如下可以解决，但不知道具体原因。

function updateFilter(currentProperty, value) 里面
if(m_bLastEnableKeyFrame != bEnableKeyFrame) //未知原因  否则关键帧的值设置不进去
        {    
            loadSavedKeyFrame()
        }

**Comment by hpuzj** [comment]
Mac 2.5.7回归测试1
 1）文字滤镜，添加关键帧后修改文字颜色，鼠标点击向上箭头增加字间距，文字有时会突然消失，即使将字间距还原成0，在该关键帧位置处仍然不见文字
  2）开启关键帧后，修改字体、轮廓、背景颜色仍然不稳定，切换关键帧位置后，无法修改字体颜色；修改轮廓或背景颜色时，字体颜色跟着闪动，但无法修改
  3）有没有关键帧修改字体的：普通、粗体、细体无效
  4）添加多个文字滤镜，播放器上有时间码闪动后又消失

**Comment by hansewu** [comment]
基本解决如下：
1添加文字滤镜，改变字体颜色，再开启关键帧，无法在关键帧处再修改颜色；
2 文字滤镜，添加关键帧后修改文字颜色，增加字间距（超过20)，文字有时会突然消失，即使将字间距还原成0，在该关键帧位置处仍然不见文字
3 开启关键帧后，修改字体、轮廓、背景颜色仍然不稳定，切换关键帧位置后，有时无法修改字体颜色；修改轮廓或背景颜色时，字体颜色跟着闪动，但无法修改

其他：
4 不是所有参数都有关键帧。字幕位置功能屏蔽掉了，可以使用下面的变换来控制位置，使得位置和动画分开。
