### ISSUE TITLE
steam 2.5.5 两个QQ用户反馈 加滤镜后预览闪退

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#215]
”一般在添加玩滤镜后快速点击播放键容易出现“
”添加滤镜就会这样 我就多点了一下滤镜 然后播放就凉了“
”好像就是快速进行滤镜操作会出现“

**Comment by pisceshsu** [comment]
给了2.5.7beta版本，但steam用户，不愿意安装网站版，想等着steam更新。 等待推广部沟通结果

**Comment by AliciaMoris** [comment]
分别于5月24日和31日邀请他们安装更新，暂未收到同样的反馈

**Comment by AliciaMoris** [comment]
用户kevin反馈新版本还未发生同样的问题
