### ISSUE TITLE
色彩分级滤镜，参数（阴影、高光、中间调）显示为四分之一圆

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#216]
色彩分级滤镜，颜色调节显示不全（如图）
<img width="405" alt="WechatIMG1" src="https://user-images.githubusercontent.com/48675877/58294699-20fb0e00-7dfe-11e9-90b4-e4800b96c83f.png">

2.5.6.5版本
系统：
Mac OS High Sierra 10.13.6
Mac Book Pro  13.3寸
分辨率：2560 x 1600 视网膜显示屏

**Comment by pisceshsu** [comment]
Mac 2.5.7回归测试1已解决
