### ISSUE TITLE
2.5.7 Mac 部分mp3资源库和时间线播放有杂音

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#220]
2.5.7 Mac版本部分mp3资源库和时间播放有杂音，2.5.7windows播放正常， Mac2.5.6.5播放也正常

Itro,Kontinuum - Alive.mp3， 25s - 41s之间播放时有杂音
[Itro,Kontinuum - Alive.mp3.zip](https://github.com/hansewu/MovieMator/files/3215363/Itro.Kontinuum.-.Alive.mp3.zip)

**Comment by vgawen** [comment]
sdl_audio播放声音有杂音。sdl2_audio播放没有杂音。删掉了libmltsdl。
