### ISSUE TITLE
void QmlFilter::combineAllKeyFramePara() 性能优化

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#221]
void QmlFilter::combineAllKeyFramePara() 性能优化

每个值和关键帧的设置都调用了
    MLT.refreshConsumer();
     emit changed();

是否有必要，会不会造成性能上的问题？

**Comment by wyl1987527** [comment]
每个参数、每个关键帧不需要特别设置
MLT.refreshConsumer();
emit changed();

在这两个循环体外设置即可。

需要设置上面两句代码，如果不设置会产生 改变关键帧处的参数值，看不到效果，即在关键帧处改变界面参数值，预览窗口效果不改变。
