### ISSUE TITLE
2.5.7Mac clip开启关键帧时和修改参数形成新的关键帧位置时，提示的内容显示为白色小窗口

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#228]
![WechatIMG5](https://user-images.githubusercontent.com/48675877/58311688-1c554a80-7e3c-11e9-9100-b9fe7268b4d5.jpeg)

**Comment by pisceshsu** [comment]
Windows 2.5.7没有该问题

**Comment by hansewu** [comment]
建议把这个提示信息暂时屏蔽掉

**Comment by vgawen** [comment]
解决方法：使用xcode 9的mac os x 10.13 sdk重新编译，参考
https://bugreports.qt.io/browse/QTBUG-71206
https://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/
