### ISSUE TITLE
2.5.7 贴图界面的Animation显示不全，且Animation、adornment 、ambience、 frame未翻译，

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#229]

**Comment by hpuzj** [comment]
![屏幕快照 2019-05-24 下午4 35 34](https://user-images.githubusercontent.com/48675877/58314457-1bbfb280-7e42-11e9-95b8-dfbd11992405.png)

**Comment by pisceshsu** [comment]
2.6.4已解决
