### ISSUE TITLE
确定代码审核工具

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#233]
确定代码审核工具，用于检查代码是否符合工具所规定的规范。

**Comment by hansewu** [comment]
高东彪，10:48windows也好安装。生成html要安装python，可能麻烦点。

这是检测的项目，就是不会检查命名，空格等代码风格之类的
https://sourceforge.net/p/cppcheck/wiki/ListOfChecks/cppcheck / Wiki / ListOfCheckshttps://sourceforge.net10:48那肯定要的不要怕检测出的问题多本身现在的代码质量就很差实际现在，编译的WARNING 就很多要解决这些都是代码缺陷造成的静态检查，就是编译功能的扩展而已高东彪，10:51嗯 编译器报的警告也要处理的。

检测编码风格的工具，就看到一个cpplint，是根据google的c++编码规范检测的。

https://github.com/danmar/cppcheck/blob/master/addons/naming.py cppcheck的这里看到一个插件，好像是可以检测命名规范的。就是需要自己写插件。


danmar/cppcheckhttps://github.com10:52这个很早就说要调研的不知道以前调研什么去了那时调研就从网上COPY 点内容？我记得很早就让XJP 调研了这个就是做事是否靠谱弄了半天都要重新去弄Xu，10:55张静整理的那些开源工具，都是已经试用过的10:55那要有结论啊能不能用，如何用都已经用过，为什么还是要重新去调研？高东彪，10:56cpplint我也查了一些资料，没有找到其他检测命名规范的工具。cpplint试了一下。 这是输出结果。
10:57这个先放一放让测试组继续去弄做事总没做到位就不弄了这个从四月份就让WYL, 测试组去弄讲了很多遍，说用这个来制订代码审查标准每次都没做到位，就跑过去了Xu，11:01嗯，好，我们继续去弄。 11:05这种事，弄到现在有多麻烦匆忙去决定使用个工具下面已经在等着去有工具去检测了这个一开始调研的时候，说了很多次，用来做测试为什么弄了就扔那，没个结论做事都是虚假的积累什么都知道点，什么都考不上去使用这种东西弄出来没有用的Xu，11:09嗯，开源的静态代码检测工具，调研结果是cppchecker好用点。 检测的范围也最广11:10要能检查代码风格这事先这样， 测试组继续调研GDB 那研究编译WARNING， 把WARNING 打开到最容易报错模式Xu，11:12嗯高东彪，11:12嗯 11:12看看如何产生更多的编译 WARNING用这个方法作为代码缺陷检查高东彪，11:12嗯 11:13等到测试组充分调研后再决定用哪个检测工具高东彪，11:14嗯Xu，11:14嗯11:15另外 XJP 你们上周这方面调研没有？确定代码审核工具 · Issue #233 · hansewu/MovieMatorhttps://github.comXu，11:16上周开会是说在我们以前调研的基础上挑选工具嗯，我看到了分配给我的任务11:16那把怎么做事的结果贴在后面GDB 也把做事结果贴在后面高东彪，11:16嗯 Xu，11:16嗯11:17ISSUE 跟踪非常重要这件事情处理的怎么样，就看这个ISSUE里面一件事没做彻底，往往是缺乏跟踪管理高东彪，11:18嗯Xu，11:18嗯11:18测试任务以后也作为开发任务加到每次里程碑测试代码也要用版本管理踏踏实实的每件事要做到位

**Comment by vgawen** [comment]
根据调研的资料，cppcheck是功能比较强大的，而且是开源的。
在Mac上试用了一下，感觉还可以。检测结果能够生成html，看着也比较方便。

这是使用方法文档
https://github.com/hansewu/Yifang-Document/blob/master/%E6%80%BB%E7%BB%8F%E5%8A%9E/6%E6%9C%88/gdb/cppcheck%20%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95_%E9%AB%98%E4%B8%9C%E5%BD%AA_20190604.pdf


问题：不检测代码风格。可以通过插件，自己写检测规则，参考
https://github.com/danmar/cppcheck/blob/master/addons/naming.py

另外试了一个代码风格检测的工具：cpplint，google c++代码规范工具。基本用法：
python cpplint.py /Users/gdb/work/MovieMator/src/MovieMator/src/main.cpp

**Comment by hansewu** [comment]
1 暂时使用工程编译工具的最高级WARNING 作为代码缺陷检查工具
2 测试组研究使用什么静态工具检查代码缺陷，代码风格

**Comment by pisceshsu** [comment]
[几个开源静态代码检测工具的使用对比_张静_20190411.pdf](https://github.com/hansewu/MovieMator/files/3250386/_._20190411.pdf)

**Comment by pisceshsu** [comment]
cppcheck,也有代码风格的检查，需要再与cppllint google的代码规范标准做一下对比，

从资料看，cpplint有函数体大小的检查，超过80行会报错，需要进一步测试

**Comment by vgawen** [comment]
qt默认开启了大部分警告，调研结果是不需要再增加新的警告选项。

1 gcc和clang 编译器警告选项
Clang 警告选项
http://clang.llvm.org/docs/UsersManual.html#controlling-errors-and-warnings

Gcc警告选项
https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Warning-Options.html#Warning-Options


Gcc相关选项较多。clang选项较少。clang的选项gcc基本都有。

常用的-Wall，会启用以下警告选项：

-Waddress   
-Warray-bounds=1 (only with -O2)  
-Wbool-compare  
-Wbool-operation  
-Wc++11-compat  -Wc++14-compat  
-Wcatch-value (C++ and Objective-C++ only)  
-Wchar-subscripts  
-Wcomment  
-Wduplicate-decl-specifier (C and Objective-C only) 
-Wenum-compare (in C/ObjC; this is on by default in C++) 
-Wformat   
-Wint-in-bool-context  
-Wimplicit (C and Objective-C only) 
-Wimplicit-int (C and Objective-C only) 
-Wimplicit-function-declaration (C and Objective-C only) 
-Winit-self (only for C++) 
-Wlogical-not-parentheses 
-Wmain (only for C/ObjC and unless -ffreestanding)  
-Wmaybe-uninitialized 
-Wmemset-elt-size 
-Wmemset-transposed-args 
-Wmisleading-indentation (only for C/C++) 
-Wmissing-attributes 
-Wmissing-braces (only for C/ObjC) 
-Wmultistatement-macros  
-Wnarrowing (only for C++)  
-Wnonnull  
-Wnonnull-compare  
-Wopenmp-simd 
-Wparentheses  
-Wpessimizing-move (only for C++)  
-Wpointer-sign  
-Wreorder   
-Wrestrict   
-Wreturn-type  
-Wsequence-point  
-Wsign-compare (only in C++)  
-Wsizeof-pointer-div 
-Wsizeof-pointer-memaccess 
-Wstrict-aliasing  
-Wstrict-overflow=1  
-Wswitch  
-Wtautological-compare  
-Wtrigraphs  
-Wuninitialized  
-Wunknown-pragmas  
-Wunused-function  
-Wunused-label     
-Wunused-value     
-Wunused-variable  
-Wvolatile-register-var




-Wextra（-W）-Wall之外的选项，会启用以下警告选项。

-Wclobbered  
-Wcast-function-type  
-Wdeprecated-copy (C++ only) 
-Wempty-body  
-Wignored-qualifiers 
-Wimplicit-fallthrough=3 
-Wmissing-field-initializers  
-Wmissing-parameter-type (C only)  
-Wold-style-declaration (C only)  
-Woverride-init  
-Wsign-compare (C only) 
-Wredundant-move (only for C++)  
-Wtype-limits  
-Wuninitialized  
-Wshift-negative-value (in C++03 and in C99 and newer)  
-Wunused-parameter (only with -Wunused or -Wall) 
-Wunused-but-set-parameter (only with -Wunused or -Wall)



其他：
-Wpedantic 
这个是-Wall和-Wextra之外的选项。允许发出ANSI/ISO C标准所列出的所有警告。检测是否兼容ANSI/ISO C标准。








-Wall -Wextra -Wpedantic -Werror

-Werror 所有警告都视为错误，必须处理。


2 Qt中设置编译选项
https://stackoverflow.com/questions/6614049/adding-extra-compiler-option-in-qt
https://stackoverflow.com/questions/7980499/where-in-qt-creator-do-i-pass-arguments-to-a-compiler、
https://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-cxxflags

Qt Creator 缺省就是-Wall和-Wextra。已开启了大部分警告。

QMAKE_CFLAGS += -Wall -Wextra -Wpedantic -Werror
QMAKE_CXXFLAGS += -Wall -Wextra -Wpedantic -Werror



-Werror不能加，一是现在警告太多，编译遇到错误会停止。就只能一个一个去解决了。另外就是有些警告是Qt库的头文件里面的，没办法处理的。

-Wpedantic 不加该选项会报457个警告，加了之后报2864个警告。gnu c的扩展用法会报警告，这种用法非常多，而且不好改。

**Comment by vgawen** [comment]
结论：
第一步先去掉编译器-Wall选项开启时报的警告。
对于改不了的Waring，要有专门注释，并使用#pragma message 进行编译时提示。

备注：
Qt缺省是加了-Wall和-W(-Wextra)选项。因此要屏蔽掉-Wextra。修改方法如下：
找到文件
Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf
把
QMAKE_CFLAGS_WARN_ON       += -Wall -W
修改成
QMAKE_CFLAGS_WARN_ON       += -Wall #-W

**Comment by pisceshsu** [comment]
### 重复代码检测工具Simian
使用方法：https://www.cnblogs.com/ttssrs/p/10313210.html ，
命令行测试moviemator中的文件, .cpp, .c文件都可以，但.qml不行。
以下是对mainwindow.cpp的部分测试结果，经过核对，确实是重复的代码：
Found 6 duplicate lines with fingerprint 3a631fd38ac075ace4f18e87e6f1e0ca in the following files:
 Between lines 3717 and 3722 in C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp
 Between lines 3460 and 3465 in C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp
Found 6 duplicate lines with fingerprint a6a83b18f078480f6d8aa556937a7829 in the following files:
 Between lines 2884 and 2889 in C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp
 Between lines 2855 and 2860 in C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp

**Comment by pisceshsu** [comment]
### cpplint测试结果：
参考链接： https://blog.csdn.net/yelu_hong/article/details/83856306
只能在命令行运行，代码规范要求比较严格，比如语句分号后不能有空格也报错，函数体的左大括号不能另起一行等。
因为moviemator没有遵循google代码标准，个人觉得不是很实用。
测试mainwindow.cpp，不限制等级有1006个报错，限制只显示3-5等级的有499个；不过可以用过滤器过滤不想报的错误类型。
以下是几个错误：
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:2:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:2:  Extra space before ( in function call  [whitespace/parens] [4]
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:3:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:5:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:5:  Extra space before ( in function call  [whitespace/parens] [4]
C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp:6:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]

**Comment by pisceshsu** [comment]
Cpplint 将输出结果保存为txt文件：
1. python cpplint.py --output=vs7 --verbose=3  C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp 2>log.txt

[log---verbose=3.txt](https://github.com/hansewu/MovieMator/files/3263776/log---verbose.3.txt)

2. python cpplint.py --output=vs7 --verbose=5  C:\Users\pisceshsu\Documents\MovieMator-github\MovieMator\src\MovieMator\src\mainwindow.cpp 2>log.txt

[log---verbose=5.txt](https://github.com/hansewu/MovieMator/files/3263777/log---verbose.5.txt)

**Comment by pisceshsu** [comment]
Clang Static Analyzer调研结果

https://clang-analyzer.llvm.org/
1) 集成到qt的Clang Static Analyzer工具，可以查出来33个问题，比qt自带的工具查出来的种类和数量都要多一些，但不如cppcheck多。 
2) 查出的内存泄露问题，是cppcheck查不出来的

**Comment by hansewu** [comment]
我:
好像有集成工具
我:
https://github.com/secularbird/cpplint-extension
我:
挺多具体使用的方法
我:
VSCode的C/C++插件自带了Clang-Format格式化工具，不仅拥有上述5种排版格式，还定义了自己的Visual Studio排版格式，且此格式是默认的排版格式（Ubuntu下格式化快捷键：Ctrl+Shift+I，Windows下格式化快捷键：Shift+Alt+F）
我:
自动排版功能

**Comment by hansewu** [comment]
有专门的代码质量检查工具
https://www.jianshu.com/p/cebcc401c00c
看上去正是我们需要的

**Comment by hansewu** [comment]
https://zhuanlan.zhihu.com/p/29086959
代码质量管控的四个阶段

**Comment by hansewu** [comment]
https://juejin.im/post/5cbfde7c5188250a7d6ddcd1#heading-1
一步一步，统一项目中的编码规范（vue, vscode, vetur, prettier, eslint）

**Comment by hansewu** [comment]
https://juejin.im/post/5c05eb206fb9a049fc034a94
代码审查之最佳实践

**Comment by pisceshsu** [comment]
调研带代码规范插件的代码编辑器

1. Atom, Vim, Visual Studio Code, Emacs 哪个好？
[url]https://www.zhihu.com/question/52227656/answer/134307058[/url]

2. 学习emacs能很好的提高工作效率吗？
[url]https://www.zhihu.com/question/38484391/answer/88845653[/url]

3. 如何把Emacs改造成类似于现代IDE一样的代码编辑器？
[url]https://www.zhihu.com/question/313485182[/url]

**Comment by vgawen** [comment]
工具调研已完成，需要根据调研结果考虑确定使用什么工具。

**Comment by vgawen** [comment]
初步方案：
1 编码规范采用google c++ 风格指南
2 风格检测
clang_format 检测代码格式，自动修改
cppcheck 检测代码缺陷
3 重复代码检测
simian
PMD-CPD
4 复杂度检测
SourceMonitor，只支持windows系统
5 使用github的pull request做代码审查

工具应用
第一步 使用clang_format 规范代码格式
第二步 重复代码。 使用simian检测，去除重复代码。PMD-CPD或其他重复代码检测工具多检测一遍。
第三步 cppcheck检测代码缺陷
第四步 复杂度检测，降低复杂度（SourceMonitor）

**Comment by ontheway01** [comment]
无意看见。代码检查工具推荐SonarQube 缺点：免费社区版不支持C/C++
