### ISSUE TITLE
画出文件qmlfilter、qmlMetadata 和 YFKeyframe.qml的UML关系图

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#234]
使用工具画qmlfilter metaldatamodel 和 YFKeyframe.qml出其UML关系图。

**Comment by wyl1987527** [comment]
![Uploading keyframe.png…]()
![Uploading kyeFrame2.png…]()

**Comment by hansewu** [comment]
UML黄色的和白色的有什么区别？

**Comment by wyl1987527** [comment]
UML 图说明
白色的是我开始处理这个任务的时候自己绘制的，上面有qml的YFKeyFrame类

黄色的是后来大家说有工具，我这也试了工具的出来效果对比下类之间的关系是否对，然后这个黄色的上面会有filterdock的一层层关系，就是从mainwindow过来的，但是黄色工具生成出来的没有qml类的方法属性。
