### ISSUE TITLE
总结和注释qmlfilter、qmlMetadata和 YFKeyframe.qml的对象，对象方法和对象成员变量的作用

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#235]
总结和注释qmlfilter metaldatamodel 和 YFKeyframe.qml对象，对象方法和对象成员变量的作用。

相关信息存放在UML 文件，方便以后根据UML图进行讨论。

同时注释加到头文件，方便阅读代码。

**Comment by wyl1987527** [comment]
QmlFilter、AnalyzeDelegate、QmlKeyframesParameter、QmlKeyframesMetadata  已经完成，YFKeyFrame还未完成

**Comment by wyl1987527** [comment]
摘抄部分注释
QmlFilter
/** A Boolean value that indicates whether the filter is new.
     *
     * \return true when the filter is new; otherwise, false
     */
    bool isNew() const { return m_isNew; }

    /** Sets the filter’s new property to the value specified by isNew.
     *
     * \param isNew the filter is new or not
     */
    void setIsNew(bool isNew) { m_isNew = isNew; };

    /** Get the filter.
     *
     * \return a Mlt::Filter value
     */
    Mlt::Filter *getMltFilter() {return m_filter;};

    /** Update the filter’s all key frames to the value specified by listKeyFrame.
     * Sync cache data to project
     * \param listKeyFrame the filter's new key frames
     */
    void refreshKeyFrame(const QVector<key_frame_item> &listKeyFrame) ;
/** Get a string value by name of Mlt::Filter.
     *
     * \param name the property to get
     * \return the property's string value or NULL if it does not exist
     */
    Q_INVOKABLE QString get(QString name);

    /** Get a floating point value associated to the name of Mlt::Filter.
     *
     * \param name the property to get
     * \return the floating point, 0 if not found (which may also be a legitimate value)
     */
    Q_INVOKABLE double getDouble(QString name);
