### ISSUE TITLE
根据方法和变量的作用对qmlfilter、qmlMetadata 和 YFKeyframe.qml部分方法和变量重新命名

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#236]
根据方法和变量的作用对qmlfilter metaldatamodel 和 YFKeyframe.qml部分方法和变量重新命名。

注意不要一次修改对象方法太多。

暂时保留老的函数名，并加入assert 错误提示信息。

**Comment by wyl1987527** [comment]
qmlfilter.cpp
1）path() 改成resourcePath()

2）setKeyFrameParaValue 改成cache_setKeyFrameParaValue
3）setKeyFrameParaRectValue 改成cache_setKeyFrameParaRectValue

4）getKeyFrameParaValue 改成cache_getKeyFrameParaValue
5）getKeyFrameParaDoubleValue 改成cache_getKeyFrameParaDoubleValue
6）getKeyFrameParaRectValue 改成cache_getKeyFrameParaRectValue
7）getPreKeyFrameNum 改成cache_getPreKeyFrameNum
8）getNextKeyFrameNum 改成cache_getNextKeyFrameNum
9）bKeyFrame 改成cache_bKeyFrame
10）getKeyFrameNumber 改成cache_getKeyFrameNumber

11）addedKeyFrame 改成cache_addedKeyFrame
12）removedKeyFrame 改成cache_removedKeyFrame
13）getPreKeyFrameNumInParent 改成cache_getPreKeyFrameNumInParent

14）combineAllKeyframe 改成 syncCacheToProject


15）changed()  改成 filterPropertyValueChanged()

16）m_keyFrameList 改成m_cacheKeyFrameList

17）path 改成resourcePath
18）m_path 改成m_sResourcePath


YFKeyFrame.qml

1)synchroData  改成syncUIDataToProject
2)setDatas 改成syncDataToProject

3)loadKeyFrame改成 refreshUI
4)loadFrameValue  改成updateParamsUI

5)addKeyFrameValue  改成addKeyFrame

6)saveValueCal 改成calcProjValByUIVal

7)loadValueCal 改成calcUIValByProjVal

8)findParameter  根据控件id查找配置项，查找对应哪几个参数，因为会有一个控件对应几个参数
改成
getParamsAssociatedWithControl

9) bBlockSignal 改成bBlockUpdateUI

**Comment by wyl1987527** [comment]
QmlKeyframesParameter

changed 信号改成parameterChanged

QmlKeyframesMetadata

changed 信号改成keyframesMetadataChanged
