### ISSUE TITLE
qmlfilter、qmlMetadata 和 YFKeyframe.qml 去掉编译器报的警告（开启编译选项-Wall）

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#237]
整理qmlfilter metaldatamodel 和 YFKeyframe.qml代码格式，使得符合代码标准
通过代码检测工具检测

**Comment by wyl1987527** [comment]
任务更改为：
qmlfilter、qmlMetadata 和 YFKeyframe.qml 去掉编译器报的警告（开启编译选项-Wall）

**Comment by wyl1987527** [comment]
目前只有qmlfilter 中在编译时报出了4个warning
1 个没有返回值
3个是局部变量unused

**Comment by wyl1987527** [comment]
qtcreate版本较低，报出的warning比较少，还需要用高版本，会报出一些c++语法错误。

**Comment by wyl1987527** [comment]
今天增加了这几个warning修改
[Warning] <>     QmlFilter::producerAspect
[Warning] <> QQmlExpression: Expression file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/filters_pro/size_position/SizePositionVUI.qml:119:26 depends on non-NOTIFYable properties:
调用producerAspect(),去除property ：producerAspect

[Warning] <> file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/filters_pro/size_position/SizePositionVUI.qml:55: TypeError: Cannot call method 'get' of null

[Warning] <> file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/filters_pro/size_position/SizePositionVUI.qml:38: TypeError: Cannot call method 'get' of null
[Warning] <> file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/filters_pro/size_position/SizePositionVUI.qml:39: TypeError: Cannot call method 'get' of null

property var fillStat: filter.get(fillProperty) 
property var fillStat: filter ? filter.get(fillProperty) : ''


[Warning] <> file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/modules/MovieMator/Controls/KeyFrame.qml:36: TypeError: Cannot call method 'setEnableAnimation' of null
[Warning] <> file:///Users/wyl/Library/Application Support/effectmatrix/MovieMator Pro/share/moviemator/qml/modules/MovieMator/Controls/KeyFrame.qml:44: TypeError: Cannot call method 'setAutoAddKeyFrame' of null

**Comment by wyl1987527** [comment]
qtcreate 4.9.0 版本报出的warning全部修改完
