### ISSUE TITLE
qmlfilter、qmlMetadata和 YFKeyframe.qml相关代码简单的重构道路路线图

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#238]
qmlfilter metaldatamodel 和 YFKeyframe.qml相关代码简单的重构道路路线图

**Comment by wyl1987527** [comment]
1 m_keyFrameList cache机制去除
2 动画、非动画的切换机制，彻底解决filter.set设置不成功问题
3 filter.set 和filter.get、filter.getAmimation、filter.setKeyFrameParaValue
4 关键帧undo、redo机制
5 mlt 底层动画机制实现代码功能模糊
6 qmlfilter代码的完备性
