### ISSUE TITLE
网页首页截图构图设计方案

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#240]
网页首页截图构图设计方案

要求：
一  构图
构图方案要写清楚主体是什么，背景是什么。
是什么构图方式。图片能量分布是否平衡。

如果背景图片是其他地方找的图片，要分析
1 原图的构图方式。
2 修改后图片的构图方式。

系列图片如果按一定方式排版在一起是否能互相协调？

二 颜色
系列图片的主色是什么，配色是什么。

单独某张图片主色是什么， 配色是什么。
和系列图片的色系是否一致。

三 内容和风格
系列图片的内容和风格是否有一定内在联系。

**Comment by gengxiaofeng** [comment]
截图一：
![screen_1](https://user-images.githubusercontent.com/37355589/58921939-77a40880-876b-11e9-809a-c552f71096b0.jpg)

截图二：
![screen_2](https://user-images.githubusercontent.com/37355589/58921947-7ffc4380-876b-11e9-877f-dd6207d39fa1.jpg)

截图三：
![screen_3](https://user-images.githubusercontent.com/37355589/58921956-87bbe800-876b-11e9-9fcd-9701cd383e5a.jpg)

截图四：
![screen_4](https://user-images.githubusercontent.com/37355589/58921976-930f1380-876b-11e9-901c-c6f2a7b76859.jpg)

**Comment by hansewu** [comment]
1 文字排版字体太小。
2 文字排版缺少变化。
3 目标颜色不稳定， 变成了黑色+橙黄色。
4 截图1， 缺少底部阴影，从而使得整体缺少光影效果。
5 截图2， 构图上不能把模糊图片放到中间，中间要清晰的图片。
6 截图2， 图片资源整体上都不清晰。
7 截图4， 和macphun的方法比较起来，差距比较大。变成了展示图片的感觉，而且后面叠加的图片没有拉开。

**Comment by hansewu** [comment]
美学规范分析主要用于版式耿晓峰，11:30奥奥 11:30就是叠加的资源比较多，目标比较多时要考虑的耿晓峰，11:30嗯嗯11:30当目标比较多，就需要管理。 文字很多， 所以要版式耿晓峰，11:31嗯嗯11:31图片很多，那也涉及版式耿晓峰，11:31是的 11:32第一张一定要加阴影为什么呢因为故意把整幅图拉白了没有阴影就很单调有了阴影，就让人感觉强光造成计算机屏幕放白耿晓峰，11:34嗯嗯11:34第二张 一条线上，要分析黄金分割点黄金分割点上要放最好的目标再一个缺少光影变化，就还是显得单调耿晓峰，11:35哦 嗯嗯11:36MACPHUN 有三张故意偏黑没有偏黑就没有对比耿晓峰，11:36是的 对比做的很好 11:37这个也就是涉及你说的美学规范耿晓峰，11:37嗯嗯 对比11:38第三张主要问题也是图片没有对比度像一张曝光不好的照片耿晓峰，11:38嗯嗯 11:39嗯 第四张你说的和我说的类似版式上标题字体应该和正文字体不同也是增加对比吧耿晓峰，11:41嗯嗯 是的之前下载网页模板 标题用的是衬线字体
正文用的是非衬线字体 

但看现在的网页这样用的比较少了 很多都是一种字体 ，就是有大小粗细颜色对比了11:44本身，你选的那个字体就不适合做标题耿晓峰，11:44嗯 11:44标题要端庄你选的那个字体主要用于正文，比较柔和耿晓峰，11:44macphun也是两种字体 标题是GraphikLCG-Bold
正文是Roboto Light对的

**Comment by gengxiaofeng** [comment]
与macphun网页截图对比分析：
1 与macphun网页截图对比分析
1.1 第一张截图对比分析 
![duibi1](https://user-images.githubusercontent.com/37355589/58929168-5998d100-8788-11e9-997f-f10c53ac6819.jpg)
1 整体视觉效果对比：客观上看两张截图，上图不论从构图，文字，内容，视觉效果上都要比下图好，而且要好很多
  1 电脑素材比下图的看起来更加的舒服，投影处理的更加自然，视觉上比较稳   
  2 电脑屏幕上界面截图上图也更好看，图片比较多但是统一在一张画面里，所以看上去图片比较大，图片带来的信息比界面上的细节更具有吸引力   
  3 文字大标题比下面的颜色更深以及更粗更大，看起来更具有辨识度，正文也比下面的更大更黑，阅读起来更容易阅读   
  4 上图里面的细节处理部分较多，比如电脑右边出去了一部分，在视觉上更加的宽阔以及大气，下图的就稍显小气，电脑顶部和那条暗灰色背景有交叉处理，这在细节上更加丰富，还有文字下面有四个图标，也丰富了整个截图的布局以及视觉

2 基础美学规范分析：上图中亲密性、对齐、重复、对比四大基本原则都比下图要好
  1 亲密性：上图一共三个区域：电脑软件界面、文字、图标，虽然整体看跟下面区别不大，但是单看某一个区域组合的都比下面的要好，电脑软件界面色调很统一；四个图标大小颜色样式都很统一。所以单看某块区域效果都比下面的要好，组合起来自己效果更好了   
  2 重复;重复性原则在两图中表现的不是很明显，主要是体现在细节上面，例如软件界面重复出现图片，四个图标样式颜色大小统一，不看图标内容，从方式上看图标重复了四次，加强了图标的整体效果
  3 对齐：两张图有一个最大的不同是上图通过超出页面来达到边缘的对齐，这样不重要的信息该简化就简化，减少边缘上视觉的干扰，但是下图电脑轮廓四周都是有变化的，所以在视觉上就会造成分散，上图的出血裁剪也是另一种对齐的表现：规整
  4 对比：上图要比下图好很多在对比上；首先电脑素材很大，可以和除电脑外的其他区域形成强烈对比；文字标题很粗很黑与正文文字很小很细形成对比；小图标和电脑大图以及文字形成大小对比等。下图这方面就弱了很多。

3 构图及色调：上图构图上比下图要好，视觉上比较稳，色调上上图表现的更加统一   
  1 构图：上图主要采用的是水平线构图以及矩形构图，好处是画面会很稳，电脑稍有角度变化不至于整个构图太过于死板，但是变化不会太大以免破坏了整个画面的平衡；下图就稍显不稳，电脑素材有往右倒的迹象，而且底部有点轻就会造成视觉上的不稳；上图中左右内容几乎对称，视觉上比较平衡和稳当；下图左右内容不对称，还是右边偏重了一些
  2 色调：上图所有内容都统一在饱和度比较低的偏灰色，下图软件界面颜色有点杂乱，造成视觉上的不够统一

  4 如何改进：
  1 素材，要找一个好的素材并且能发挥这张素材的长处以及规避其短处，还必须以画面的整体统一协调性为主   
  2 四大基本原则处理，根据四大基本设计原则逐条去优化，争取达到最好的效果   
  3 画面平衡和色调统一，做完画一个中轴线看看哪边画面更重以及更轻，色调上要统一在一个范围之内，如果用灰色调就整体都用灰色调   
  4 细节处理，主要是细节打磨，使整体更加的协调以及给人眼前一亮的感觉


1.2第二张截图对比分析：
![duibi2](https://user-images.githubusercontent.com/37355589/58929186-6caba100-8788-11e9-899a-ecca6ef4794c.jpg)
1 整体视觉效果对比：客观上看两张截图，上图跟沉稳，下图很浮躁
  1 上图中图片看起来比下图更沉稳以及耐看，而且整个画面也比较统一，主色调比较明确，不会有太多杂色；下图中由于图片过亮以及背景不是纯黑的，所以整体看起来就有点浮躁了，给人很刺眼的感觉 

2 基础美学规范分析：
  1 亲密性：上图标题和正文是分开的，所以整个视觉区域有三个，由于标题在画面居中位置，所以三者关联上要比下图要好一些，下图直接是分成两个区域；但是具体效果可能还与整个页面有关，单看图片的话各有千秋   2 重复;多张图片重复叠加，造成很强的视觉冲击力，两图因为采用的都是用一个表现方式，所以这方面差距不是很大 
  3 对齐：上图有有居中对齐和左对齐，下图中是左对齐，主要还是根据网页的整体做判断的，单张图可能看不出所以然来
  4 对比：上图中对比中更多的是画面的和谐，下图中就是对比上稍微欠佳了些，造成整体上有点偏灰，对比的不够彻底；另外文字上也是和截图1一个问题，文字对比也要更大才好

3 构图及色调：    
  1 构图：上图主体内容构图是三角形构图，下图主要是对称；还是需要根据整个网页内容排版确定哪种更好，单张图看各有千秋
  2 色调：上图色调处理比下图好很多，上图基本上统一在一个大的基调里，下图没有，所以下图比较浮躁看起来

  4 如何改进：
  1 色调统一，把背景改成黑色的试试，还有图片处理的更暗一些，边缘最好和周围环境能融为一体   2 字体对比再强烈些，也试下标题放中间，看下哪种方式更好  


1.3第三张截图对比分析：
![duibi3](https://user-images.githubusercontent.com/37355589/58929198-792ff980-8788-11e9-9f9b-bea181087a23.jpg)
 1 整体视觉效果对比：客观上看两张截图，上图对比更强烈，细节更丰富，更有吸引力，下图对比不够，也不够丰富，吸引力较差
  1 上图中第一感觉层次很丰富，不管是内容上还是色调上；下图就稍显单薄了
  2 上图居中对齐更彻底，更严谨，下图则没有这种严谨   
  3 上图背景以及主体文字都很平稳，下图背景就有点不够平稳   
  4 上图视觉中心很明确就是界面，下图视觉中心有点不太确定   
  5 上图文字辨识度很高，下图几乎看不清   
  6 上图内容比较紧凑，有聚有散，节奏感很强，下图内容比较松散 

2 基础美学规范分析：
  1 亲密性：上图画面里的物体几乎都聚焦在一起，最为最核心主体的界面是所有主体的核心聚焦点，有视觉聚拢的感觉；下图各个内容不太连贯，主体界面也孤零零的没有其他帮衬，就会形成视觉焦点分散    
  2 重复;上图中物体几乎都是横着摆放，下图则不太明显，特别是背景桌子边缘很破坏画面重复性原则
  3 对齐：上图是标准的居中对齐，下图则不太明确，说居中又不是居中，左对齐又不完全是，不够彻底
  4 对比：上图中色调有很暗的，也有很亮的，对比比较明确，且文字与背景颜色差别很大，所以对比就比较强烈；下图整体偏灰，缺少强有力的对比，所以整个画面会有点飘，没有给人沉稳的感觉

3 构图及色调：    
  1 构图：上图主要是水平线构图，很彻底，所以画面很稳，下面的虽说是水平线构图，但又夹杂了一些不太明确的其他构图，所以构图方式的不确定性也会给视觉造成干扰
  2 色调：上图色调是浅黄色为主，但是也有其他颜色，整体上对比很明确，又能统一在一个色调里；下图也是淡黄色为主，但是其他颜色上对比较弱，所以整体上看就有种轻飘飘的感觉

  4 如何改进：
  1 构图，这个截图最大的一个问题就是构图，构图不明确，以及构图没有达到提升主体的效果   
  2 色调，色调上层次太少，对比不够强烈，所以色彩上会显得单调   
  3 对比，整个画面偏灰，对比度不够，特别是主体与文字


 1.4 第四张截图对比分析：
![duibi4](https://user-images.githubusercontent.com/37355589/58929206-81883480-8788-11e9-9e7b-11a5741448de.jpg)
 1 整体视觉效果对比：客观上看两张截图，上图感觉更像是展示内容，下图则给人感觉使故意展示图片
  1 上图中图片虽然有叠加，但是下面的图细看还是能看到要展示的细节的，下图则更像是为了叠加而叠加，叠在下面的图看不到细节
  2 上图中视觉中心在界面弹出框那，儿下图则在图片左边   3 上图整个图的内容有向中间靠拢的感觉，下图则是两个分散开的内容 

2 基础美学规范分析：
  1 亲密性：上图整个画面比较紧凑，有往中间聚拢的视觉感受，下图则更像是两个不相关的区域内容   
  2 重复;上图中图片叠加是重复性的表现，上图能看清下面叠加的内容，下图则看不清，所以重复性原则上就差了一些，起不到重复强调的作用，只有为了表现第一张而做的铺垫
  3 对齐：上图软件悬浮框虽然没有和其他图片对齐，但是画面上整体上还是对齐的，所以这个没有对齐起到了画龙点睛的作用，大的方向还是必须遵循对齐原则，偶尔有个打破，起到点缀以及对比的作用，突出视觉焦点
  4 对比：上图中对比中有统一，图片边缘跟周围环境尽量融合的和谐，下图则没有做这个细节处理，对比中缺少统一

3 构图及色调：    
  1 构图：上图主要对称性构图，还有延伸线构图，即图片从左到右逐渐变大变清晰，把视觉焦点延伸到软件弹出框那里，还有文字，右边没有左边对齐，就会造成视觉向中间靠拢的感觉；下图则是单纯的对称性构图，没有其他细节在里面
  2 色调：上图基本上保证在大的暗色调里有局部的亮色调，下图则稍显混乱，图片吸引力过重，跟背景有点脱节，整体上不够和谐统一  

4 如何改进：
  1 表现内容上，这个是截图目前最大的缺点，内容才是最重要的，而不是为了展示漂亮的图片   
  2 构图，学习下视觉聚拢的这种构图方式，还有图片叠加的间距再大一些   
  3 对比，要保证整体的统一，然后再谈对比


 1.5 总结   
1 无论画面文字以及内容，整体的和谐统一始终要放在第一位的   
2 素材很重要，即表现在选择素材上以及对素材的处理上和因地制宜根据素材本身特点和网页整体上要统一和谐   
3 最基本的四大设计原则一定要处理好   
4 做图不能太急，里面的很多细节以及步骤必须要要求严格，这样最后出来的整体效果才能更好   
5 建立严格的自我审查流程，不是做完了自己觉得OK就行了，必须建立客观的审查标准，然后客观的按照审查标准却审查，发现问题一一记录下来，然后继续修改完善，直到达到这个标准   
6 任何时候都不能停止向高手学习，自己的能力是有限的，而且很多时候自己都不知道，唯有多去向高手学习才能真正提高自己的设计水平

**Comment by hansewu** [comment]
截图方面后续的优化放到整体方案里面一起考虑
https://github.com/hansewu/MovieMator/issues/273
