### ISSUE TITLE
界面规整和简化设计需求和设计优化方案

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#243]
界面规整和简化设计需求和设计初步方案的优化

**Comment by hansewu** [comment]
1920  * 1080 和 1440 *  980 分别作一张效果图

**Comment by vvyan** [comment]
1920*1080
![1920X1080文字效果图3](https://user-images.githubusercontent.com/37361188/58922651-6ad4e400-876e-11e9-957a-5c641fde588f.jpg)

1280*800
![1280x800  文字效果图3](https://user-images.githubusercontent.com/37361188/58922707-9eb00980-876e-11e9-9611-0fe3d539dfe2.jpg)

**Comment by vvyan** [comment]
6.5 优化内容：轨道部分
![1920X1080轨道绿色对比效果](https://user-images.githubusercontent.com/37361188/59005168-0f2e5780-884f-11e9-8630-9d39ec33f14d.jpg)
![1920X1080轨道绿色对比效果2](https://user-images.githubusercontent.com/37361188/59005169-0fc6ee00-884f-11e9-8bbc-72957b6f5dc2.jpg)
![1920X1080轨道绿色对比效果3](https://user-images.githubusercontent.com/37361188/59005170-0fc6ee00-884f-11e9-9d4d-5d39a120159c.jpg)

**Comment by hansewu** [comment]
轨道绿色的，整体效果出不来，换成 MOVAVI/FILMORA 蓝色的看一下效果

**Comment by hansewu** [comment]
上面还要画一张上面是二分图的。

**Comment by vvyan** [comment]
设计内容：轨道部分与二分图
轨道：5号设计轨道部分太过于在意绿色，一头扎在颜色里，忽略了我们的轨道上不仅仅是颜色的问题，图片和文字的显示方式也很重要，现在的轨道是结合了final cut轨道中图片和文字的布局，万兴轨道的颜色，两者相结合，发现问题的根源很重要，不然只会在里面绕。


![1280*800轨道](https://user-images.githubusercontent.com/37361188/59046969-8dbde000-88b5-11e9-81d9-d7949194a6b5.jpeg)
![1920*1080轨道](https://user-images.githubusercontent.com/37361188/59046970-8dbde000-88b5-11e9-9e95-86b828133385.jpeg)
