### ISSUE TITLE
2.5.7 win10 贴纸放大后在预览中不显示（QQ用户 千浔反馈）

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#245]
删了特效，然后改变大小就成这样子了
![贴纸问题1](https://user-images.githubusercontent.com/37360104/58414543-42822100-80ae-11e9-8609-320ebd581f42.jpg)
![贴纸问题2](https://user-images.githubusercontent.com/37360104/58414545-43b34e00-80ae-11e9-93d6-c101e5c6a84e.jpg)
在win10上没测出同样的问题

**Comment by pisceshsu** [comment]
win10上没有复现，需要再具体询问操作步骤

**Comment by hpuzj** [comment]
win7、mac10.14未复现
版本：2.5.7测试版本、2.5.7回归测试版本
