### ISSUE TITLE
2.5.7 mac导出速度太慢（QQ用户380180035 多次反馈）

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#265]
几个视频加起来34分钟，2个小时才导出7%，用的HD mp4，”10来分钟才1%“；后建议他用MP4(h264)也没什么效果
同时反馈新版本操作卡、”视频只能插入一个，无法插入多个“

**Comment by pisceshsu** [comment]
为了测试更多的错误，底层库用的是debug版本，待发布release版本再让用户试一下

**Comment by AliciaMoris** [comment]
已经邀请用户试用release版本，等待反馈中

**Comment by AliciaMoris** [comment]
截止至6.10未收到任何反馈
