### ISSUE TITLE
2.5.7回归1  添加文字滤镜时，播放器上有时间码闪动后又消失

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#267]
Mac截图
![屏幕快照 2019-05-30 下午4 20 39](https://user-images.githubusercontent.com/48675877/58619188-f5dd5680-82f6-11e9-9543-c73005cf988c.png)

Windows截图：
![屏幕快照 2019-05-30 下午5 08 18](https://user-images.githubusercontent.com/48675877/58627623-48743e00-830a-11e9-98ea-30f3715be8d4.png)

**Comment by pisceshsu** [comment]
2.6.4未重现
