### ISSUE TITLE
导出视频长度变小

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#27]
### 问题描述：
用户视频有 3:30 长，但导出只有 2:52，结尾部分会被切掉，视频切掉的位置会 变得模糊

### 来源: 
Steam

### 版本: 
Steam MovieMator 2.5.5

**Comment by hpuzj** [comment]
用户导出时，应该设置了帧/秒参数
测试过程：
1.选用一段时长为 00：03：30：02的clip（两段组合） 当前视频模式是1080p, 24帧/秒
2.导出时修改帧/秒为30 ，导出的时长为00：02：51：16
