### ISSUE TITLE
左上角filter资源往下滚动时经常弹回跳跃

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#272]
左上角filter资源往下滚动时经常弹回跳跃，不流畅。

**Comment by hansewu** [comment]
1920*1080 和 1440* 980 分别作一张效果图

**Comment by pisceshsu** [comment]
与 https://github.com/hansewu/MovieMator/issues/22 重复，  https://github.com/hansewu/MovieMator/issues/22 已关闭

**Comment by WanYuanCN** [comment]
使用 Reater代替 ListView，一次性加载所有滤镜
