### ISSUE TITLE
QQ用户kevin: 视频播放卡

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#280]
QQ用户kevin： 2.5.7 win
多个文件在同一轨道的时候会卡
就是那种快闪镜头，很多张照片放到很短的时间轴里，就会卡

**Comment by debelliszhu** [comment]
QQ用户千浔：剪大师优化做的不够好，超过200m的文件基本上就卡死

QQ用户毛一戈 ： 播放视频很卡，win10， 3分半钟的视频，卡成PPT

**Comment by hpuzj** [comment]
QQ用户kevin问题：添加了几十个文件到同一个轨道，时长在8小时左右，包括手机拍摄的图片和视频、视频软件下载的视频(优酷、腾讯、电驴等)，播放未见卡顿
QQ用户千浔问题：向轨道添加的是视频大小为1.22G，播放未见卡顿
QQ用户毛一戈问题：发现该用户视频是在资源库直接预览的，测试时在资源库直接预览未见卡顿


### **来源：**
win 7测试
jiandashi.com下载

**Comment by debelliszhu** [comment]
用户毛一戈的视频（4K，1G，但是只有3分钟）存放：
链接：https://pan.baidu.com/s/1ZeeK0KAUY9_BRIAb0qI_XQ 
提取码：n3de 
![卡成PPT](https://user-images.githubusercontent.com/37359992/59000876-12b9e280-883f-11e9-8e15-aa634ae6b6a4.jpg)

**Comment by hpuzj** [comment]
用户毛一戈的视频：分辨率 4096x2160 kmv格式
1）使用MovieMator测试，直接在资源预览播放，图像和声音都卡
2）使用爱奇艺、腾讯播放，播放效果和MovieMator一样卡顿，优酷播放效果卡顿轻微
3）使用vlc播放，声音不卡，但图像花屏
4）使用万兴喵影工厂预览，声音不卡，但图像几乎不动
5）moviemator使用优酷客户端下载的4096x2160分辨率的MP4视频播放不卡顿

### **来源**
mac10.14 steam下载2.5.7
win7 jiandahsi.ccom下载2.5.7
