### ISSUE TITLE
ScrollView.qml: QML : Possible anchor loop detected on fill.

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#292]
[Warning] <> file:///C:/Projects/moviemator/lib/qml/QtQuick/Controls/ScrollView.qml:344:13: QML : Possible anchor loop detected on fill.

**Comment by Dragon-S** [comment]
添加文字滤镜过程中产生此警告

**Comment by WanYuanCN** [comment]
将文字滤镜中TextArea的wrapMode改为Text.Wrap，警告消除。Qt助手中提到“If you set a width, consider using TextEdit.Wrap.”。修改后，滤镜设置界面的文字内容会自动换行，以前的不会自动换行而是一行显示。
