### ISSUE TITLE
MLT日志提示 WARING：The DeckLink drivers not installed

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#295]
The DeckLink drivers not installed

**Comment by Dragon-S** [comment]
主要原因是moviemator使用的mlt中没有DeckLink 这个插件。由于moviemator暂时用不到DeckLink ，因此在编译mlt时将其禁用（ --disable-decklink ）。

DeckLink
https://www.blackmagicdesign.com/products/decklink/workflow
