### ISSUE TITLE
日志WARING：QMainWindow::saveState(): 'objectName' not set for QToolBar 0x34042880 ''

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#297]
[Warning] <QToolBarAreaLayout::saveState> QMainWindow::saveState(): 'objectName' not set for QToolBar 0x34042880 ''

**Comment by Dragon-S** [comment]
手动new的QToolBar 缺少objectName，由于在 QMainWindow::saveState():时会用到objectName，因此会报警告

**Comment by Dragon-S** [comment]
同样的问题
[Warning] <QDockAreaLayoutInfo::saveState> QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x4aa3eec0 ';
[Warning] <QDockAreaLayoutInfo::saveState> QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x4aa3ea40 ';
