### ISSUE TITLE
QmlFilter 去掉 m_keyFrameList 方案

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#300]
QmlFilter 去掉 m_keyFrameList 可行性和实现方案。

接口保持和以前的一致。

**Comment by wyl1987527** [comment]
1 m_keyFrameList 作用
 cache 机制存储关键帧的相关信息,存储的是当前滤镜的所有关键帧列表，按照位置去存储的。


2 使用m_keyFrameList的地方

1）
MltAnimation 的获得可以通过filter的parameter的name 生成出来。
cache_getKeyFrameNumber()
MltAnimation有直接接口，int key_count()  ，，这个要注意，因为默认是只要加了关键帧就会哟第0帧的。对裁剪过的要考虑如何处理。


getKeyFrame(int index)
MltAnimation有直接接口，int key_get_frame( int index );


cache_bKeyFrame(int frame)  
MltAnimation有直接接口，bool is_key( int position )

cache_getPreKeyFrameNumInParent(int currentKeyFrame)
MltAnimation有直接接口，int previous_key( int position );

cache_getNextKeyFrameNum(int currentKeyFrame)
MltAnimation有直接接口，int next_key( int position );



cache_getKeyFrameParaDoubleValue(int frame, QString key)
MltProperties有直接接口，double anim_get_double( const char *name, int position, int length = 0 );


cache_getKeyFrameParaRectValue(int frame, QString key)
MltProperties有直接接口，mlt_rect anim_get_rect( const char *name, int position, int length = 0 );
			
cache_getKeyFrameParaValue(int frame, QString key)
MltProperties有直接接口，char* anim_get( const char *name, int position, int length = 0 );

cache_setKeyFrameParaValue(int frame, QString key, QString value)
removeKeyFrameParaValue(int frame)

syncCacheToProject()
一次性更新所有参数，之前是只要更改一个数据，就更新所有参数，觉得没有必要，可以改成每次就更新一个数据

refreshKeyFrame(const QVector<key_frame_item> &listKeyFrame)
可以直接在此函数中实现功能，不需要存下来

**Comment by wyl1987527** [comment]
mlt 底层研究部分记录
set 动画，set时，动画信息丢失。

set ，set anima-》set信息没有丢失。


set 动画，set，get 动画信息-》得到的是set的int值（因为此时self->animation== NULL）
set 动画，set，get-》得到的是set的int值（因为此时self->animation== NULL）

set，set动画，get 动画信息-》得到的是set动画信息
set，set动画，get -》得到的是set的值

**Comment by hansewu** [comment]
挺好MLT 分析的很好可以增加个测试函数wyl1987527，9:37嗯嗯，好的9:38保证结果是按自己的想法在跑wyl1987527，9:39嗯嗯9:39MLT 有个animation **单元测试**可以参考一下wyl1987527，9:40嗯嗯，好的。

9:46 function testNormalKeyFrameState()
{
var fgcolourNormalOld = filter.getRectOfTextFilter(fgcolourProperty)

filter.set(fgcolourProperty, Qt.rect(254.0, 254.0, 254.0, 254.0))

filter.setEnableAnimation(true)

filter.setKeyFrameParaRectValue(0, fgcolourProperty, Qt.rect(250.0, 250.0, 250.0, 250.0), 1.0)
filter.setKeyFrameParaRectValue(2, fgcolourProperty, Qt.rect(25.0, 25.0, 250.0, 250.0), 1.0)

var fgcolourNormalAfterKeyFrame = filter.getRectOfTextFilter(fgcolourProperty)

removeAllKeyFrame()

var fgcolourNormalAfterRemoveKeyFrame = filter.getRectOfTextFilter(fgcolourProperty)

filter.set(fgcolourProperty, fgcolourNormalOld)

var fgcolourNormalRestore = filter.getRectOfTextFilter(fgcolourProperty)

console.log("testNormalKeyFrameState fgcolourProperty 1 ", fgcolourNormalOld, " 2 ", fgcolourNormalAfterKeyFrame, " 3 ", fgcolourNormalAfterRemoveKeyFrame, " 4 ", fgcolourNormalRestore )
}我在TEXT UI.QML 写的一点测试
wyl1987527，9:47哦哦，好的，可以参考下:)9:48现在MLT里面**非关键帧值和关键帧值的存储**还是有个问题的模板里面geometry=0~=0.0375 0.7625 0.564844 0.140278 1;13~=0.0375 0.7625 0.564844 0.140278 1这样直接给属性设置个字符信息自动有关键帧值但非关键帧值会一直是这个字符串wyl1987527，9:51嗯嗯，是的9:52这个造成， 现在一刷模板，没办法恢复以前的值wyl1987527，9:53嗯嗯，它这个现在数据是分来存的，但是set的时候影响了动画的数据，设置动画的数据又没影响到非动画的数据。而模板这个设置的字符串所以它没有拿设置动画后实际的单个set的值。9:54嗯wyl1987527，9:54如果说有这个机制，其实非动画的值也是存着的，但是现在没有，昨天我还特地看了这个9:54对本来希望删掉动画，自动恢复非关键帧值这个现在不好弄要动底层的刷新机制wyl1987527，9:56嗯嗯，是的本来希望删掉动画，自动恢复非关键帧值 ---这个主要就是读取模板的都有问题的，**只要是以一个字符串形式的都是有问题**。暂时就没有动画数据设置后，非动画数据的一些问题处理机制。9:57嗯 它里面就是根据字符串去重新分析动画信息的wyl1987527，9:58而且现在是一旦设置了非动画的状态，底层的机制也会立马将动画的信息全部去除了。是的9:58底层应该把单字符和动画字符分开存储wyl1987527，9:58嗯嗯，这样就不影响了现在共用了一个prop_string的9:59嗯还有个问题，我不知道现在怎么处理的就是关键帧超出了CLIP 之外调用模板后，关键帧超出了CLIP 之外这个会不会有问题wyl1987527，10:01上层，没有做特别处理，超出了之外应该是不影响的。当时是记得是考虑到这个点的。10:02但添加关键帧时，会使用关键帧长度anim_set 需要长度信息设置后，会不会乱掉？我没仔细分析过wyl1987527，10:06应该不会的
1）如果是裁剪超出的，记得长度是按照**filter的length**。
2）如果不是裁剪的，而是直接是设置位置超出的，是不在那个clip的长度范围内的。10:07就是说裁剪后，再添加关键帧里面length 不知道有没有存储到每个属性里面wyl1987527，10:12每个动画的那个对象mlt_animation 存了 设置的length。但是property中没有存length10:13嗯 关键帧算法，应该和长度有关系wyl1987527，10:14就是每个设置了动画数据了，那么这个数据的length中存的就是我们上面设置的length。10:14是啊wyl1987527，10:23就是说裁剪后，再添加关键帧
----这个 我记得现在的机制上层应该是裁剪后，添加的关键帧不会出现超出clip的范围，印象中是有这个处理，超出的可能就遍历获取不到了。等于是抛弃了。10:24超出是个问题，主要还有个问题length 信息以前添加的 length 和后来裁减过的不一样wyl1987527，10:28应该是要一样还是不一样呢？
我这理解的是一样的。所以当初处理的是一样的。10:29裁剪，它不可能还去改length了吧wyl1987527，10:29因为当初理解的即使裁剪过了，但是对filter来说设置的关键帧位置啥还是没裁剪的位置。是的10:29我猜测wyl1987527，10:30我感觉它就要一样的吧？即使裁剪过也是用没裁剪的length10:30filter的length是CLIP的length吧不是文件的wyl1987527，10:30不是的是那个文件的10:31那是开始的wyl1987527，10:31对的clip是和producer的一样的。10:31后面设置过的wyl1987527，10:31说错了我自己设置过的10:32是啊

**Comment by wyl1987527** [comment]
1)cache_getKeyFrameNumber()
可以使⽤用MltAnimation的int key_count()接⼝口来实现，这个接⼝口是最后是直接使⽤用的
c接⼝口的mlt_animation这个对象。这个接⼝口是mlt底层直接获取有多少animation_node的即 有多少个关键帧。不不过这个接⼝口是MltAnimation，即依赖于具体某个参数的。 另⼀一个要注意，mlt底层默认是只要加了了关键帧就会有第0帧的。对裁剪过的要考虑如何处 理理。没有裁剪的刚好⾃自动在⾸首尾帧加了了关键帧，但是裁剪过的譬如中间⼀一段，增加关键帧 会出现3帧，实际上有4帧。因为上层⾸首尾帧删除不不掉，除⾮非使⽤用remove all的⽅方法，这个 ⽅方法实现时注意需要全部删除即可。
 在获取个数时，完全就采⽤用底层获取出来多少个关键帧就是多少个关键帧，不不过如果
关键帧个数是1时，就应该等于是没有动画功能。
2)getKeyFrame(int index)
可以使⽤用MltAnimation的 int mlt_animation_key_get( mlt_animation self,
mlt_animation_item item, int index )接⼝口实现，这个接⼝口是直接使⽤用的mlt_animation这 个对象，获取出第index个keyframe的动画项。这个动画项mlt_animation_item结构体中可 以获取出来关键帧的位置信息。 不不过这个接⼝口是MltAnimation，即依赖于具体某个参数的。
3)cache_bKeyFrame(int frame)
可以使⽤用MltAnimation的bool is_key( int position )接⼝口获得，即依赖于具体某个参
数的。
4)cache_getPreKeyFrameNumInParent(int currentKeyFrame)
使⽤用MltAnimation的int previous_key( int position )接⼝口，即依赖于具体某个参数的。
5)cache_getNextKeyFrameNum(int currentKeyFrame)
使⽤用MltAnimation的 int next_key( int position )接⼝口， 即依赖于具体某个参数的。
6)cache_getKeyFrameParaDoubleValue(int frame, QString key) MltProperties有直接接⼝口，
double anim_get_double( const char *name, int position, int length = 0 );
7)cache_getKeyFrameParaRectValue(int frame, QString key) MltProperties有直接接⼝口，
mlt_rect anim_get_rect( const char *name, int position, int length = 0 );
8)cache_getKeyFrameParaValue(int frame, QString key) MltProperties有直接接⼝口，
char* anim_get( const char *name, int position, int length = 0 );
9)cache_setKeyFrameParaValue(int frame, QString key, QString value) 这个接⼝口是为了了写数据到缓存m_keyFrameList中的，现在使⽤用这个接⼝口的地⽅方都是使 ⽤用完了了，后⾯面会紧接着使⽤用数据同步到mlt底层中。可以直接写到底层去，完全可以去除这
个函数，直接将数据写到mlt底层去即可。譬如直接根据参数类型使⽤用MltProperties中的⼏几 个anim_set接⼝口。即在这个接⼝口中直接设置，同时更更新界⾯面。
keyFrame的undo、redo 之前的数据实际存储的是m_cacheKeyFrameList，这⾥里里可以 考虑改成和set的采⽤用的是类似的机制，数据存储的就是当前需要更更改的值，和改之前的值， 同时将关键帧的位置信息记录下来即可。这个时候存储的就是需要有filter对象、参数信息、 关键帧位置、参数设置前后的值。
10)removeKeyFrameParaValue(int frame) 这个接⼝口是为了了删除缓存m_keyFrameList中数据的，现在使⽤用这个接⼝口的地⽅方都是使
⽤用完了了，后⾯面会紧接着使⽤用数据同步到mlt底层中。完全可以去除这个函数，直接将数据写
到mlt底层去即可，即直接删除frame位置的关键帧，在这⾥里里删除动画和添加不不⼀一样，添加 是使⽤用MltProperties这个类，删除需要使⽤用MltAnimation这个类，使⽤用这个类中的int remove( int position )这个接⼝口，依赖于某个参数了了。即要将所有参数的这个位置的动画都 要删除。
这个接⼝口之前没有处理理undo、redo，即删除关键帧没有undo操作，应该也是要有的， 这个时候存储的就是需要有filter对象、参数信息、关键帧位置、参数的值。这个的undo、 redo就要考虑关键帧的增加、移除的undo、redo。
11)syncCacheToProject() ⼀一次性更更新所有mlt底层的参数，之前是只要更更改⼀一个数据(增加、删除、修改)，就更更
新所有参数，觉得没有必要，效率可能还有影响，可以改成每次就更更新⼀一个数据。这个除了了 更更新参数，还更更新了了播放预览串串⼝口的显示。如果(9)(10)修改成直接更更改到底层数据了了， 那么这个同步到底层的函数就可以抛弃了了。之前这个同步函数有刷新界⾯面部分的代码， MLT.refreshConsumer()和emit filterPropertyValueChanged()，现在如果不不 要这个同步了了，那么在直接修改底层的数据的代码部分要加上这两句句代码 MLT.refreshConsumer()和emit filterPropertyValueChanged()，即qmlFilter对象的 setKeyFrameValue 和removekeyFrame这些函数执⾏行行最后加⼊入。现有这些函数有
emit filterPropertyValueChanged()，但是没有MLT.refreshConsumer()，这个是需要的， 更更新预览窗⼝口的，如当前关键帧处的位置修改参数的值，此时anim_set之后需要看到预览 的效果发⽣生改变，就要这句句代码。之前都是set和remove关键帧之后都同步数据，都在同 步数据这个函数中加⼊入的。
12)refreshKeyFrame(const QVector<key_frame_item> &listKeyFrame) 可以直接在此函数中实现功能，不不需要存下来之后再进⾏行行数据同步，完全可以直接调⽤用filter 的anim_set将所有参数、所有位置全部设置。
以上接⼝口中使⽤用到的MltAnimation对象，都可以通过filter的parameter的name ⽣生成出来。因 为现在接⼝口的上层使⽤用没有依赖参数name，所以这⾥里里使⽤用时，还可以不不依赖参数名字，不不过可 以是接⼝口加⼊入默认的输⼊入参数，参数name，对默认情况的参数name进⾏行行查找选择合适的参数 然后获取MltAnimation，获取这个对象的参数要注意是⽀支持关键帧的，因为会有些参数不不⽀支持 关键帧，默认情况下⽀支持查找，其它不不⽀支持。将查找合适的MltAnimation这个可以封装到⼀一个 函数中，这样如果后期代码更更改成依赖参数名字，也很⽅方便便更更改。
接⼝口中使⽤用到的MltProperties对象直接就是QmlFilter中的Mlt::Filter对象。
3 附录
3.1 mlt 底层动画部分的某些接口理解记录
(1) filter 的数据以及动画信息数据是以参数分开存储的，即以 property 进⾏行行分开存储的。⼀一 个 filter 有多个 property。每个 filter 对应⼀一个 properties 的列列表，以 property 的 name 为 key 。
(2)每个 property 对应界⾯面的⼀一个参数(⼤大部分是这么处理理的)，有些早期界⾯面不不是这么处理理 。参数的动画信息和参数的⾮非动画信息都存在这个单⼀一的 property 中，⾮非动画数据，其参数的 就存在 mlt_property 这个结构体中的 prop_int 和 prop_double 等这些个变量量中，同时还存了了参 数类型。
动画数据存在mlt_animation animation变量量中，这⾥里里存储的动画信息。动画和⾮非动画数据是分 开存储的。
(3)⾮非动画数据设置时，会清空这个 property 的之前所有动画和⾮非动画数据。 (4)动画数据设置时，不不会清空 property 之前设置的⾮非动画数据，只会在当前动画数据基础上 插⼊入以及新增加设置动画数据。 (5)获取⾮非动画数据，直接获取之前设置的⾮非动画数据，不不论中间有没有设置过动画和⾮非动画 都可以获取到。 (6)获取动画数据，如果当前有动画数据存储，就获取动画数据，如果没有就获取⾮非动画数据 。
(7)set 之后，amin_set 动画，不不会改变⾮非动画的数据，获取动画和⾮非动画的数据信息都 存在。
(8)anim_set 动画，set 时，动画信息丢失。获取动画和⾮非动画的数据最后得到的结果都 是 set 的结果(⾮非动画的数据)。
(9)mlt 底层算法出现了了有时直接通过 self-> animation 属性来获取 string 的，这个时 候就等于不不管是动画的还是⾮非动画的，只要有动画数据存在(当 set 之后，继续 anim_set ，就会存在两个数据都有)就获取动画数据，不不过使⽤用这个的都是为了了获取当前这个 property 是否有值的。譬如 char* level_property = mlt_properties_get( properties, "level" );
(10)不不论是动画还是⾮非动画的数据，⾮非动画的参数不不论是 int、double 型的都会给 prop_string 赋值，这个赋值是跟(9)中涉及到的相关，即不不论动画和⾮非动画都可以通过 string 得到值，不不过为了了确保从 string 必须得到需要在获取之前调⽤用 mlt_properties_get 。动画的 string 是通过 mlt_animation_serialize 这个函数设置的，设置的格式是“ 时间 =value;时间=value” 。
(11)mlt_animation_parse 这个接⼝口在不不断的重新解析动画的数据，将解析出来的数据重 新存成动画的 node，这个对关键帧个数等获取都有直接影响，譬如这⾥里里上⾯面说到的获取关 键帧个数，上⼀一个关键帧位置、下⼀一个关键帧位置等等这些接⼝口都是直接遍历动画的 node 。这个接⼝口在 refresh_animation 中会调⽤用到，这个接⼝口调⽤用频率⽐比较⾼高。
