### ISSUE TITLE
按方案实现QmlFilter 去掉 m_keyFrameList 

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#301]
按方案实现QmlFilter 去掉 m_keyFrameList

**Comment by wyl1987527** [comment]
1 cpp 部分的所有接口都已经处理完了，去除cache机制
2 qml代码中之前有不少部分的filter set 和 filter setKey 使用出错了，基本是重要的函数都有问题，只要是使用到set 和 setKeyFrame的都需要处理考虑下，譬如加关键帧、刷新界面、界面改变这些都有问题，而且之前经常调用同步数据，这些都有问题。为什么之前不出错？之前不出错是因为实际mlt底层起作用的是filter set的数据，动画的数据起作用的一直是cache中的数据。譬如经常会发现代码中有filter set ，一旦去除了cache机制，fiter set时就会将底层的动画和非动画数据清除了，然后设置非动画数据，此时如果再获取动画数据是全部丢失的，但是现有界面没有出问题，是因为总是refresh 界面等等，即使这样现在代码也是有点小问题的。之前使用这个机制也不是不出错，也会出错的，只是几个关键功能没有大问题，因为细看代码就知道有问题的。
总之之前的qml中使用就等于动画没有依赖底层，但是有时有依赖底层，mlt底层没有完全使用上，对set 和setkey之间的使用会造成动画和非动画数据的影响没有理清楚造成的。

这也是为什么之前总是会出现一些奇怪问题，但是也不是太好解决：譬如会出现上一个关键、下一个关键帧这些消失，明明有关键帧，还有总是会数据同步不对，以及会出现一旦改变一个参数值，但是这个值不加入到动画中，那么此时播放会界面数据一直不会改变，直到遇到了关键帧才改变，都是因为底层动画被清除了，而cache机制和底层又没有对应上。

**Comment by hansewu** [comment]
去掉m_keyFrameList  后发现QML相关代码有隐藏的BUG。

wyl:
"cache机制一旦去除，动画的数据我们都是直接用底层，qml keyframe的代码就需要更改，因为之前那个机制底层的动画其实没有用到，只在刷新用了下。嗯嗯等于这两个都要改完，才能算cache机制去除好了。"

此问题单独添加 ISSUE：
https://github.com/hansewu/MovieMator/issues/361

**Comment by wyl1987527** [comment]
现有进展处理：YFKeyFrame的参数变化函数，这个函数中也处理的差不多了，但是有一个难点再考虑合适的方法：就是在动画情况下有时是不自动增加关键帧的情况，即改变参数看到效果，但是又不是自动加入关键帧
