### ISSUE TITLE
点击左上角filter列表中的FILTER 在视频播放窗口预览播放

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#302]
点击左上角filter列表中的FILTER 在视频播放窗口预览播放

可以采用静态图片， 1S 显示原图， 5S 显示FILTER变换后的图片。

**Comment by fuyunhuaxin** [comment]
现目前是用的每个滤镜的默认效果，效果基本都能出的来。有两点问题：
1 个别滤镜（比如白平衡）会全部变黑或全部变白。
2 少数滤镜的默认效果看不出来。
这两个问题需要专门新建一个配置文件配置每个滤镜单独的预览效果参数。这一步留在后面需要的时候特殊处理。

**Comment by vgawen** [comment]
新问题：
1 webvfx相关的滤镜都显示白色，比如3d文字、环形边框，这种不是缺省参数问题。
2 防抖动，图片无法看效果。就算是视频也需要先点配置界面的"分析"才能起作用。

**Comment by fuyunhuaxin** [comment]
目前两个问题：
1 滤镜预览之后，只能点击时间线或clip才能切换回来，不能自动切回来。
2 有4个滤镜全黑或全白，另有一小部分没效果（其中大部分是本来就没效果，或者要特殊图片才能有效果。另一部分是效果要调节参数才能出来，默认参数是出不来的）。现目前预览滤镜都是直接加上滤镜，滤镜本身有参数默认值。程序里面能拿到的滤镜参数m_metadataModel有几种情况：
    （1）老的滤镜无关键帧：meta文件里面本来就没有配置参数名称和默认值，直接都是ui文件里面配的，而程序里面的滤镜参数配置信息都是读取meta文件里面的。
    （2）老的滤镜有关键帧：meta文件里面配有各个关键帧参数的配置项。程序也能读取到m_metadataModel里面
    （3）frei0r滤镜：动态生成的，所以没有meta文件，但是能生成配置项在m_metadataModel里面，但是frei0r没有提供默认值接口，所以配置项里面有参数名称，但是没有该参数的默认值。

**Comment by fuyunhuaxin** [comment]
[滤镜参数配置.txt](https://github.com/hansewu/MovieMator/files/3288585/default.txt)

**Comment by fuyunhuaxin** [comment]
1 滤镜预览之后，只能点击时间线或clip才能切换回来，不能自动切回来。
----问题已经解决，当播放预览的时候，添加滤镜，会自动切回时间线上的播放。

**Comment by fuyunhuaxin** [comment]
少部分滤镜默认值没效果或者效果不对，还需要解决一下。
