### ISSUE TITLE
时间线右键菜单修改，菜单需要有快捷键信息

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#304]
时间线点击视频片段右键菜单，菜单增加和修改为

27 时间线点击视频片段右键菜单，菜单增加和修改为：

切割
插入资源
分隔线
删除
删除并关闭空隙
分隔线
剪切
复制
粘贴
分隔线
缩放到合适
添加滤镜

28 时间线点击轨道空白处，右键菜单调整为
切割
追加资源
分隔线
粘贴
分隔线
增加视频轨道
增加音频轨道
删除轨道
分隔线
轨道关闭视频
轨道关闭音频

**Comment by hansewu** [comment]
参看设计：
https://github.com/hansewu/MovieMator/issues/187

**Comment by WanYuanCN** [comment]
关于时间线右键菜单的一点疑问，现在的时间线轨道空白处的右键菜单有三种：
![图片](https://user-images.githubusercontent.com/44854531/59187336-d4f2ec00-8ba7-11e9-89f5-e544ade79d73.png)
![图片](https://user-images.githubusercontent.com/44854531/59187398-f3f17e00-8ba7-11e9-9fd2-c472ee02f3c6.png)
![图片](https://user-images.githubusercontent.com/44854531/59187455-11264c80-8ba8-11e9-8434-c5698157f700.png)
后两种的菜单是一样的，但是区域不一样，新修改的菜单增加了一些功能
![图片](https://user-images.githubusercontent.com/44854531/59187219-88a7ac00-8ba7-11e9-9c66-52b8603da5a8.png)
