### ISSUE TITLE
代码检查工具专家意见归纳

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#306]

**Comment by pisceshsu** [comment]
[代码质量控制调研-思维导图.pdf](https://github.com/hansewu/MovieMator/files/3271591/-.pdf)

参考链接：
1. 代码质量管控的四个阶段
https://zhuanlan.zhihu.com/p/29086959 

2. 从Code Review 谈如何做技术
https://coolshell.cn/articles/11432.html

3. 如何提高代码质量
 https://zhuanlan.zhihu.com/p/39305285

4. 代码质量检测-Sonar
https://blog.csdn.net/liaomin416100569/article/details/79230610

5. 本地搭建SonarQube并集成Jenkins进行代码质量管理(For windows) 
https://zhuanlan.zhihu.com/p/22926742

6. 让你的代码更Prettier！代码风格统一终极方案！
https://zhuanlan.zhihu.com/p/37478644

7. 技术管理者---提升研发代码质量---总体方法论
https://blog.csdn.net/chengyun19830206/article/details/82846419

8. 代码质量管控 -- 复杂度检测
 https://zhuanlan.zhihu.com/p/29438120

9. 谈一谈开发团队代码质量如何管控与提升
https://ningyu1.github.io/site/post/111-code-quality-management/

10.大家的公司的 Code Review 都是怎么做的？遇到过哪些问题？
https://www.zhihu.com/question/41089988/answer/89651601

11.如何用人类的方式进行 Code Review
https://zhuanlan.zhihu.com/p/31581735

12.如何用人类的方式进行 Code Review（二）
https://zhuanlan.zhihu.com/p/31786640

13.为什么bat很多部门不进行code review?
https://www.zhihu.com/question/42000238

调研带代码规范插件的代码编辑器

14.Atom, Vim, Visual Studio Code, Emacs 哪个好？
https://www.zhihu.com/question/52227656/answer/134307058

15.学习emacs能很好的提高工作效率吗？
https://www.zhihu.com/question/38484391/answer/88845653

16.如何把Emacs改造成类似于现代IDE一样的代码编辑器？
https://www.zhihu.com/question/313485182

17. Visual Studio Code 如何编写运行 C、C++ 程序？
https://www.zhihu.com/question/30315894
     
18. 好用的vscode插件
   https://www.cnblogs.com/foohack/p/7773061.html

19. QtCreator 代码格式化Google
https://blog.csdn.net/qq_22207951/article/details/80220393

**Comment by pisceshsu** [comment]
[代码质量管理专家意见归纳_徐金萍_20190610.pdf](https://github.com/hansewu/MovieMator/files/3279969/_._20190610.pdf)

**Comment by pisceshsu** [comment]
修订版，增加了当前提高代码质量管理的建议，
[代码质量管理专家意见归纳_徐金萍_20190610.pdf](https://github.com/hansewu/MovieMator/files/3284812/_._20190610.pdf)
