### ISSUE TITLE
试用自动代码检测工具

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#307]
### 需要试用的工具有：
1.SourceMonitor
函数圈复杂度，函数个数等重要指标检测工具
参考：软件质量之道：SourceMonitor
    https://blog.csdn.net/feng_ma_niu/article/details/40594799 

2.重复代码检测工具 PMD-CPD,  CCCD, CCFinder, CodePro  
   参考链接：https://www.jianshu.com/p/59a6d409b8c4

3. VSCode
4. SonarQube

### 试用要求：
1) 支持哪些系统，如何配置
2) 能测出哪些问题，
3) 是否能继承到qt
4) 试用过程中有哪些注意事项

**Comment by hpuzj** [comment]
试用Google代码格式化工具clang-format

1.brew install clangformat
2.Qt >>关于插件 >>启用Beautifier插件后 >>重新启动qt
3.点击「偏好设置」在左侧菜单找到Beautifier
4.Clang format:
1) 在Clang format command中选择clang-format路径: 
/usr/local/Cellar/clang-format/2019-01-18/bin/clang-format
2）可选择预定义风格（use predefined style) ：LLAM、 Google、Chromium、Mozilla、WebKit、File
3）自定义代码风格（use customized style）:需要在给定的预定义风格基础上进行自定义
例如：
#基础样式
BasedOnStyle: Google
#指针的*的挨着哪边
PointerAlignment: Right
# 缩进宽度
IndentWidth: 4
# 连续的空行保留几行
MaxEmptyLinesToKeep: 1
# 圆括号的换行方式
BreakBeforeBraces: Attach
# 是否允许短方法单行
AllowShortFunctionsOnASingleLine: true
# 支持一行的if
AllowShortIfStatementsOnASingleLine: true
# 在未封闭(括号的开始和结束不在同一行)的括号中的代码是否对齐
AlignAfterOpenBracket: true
# 圆括号的换行方式
BreakBeforeBraces: Attach
# switch的case缩进
IndentCaseLabels: true
# 针对OC的block的缩进宽度
ObjCBlockIndentWidth: 4
# 针对OC，属性名后加空格
ObjCSpaceAfterProperty: true
# 每行字符的长度
ColumnLimit: 0
# 注释对齐
AlignTrailingComments: true
# 括号后加空格
SpaceAfterCStyleCast: false
# 换行的时候对齐操作符
AlignOperands: true
# 中括号两边空格 []
SpacesInSquareBrackets: false
# 多行声明语句按照=对齐
AlignConsecutiveDeclarations: false
# 容器类的空格 例如 OC的字典
SpacesInContainerLiterals: false
# 在构造函数初始化时按逗号断行，并以冒号对齐
BreakConstructorInitializersBeforeComma: true
# 函数参数换行
AllowAllParametersOfDeclarationOnNextLine: true
# 每行字符的长度
ColumnLimit: 120
#在续行(\
# 下一行)时的缩进长度
ContinuationIndentWidth: 4
# tab键盘的宽度
TabWidth: 4
# 赋值运算符前加空格
SpaceBeforeAssignmentOperators: true
# 行尾的注释前加1个空格
SpacesBeforeTrailingComments: 1
5.在偏好设置>环境>键盘>设置clang-format 的快捷方式ctrl+Alt+k
6.对于.cpp文件中不需要修改代码风格的代码可以使用

  // clang-format off
 不需要修改的代码
  // clang-format on
  
7.试用结果
选中mainWindow.cpp,使用快捷键ctrl+Alt+k，代码直接转换成google代码风格
1）对于像mainWindows这种代码行数为4628行，代码转换失败，代码太长
提示：Error in Beautifier: Cannot call /usr/local/Cellar/clang-format/2019-01-18/bin/clang-format or some other error occurred. Time out reached while formatting file /Users/apple/Downloads/MovieMator-github/MovieMator/src/MovieMator/src/mainwindow.cpp
2）Main.cpp文件修改代码风格后报错：:-1: error: symbol(s) not found for architecture x86_64
解决方法：屏蔽头文件：#include <framework/mlt_log.h>
3).qml文件不能进行代码格式化

**Comment by pisceshsu** [comment]
SonarQube试用情况：
1. 成功下载SonarQube, 
2.安装 SonarQube
   1) cd xx/SonarQube/sonarqube-7.7/bin/macosx-universal-64/
   2) ./sonar.sh start

    但安装过程中，提示需要安装Java JDK, 按提示下载了jre-8u211-macosx-x64.dmg, 安装后还是无法识别java命令，需要重新下载jdk, 目前正在下载中

**Comment by hpuzj** [comment]
试用vscode
1.直接安装vscode应用程序
2.在「扩展」安装需要的插件：C/C++  cppcheck   clang formator等等
3.在安装的插件右下键，点击设置，选择「配置扩展设置」，根据需要将设置添加到settings.json中
![屏幕快照 2019-06-12 下午5 11 34](https://user-images.githubusercontent.com/48675877/59338615-41e7bc80-8d35-11e9-86c9-096082e9f349.png)
4.添加.cpp文件或者moviemator文件夹，按F1键，在命令面板打开settings.json或者相对应插件的命令，对代码进行检测
5.暂时未找到怎么直接覆盖全部文件

**Comment by hpuzj** [comment]
1.SourceMonitor目前只支持Windows系统
2.可以配置到qt作为外部工具使用
https://www.jianshu.com/p/b83c48888af6?utm_source=oschina-app
3.已经配置到qt中，暂未使用
4.明天将win  moviemator跑通，再执行SourceMonitor，查看执行结果

**Comment by hpuzj** [comment]
Source Monitor客户端测试moviemator
### **测试结果：**
以单个.cpp文件为例
![总文件目录](https://user-images.githubusercontent.com/48675877/59490617-bf3b3a80-8eb7-11e9-94b4-ab4bb4f5107c.jpg)
![单个文件测试结果](https://user-images.githubusercontent.com/48675877/59490629-c7937580-8eb7-11e9-9009-930fb85d7242.jpg)
![Kiviat图](https://user-images.githubusercontent.com/48675877/59490639-ce21ed00-8eb7-11e9-87aa-e06690f69b6e.png)
[glwidget.cpp文件测试结果.txt.zip](https://github.com/hansewu/MovieMator/files/3289470/glwidget.cpp.txt.zip)

### **结果分析：**
Kiviat 图中的绿色环形区域即被测量维度的期望值，维度上的点则是测量得到的实际值。当一个维度上的点位于绿色环形区域中时表明这个维度的测量结果是符合期望的。
从Kiviat图可以看出Max complexity和 Avg Stmts/Method对应的红星或红加超出了绿色区域的范围，


使用教程：https://blog.csdn.net/qq_37372196/article/details/89411366
Kiviat图说明：https://blog.csdn.net/Qidi_Huang/article/details/51027179

**Comment by pisceshsu** [comment]
华为云试用：
1.功能概述：(是收费项目)
代码检查（CodeCheck）是面向软件开发者提供代码质量管理云服务，支持Java、C/C++ 、Android（Gradle）、PHP、C#、JavaScript、Web和CSS等业界主流开发语言，可在线进行多种语言的代码静态检查、代码架构检查、代码安全检查、编码问题检查、质量评分、代码缺陷改进趋势分析，辅助用户管控代码质量。

2.免费试用界面(目前还没有配置成功)
![屏幕快照 2019-06-14 下午5 38 19](https://user-images.githubusercontent.com/6078647/59500086-4e9e1900-8ecb-11e9-8aaa-7521beb3f157.png)

**Comment by pisceshsu** [comment]
自动代码检测工具调研总结：
开源工具
1. 代码规范和其他静态检测， 选用VSCode,  
   1) 安装配置比较简单，适用于windows, mac系统
   2) 可以直接查看报错代码
2.代码重复度检测，选用 Simian
   1) 

3. 复杂度检测，选用SourceMonitor
    https://www.jianshu.com/p/b83c48888af6?utm_source=oschina-app 
    1) 只支持windows系统， 
    2) 图形化报告可以看到哪个指标不好，还可以看到某个类中具体某个函数的圈复杂度信息


收费工具：
1.华为云
2. SonarQube
