### ISSUE TITLE
试用手动代码审核工具 

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#308]
### 需要试用的github结合的code review工具：
1)  Gerrit：Google 开源的 git 代码审查工具；
          https://link.zhihu.com/?target=https%3A//www.gerritcodereview.com/
2)  PullRequest：GitHub pull requests 代码审查辅助工具；
          https://link.zhihu.com/?target=https%3A//www.pullrequest.com/
3)  Pull Reminders：GitHub 上有 PR 需要你审核，该插件自动通过 Slack 提醒你；
          https://link.zhihu.com/?target=https%3A//pullreminders.com/
4)  Reviewable：基于 GitHub pull requests 的代码审查辅助工具；
          https://link.zhihu.com/?target=https%3A//reviewable.io/
5)  Sider：GitHub 自动代码审查辅助工具；
         https://link.zhihu.com/?target=https%3A//sider.review/

**Comment by pisceshsu** [comment]
Github pull request 使用步骤：
参考： https://www.jianshu.com/p/7dae3787de13

1. Fork 原始代码仓库
   进入链接：https://github.com/hansewu/MovieMator ， 点击右上角的 Fork 按钮
  ![屏幕快照 2019-06-13 上午10 03 03](https://user-images.githubusercontent.com/6078647/59398353-8b321d80-8dc2-11e9-8563-8d822085d4e6.png)

2.Fork后，原始代码会出现在自己的github目录下，并在fork后自动跳转

3. clone fork后的代码到本地
    可以直接用命令行svn checkout, 也可以用客户端github desktop
4. 本地修改代码，并提交到fork后的github代码仓库
5. 进入github上fork的代码仓库主页, 提交pull request
    5.1 主页上会看到如下图的信息：
    ![屏幕快照 2019-06-13 上午10 13 27](https://user-images.githubusercontent.com/6078647/59398761-faf4d800-8dc3-11e9-8816-96e352304da6.png)

    5.2 或者直接点击主页上的 “Pull Request”标签页
    ![屏幕快照 2019-06-13 上午10 20 27](https://user-images.githubusercontent.com/6078647/59399024-04cb0b00-8dc5-11e9-8cc2-a3a173af2193.png)

    5.3 点击按钮“New Pull Request”,  填写标题和描述，右上角 "Reviewers"选择审核者，就可以提交了

6.仓库拥有者审核Pull Request, 审核者可以对代码的每一行进行注释注明修改建议，审核介绍后，修改者会收到修改建议，参考如下
    ![Uploading 屏幕快照 2019-06-13 上午9.57.23.png…]()

7.仓库拥有者审核通过后，合并代码

**Comment by pisceshsu** [comment]
总结：
经测试，github pull request基本满足code review的需求，下一步可以尝试使用
