### ISSUE TITLE
github用户提交问题确认并设置优先级

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#309]

**Comment by pisceshsu** [comment]
1. 视频轨道序号错误：
    https://github.com/hansewu/MovieMator/issues/319   

2. 软件包里多了一张sample图片
    https://github.com/hansewu/MovieMator/issues/318

3. 2.5.7 steam音频卡点不方便 
   https://github.com/hansewu/MovieMator/issues/313
