### ISSUE TITLE
2.5.7 苹果商店版在10.14.4上启动失败

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#312]
差不多启动到11%-12%的时候失败，用户等着急用(QQ:179616279)
[[超长消息]Process    .pdf](https://github.com/hansewu/MovieMator/files/3271220/Process.pdf)

**Comment by pisceshsu** [comment]
错误报告
[Uploading [超长消息]Process    .pdf…]()

**Comment by vgawen** [comment]
用户后来反馈又可以启动了。根据崩溃日志判断是m_player初始化没有完成，就触发了MainWindow::resizePlayer()。加了非空判断。
