### ISSUE TITLE
视频滤镜图标个性化

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#315]
一种视频滤镜对应一张图片。

要求： 
1夸张其滤镜效果，使得各种滤镜容易分辨。

**Comment by vvyan** [comment]
[滤镜效果20190612汪艳.zip](https://github.com/hansewu/MovieMator/files/3280382/20190612.zip)
还剩特效2中部分滤镜未做，还有一些滤镜没有效果。


特效2 小块闪现没有效果（只有第一次添加滤镜播放会出现效果，属性调整没用）
特效 锐度和锐化功能一样（锐化比锐度多一个预设)

**Comment by vvyan** [comment]
[滤镜效果20190613汪艳.zip](https://github.com/hansewu/MovieMator/files/3284069/20190613.zip)

特效2未做效果的滤镜
1.蓝屏静态视频背景Blue screen static video backgroun
2.alpha深度 alpha deep
3.延迟   delay
4.alpha通道蒙版 alpha Channel mask
5.预乘或预除  pre x /
6.选择 choose
7.小块闪现（对添加的图片没有作用，对视频有作用） Small flash
8.映射延迟帧（对添加的图片没有作用，对视频有作用）Mapping delay
9.超时指标 Timeout indexTimeout indextim
10.及时冲洗帧 Flush frame in time
