### ISSUE TITLE
2.5.7 steam 软件包里的一张图片不知道有什么用途（QQ 1337507993反馈）

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#318]
Contents/Resources/template/Effects/Sample/1.png
![1](https://user-images.githubusercontent.com/37360104/59239908-c4895280-8c35-11e9-859e-150998d814a6.png)
“一个胡乱做的图片被单独放在一个文件夹里”、“强烈要求下次更新减小文件大小”

**Comment by pisceshsu** [comment]
Windows, Mac都有这个文件，但界面中不会显示

**Comment by vgawen** [comment]
已删除
