### ISSUE TITLE
视频轨道序号错误

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#319]
点击时间线工具栏菜单，先插入轨道，再增加视频轨道，会导致视频轨道序号错误，如图所示：
![图片](https://user-images.githubusercontent.com/44854531/59242202-4335be00-8c3d-11e9-8aca-ad86d39a16f6.png)

**Comment by pisceshsu** [comment]
与 https://github.com/hansewu/MovieMator/issues/180 同类型

**Comment by fuyunhuaxin** [comment]
音频和视频是存放在一个trackList里面的，轨道的数据和轨道显示的UI是通过Qt的model数据模型直接绑定的。对于数据..V3,V2,V1,A1,A2,A3...,对于插入和删除轨道的操作，需要修改的都是比该轨道数字更大的轨道的名称，由于这个model数据模型，他对于界面UI的刷新也是自动的，刚好这个情况下只刷新了前面...V4,V3数字高的视频轨道，而后面的音频轨道数字更高的就没有在UI上面刷新，实际在插入和删除之后，底层的数据是修改好了的，只是UI没有刷新。
上一个音频轨道的bug处理的时候将所有modify的情况都将所有的轨道名称刷新一遍。这样导致了之前能刷成功的视频轨道也变得有问题了，所以此次限定只在音频轨道发生插入和删除的时候刷新轨道名称。这样就没有问题了。

**Comment by hpuzj** [comment]
如果有两个视频轨道，编号为1、2，再新增加一条轨道，轨道编号显示为2、3、3，而不是1、2、3此时音轨显示为1、1，而不是1、2

**Comment by fuyunhuaxin** [comment]
经过程序跟踪，可以完全确定，轨道的底层数据逻辑处理是没问题的，只不过数据在刷新的时候，界面的刷新先于了model底层的刷新，导致model数据准备好了之后，界面已经刷过了。这个问题本身最初只是音频轨道有问题，解决音频轨道问题的时候，由于强行刷新一遍界面数据，导致了视频轨道出了问题，之后代码回滚，重新直接处理音频轨道的问题，添加了一个异步延时刷新。
