### ISSUE TITLE
在中国区导出的视频水印，建议改为 ： 剪大师 及用中文网站 http://jiandashi.com/

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#324]

**Comment by debelliszhu** [comment]
建议导出的水印不要太大，太大的话，视频网站不收录，反而不利于传播。
在中国区也卖的便宜，传播出去，有利于别的看客买

**Comment by pisceshsu** [comment]
建议水印加一个产品的logo, 可参考喵影工程的水印
![屏幕快照 2019-06-14 上午11 47 14](https://user-images.githubusercontent.com/6078647/59482144-3bbf2080-8e9a-11e9-94ee-9d723ffccdaf.png)

**Comment by Dragon-S** [comment]
![1](https://user-images.githubusercontent.com/36149358/59666401-59b4ba00-91e7-11e9-8a51-5fd3b853eab9.PNG)

![2](https://user-images.githubusercontent.com/36149358/59666412-5faa9b00-91e7-11e9-90f8-0e321a530c12.PNG)

**Comment by hpuzj** [comment]
2.6.2 win 7
未注册时的水印问题：
中文状态下，导出应该是剪大师，但中文状态下是水印显示的moviemator
![1](https://user-images.githubusercontent.com/48675877/60337119-bfb5f400-99d4-11e9-9419-86c1ca0ce6e3.png)

**Comment by Dragon-S** [comment]
打包时翻译文件未替换造成
