### ISSUE TITLE
2.5.7 无法启动

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#328]
1. steam上的MovieMator Video Editor Pro无法启动
点击启动无反应，但steam显示程序已经启动，任务管理器显示MovieMator.exe正在运行，但除了内存占用2.4mb，其他都是0，无法显示主界面
![11](https://user-images.githubusercontent.com/37360104/59413764-c8160880-8df2-11e9-8c2e-5c9093aa3d6a.png)
![22](https://user-images.githubusercontent.com/37360104/59413767-c9473580-8df2-11e9-9d6e-3945a1f4039f.png)
![33](https://user-images.githubusercontent.com/37360104/59413768-c9473580-8df2-11e9-8b27-9bf00c296366.png)

显卡是蓝宝石rx580

邀请用户试用了网站版的MM 2.5.7，还是无法启动

6.24邀请用户试用steam版和网站版2.6.1，还是一样无法启动，日志文件也找不到

**Comment by AliciaMoris** [comment]
2. MovieMator Video Editor Pro by effectmatrix I paid for this app and it won’t even open
用户从苹果商店下载的剪大师打不开

**Comment by debelliszhu** [comment]
steam用户：无法启动，点击启动后无反应，系统win10 1903，任务管理器显示MovieMator.exe占CPU 0%，
内存 3.8MB， 磁盘 0MB/秒，网络 0Mbps

**Comment by AliciaMoris** [comment]
3. Your Service MovieMator Video Editor Pro Cant Open,Iam used Macbook Air,
MovieMator Video Editor FREE is Ok and Can Edit, but only 5 Minutes
之前用的免费版能打开，后升级pro打不开了；推荐其使用网站版，同样取法启动

**Comment by debelliszhu** [comment]
![QQ20190614-0](https://user-images.githubusercontent.com/37359992/59474858-14a52680-8e7b-11e9-855f-061f37ac4496.jpg)

**Comment by debelliszhu** [comment]
6.15日，发2.6.1 Mac版本给用户，系统10.14.5，用户反馈：可以打开了.
