### ISSUE TITLE
音频轨道连续插入然后连续删除，然后连续多个undo和redo就会崩溃

### ISSUE THREAD

**Issue by fuyunhuaxin** [hansewu/MovieMator#329]
1 连续插入5个音频轨道
2 连续删除5个音频轨道
3 再连续插入5个音频轨道
4 连续undo直到刚才新增的5个轨道都删掉
5连续redo将5个轨道加回来，这个过程中会崩溃。

**Comment by fuyunhuaxin** [comment]
简化版：
1 选择A2
2 插入轨道
3 选择A3
4 插入轨道
5 undo点击4次
6 redo即崩溃
debug之后发现是
void MainWindow::on_actionRedo_triggered()
{
    m_undoStack->redo();
}
这句代码卡死了，执行不了。
c++里面调用undo的时候触发qml：
// 当前轨道发生变化时响应的函数
    onCurrentTrackChanged: {
        console.assert(timeline);
        if(timeline)
            timeline.selection = []
    }
而qml并不知道是否为undo操作
然后又触发c++里面的undo的push。
进入死循环。

**Comment by fuyunhuaxin** [comment]
这个问题和之前sll发现的undo、redo问题本质上一样的，改动的话涉及轨道的setSelection函数，强行改的话容易引发别的问题，因小失大。所以只能放到以后再处理了

**Comment by vgawen** [comment]
主要跟踪设置选中函数TimelineDock的setSelection
一
只要工程有改动，发送modified消息，就会调用 clearSelectionIfInvalid。一般不会有问题。

二 添加轨道
1 modified
调用clearSelectionIfInvalid  setSelection
2 setCurrentTrack 
（1） 时间线显示
（2） 调回setSelection 把当前选择清空

三
timeline的currentTrack和选中没有关系。currentTrack只是标识当前track，显示不通的颜色，另外点击append和insert按钮的时候，往哪个轨道添加。
timeline的currentTrack变化后，会调用setSelection清空选择。

四
点击Clip，（1）如果currentTrack有变化，调用setSelection清空选择（2）调用setSelection选中点击的Clip

五
点击trackHead，（1）currentIndex有变化，调用setSelection清空选择（2）调用selectTrackHead 选中点击的轨道。
（1）-》（2）-》点击undo，因为清空了再选择的，undo也会清空选择。但是时间线上没有变化。再次undo恢复到之前的选中状态，时间线还是无变化。


问题
1 轨道头的选中恢复回来，界面不会刷新
2  选中一个轨道上的clip，然后点击其他的trackHead，然后undo两次，然后点击时间线上的删除按钮，触发assert。选中也没恢复回来。
3 一次点击有多个SelectCommand
4 其他操作也会引入选中Command，导致一次操作有多次Undo。
主要问题是更改选中状态的地方太多，调用流程很难不清楚。setSelection又区分是否是从Undo、redo的过程中调用的。整个逻辑太复杂。

**Comment by vgawen** [comment]
去掉了ClipsSelectCommand的使用，把选中状态保存到MultitrackModel里面。UndoCommands保存操作前后的选中状态，用以恢复选中状态。
