### ISSUE TITLE
“Insert”按钮插入的不是选中图片

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#33]
问题描述：
点insert插入图片到时间线，选中的是一张图片，实际导入的是另一张图片
（xyy已证实，如果3张图片拖入的顺序是231，第四次按insert就会出错）

来源：
App Store

版本：
Mac MovieMator Pro 2.5.4
iMac 10.14.4

**Comment by WanYuanCN** [comment]
插入/追加的资源：
xmlToUse = !xml.isEmpty()? xml : MLT.XML(MLT.isClip()? nullptr : MLT.savedProducer());
而粘贴资源的主要功能也是插入，主要问题在于MLT.savedProducer()，它保存了播放和复制时的producer，所以播放的会覆盖复制的内容，粘贴就会出问题，而拖动时选中文件并没有播放这个文件，因此MLT.savedProducer()的文件依然是之前播放过的文件，所以就会造成选中却没有插入到时间线的问题。
将savedProducer按功能拆分成3个变量：
播放：savedProducer，关联太多，保持不变
选中：selectedProducer，仅recentdock/effectdock的append/insert使用
复制：copiedProducer，仅timelinedock的copy使用
