### ISSUE TITLE
左上资源框点击音频滤镜， 自动播放两次音效，一种原声，一种处理后的声音

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#333]
左上资源框点击音频滤镜， 自动播放两次音效，一种原声，一种处理后的声音

**Comment by fuyunhuaxin** [comment]
预览功能都加上了，部分滤镜本身加了也没效果，或者需要特殊音频文件特殊的参数配置才会出效果的，可以后面对不同的滤镜配置不同的参数即可。
