### ISSUE TITLE
右上角属性框界面优化

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#336]
右上角属性框：

18 右上角属性框将开始时间点和结束时间点，因为不能修改，采用一般文本显示。

19 右上角属性框将开始时间点和结束时间点，调整到“速度”选项上面。

20 右上角属性框“速度”选项需要强调，将其和开始时间点和技术时间分隔开。另外增加ICON示明“速度”的含义。

21 应用按钮用图形化强调，修改速度后，需要闪烁，避免没有应用。

参考：
https://github.com/hansewu/MovieMator/issues/187

**Comment by WanYuanCN** [comment]
需要速度的 ICON 素材
