### ISSUE TITLE
undo/redo 单元测试验证undo/redo问题

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#338]
编写undo/redo 单元测试验证模块验证undo/redo问题解决

1 保存各个阶段MLT XML， 验证UNDO/REDO 各个状态是否和保存的相等
2 将各个阶段XML 保存到日志文件，方便研究分析
3 模拟复杂各种操作UNDO和REDO

**Comment by fuyunhuaxin** [comment]
添加了xml保存到日志文件的功能，对于每个undo命令都会保存一个文件夹，里面包含原来的状态和新状态两个xml文件。

**Comment by fuyunhuaxin** [comment]
分析xml日志文件，遇到几个瓶颈问题：
1 有些状态不一样的，造成的情况本身不好解决。
2 一旦出现了不一样的情况，后面的xml日志文件，受这个情况的影响，往往都会不一样。

**Comment by fuyunhuaxin** [comment]
编写undo/redo单元测试。程序启动之后，触发对所有command命令依次进行单元测试，测试的结果和之前一样保存在log文件夹中。总共有30多个command命令，现在单元测试已经添加了10多个进去，每个单元测试都是通过debug跟代码，找到相应的参数设置进去，是写死的。遇到一个特殊的command：
FilterAttachCommand：程序中的注释写了 //第一次自动执行不调用，外部已经执行。导致不好进行单元测试。

**Comment by fuyunhuaxin** [comment]
已经把单元测试都添加好了，其中滤镜操作相关的有m_bFirstexec第一次不调用的 几个command，将构造函数里面添加了bool isFirst参数来初始化。
滤镜添加command会发送一个信号，该信号在所有单元测试做完了之后会执行到一个ASSERT地方崩溃掉。这是添加滤镜command的一个问题，可以和将来解决其他redo前后不一样的问题一起处理。
