### ISSUE TITLE
2.5.7 QQ(2772145513) 游标无法移动

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#344]
Win 10, 之前都能移动的,今天刚打开想用一下发现针拖动不了。

我看用户发的录屏里 是mp3的一个音频 上有标没法动

**Comment by debelliszhu** [comment]
steam用户（龙晨魄）留的评论：我真是气炸了，没更新之前视频剪辑时间轴随便移动，方便定位，更新之后这功能用不了了，心里超级堵，别人更新是为了方便，这里更新是为了添堵

**Comment by hpuzj** [comment]
2.6.1 测试版本复现问题;
### **复现步骤：**
1.添加1段clip到轨道上，
2.再添加一个贴图，拉伸贴图长度（或者添加一段clip，切分clip后，再把clip拉长）
3.再行轨道上拖动两段clip，clip之间保持空隙，游标无法移动到最后一段clip上
4.此时必须重启程序，否则即使删除clip，再添加新的clip（比上述步骤中的视频要长），clip播放到中间某个位置就不再播放了
5.但是重启后，会有下面的问题：

两段clip之间有空隙，可以播放到第二段clip播放结束（共计26s），但是播放器对应的时长是(10m25s)

**Comment by Dragon-S** [comment]
1、用户反馈的问题：主要原因应该是打开的工程中含有不能seek的文件造成的，目前使用flv进行复现的。含有flv视频的工程文件flv对应的producer的seekable属性是false，因此不能seek。但实际的flv视频时可以seek的，在程序中对是否能seek的判断中，除了对producer进行判断意外还对mlt_type和service进行了检测，设置seekable。打开的工程文件是service是xml，因此目前临时先添加xml检测项。还有另一种方法就是提示转换，目前软件没有转换功能，可能不是太友好。讨论暂且先加入xml判断，后期在继续优化。
此问题最好和用户确认一下，以及把用户的资源收集到，验证确认一下问题

2、测试反馈的不能seek问题：主要是cx修改的modify造成的，目前已经有gdb处理（暂且恢复代码）
