### ISSUE TITLE
2.6.1 把游标放在时间线两段clip的空隙处，播放器显示为紫色竖条纹状，有时是白色

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#346]
![clip间空隙预览图片](https://user-images.githubusercontent.com/6078647/59549049-5bce0d00-8f8a-11e9-80dc-ce45416e1162.png)

**Comment by vgawen** [comment]
multitrackmodel modified消息加了个bool参数，但是连接的地方没有修改，引起消息不能响应引起的问题。已恢复。
