### ISSUE TITLE
2.6.1 clip切分后删除后面一段，播放器显示总工程时间不变

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#349]
较长一点clip，切分后只保留最前面一部分，但是播放器时间显示的还是最开始的时长，预览时，切分后面的部分，播放器显示紫色竖条纹。

**Comment by vgawen** [comment]
multitrackmodel modified消息加了个bool参数，但是连接的地方没有修改，引起消息不能响应引起的问题。已恢复。
