### ISSUE TITLE
2.6.1 导出时键盘输入数字修改分辨率达不到预期效果

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#351]
键盘输入数字修改分辨率，想把分辨率设置成580x360, 360这个值，输入比较麻烦，只能从48开始，点击向上箭头，直到加到360为止

**Comment by Dragon-S** [comment]
由于现在对输出分辨率数字的判断是在修改每个字符是进行的，因此会造成问题（比如想输入128就输入不了，因为在输入1的时候就被自动改成4了）。
现在修改为在输入完成后在做判断
