### ISSUE TITLE
2.6.1 新建工程文件，只有当轨道上的clip添加过滤镜后，才会提示保存工程；没有加滤镜时，工程丢失

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#356]
轨道上的clip，只要不添加滤镜，哪怕进行了切分、删除、添加转场、修改速度等很多操作，点击「新建工程」，会直接覆盖之前的操作，不提示保存工程文件。

**Comment by vgawen** [comment]
multitrackmodel modified消息加了个bool参数，但是连接的地方没有修改，引起消息不能响应引起的问题。已恢复。
