### ISSUE TITLE
去掉m_keyFrameList  后发现QML相关代码有隐藏的BUG

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#361]
去掉m_keyFrameList  后发现QML相关代码有隐藏的BUG
WYL:
“以前经常遇到关键帧跟踪数据会有时跟踪不到，我一直怀疑这个还有线程的问题，但是当时也没有线程，现在想想其实这个现有界面使用的机制就是有问题的，因为底层动画数据大部分时候都是失效了的，都是错误的”

**Comment by wyl1987527** [comment]
主要的隐藏bug：
filter set 和filter setKey 混用造成的
fiter get 和filter getanim混用造成的
