### ISSUE TITLE
解决少部分滤镜预览有问题或者没效果 的问题

### ISSUE THREAD

**Issue by fuyunhuaxin** [hansewu/MovieMator#362]

**Comment by fuyunhuaxin** [comment]
所有老滤镜能调参数的都调出效果了，frei0r有些默认值本身就没有效果，这小部分只有看需要特殊重点处理了，现在唯一一个是3d文字滤镜效果刷不出来。

**Comment by fuyunhuaxin** [comment]
3d文字和动态文字两个滤镜比较特殊，所以新添加了两个.mlt配置文件。两个滤镜的预览效果就能出来了。
新加了一个功能，当视频预览的时候，先搜索文件夹下没有用该滤镜名对应的专用配置文件，有的话就用该配置文件，没有的话就用通用的配置文件。

**Comment by hpuzj** [comment]
滤镜预览：
 1）滤镜预览肯定是看的动态效果，而不是默认效果，如果预览看默认效果就达不到预览的目的
    绝大多数滤镜预览都是没有效果的，之前有动态效果的例如波形，现在也没效果了
  透视变换、翻转、变换、旋转、裁剪、视频淡入、视频淡出、防抖动
  3D文字预览，去掉“？？”
  亮度、色调偏移、透明度、白平衡
  3D降噪、方形模糊、预乘或预除、选择
  超时指标、rgb拆分 等等
 2）滤镜预览选择的图片不合适，应该与滤镜贴图保持一致
 3）滤镜预览选择的图片最好满屏显示，不要留下左右两个黑边，滤镜预览时是应用于整个播放器，部分滤镜预览时，图片是一个效果，两边和黑边又是另外一种效果。
