### ISSUE TITLE
实现文字出点动画，确保拉伸CLIP时，能尾巴关键帧能自动跟踪

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#367]
实现文字出点动画，确保拉伸CLIP时，尾巴关键帧能自动跟踪CLIP尾部

尽量采用MLT 时间为负数的方式实现

**Comment by hansewu** [comment]
有两个问题：
1 关键帧动态更新
尾巴关键帧自动，理论可以采用引擎内时码为负数完成。然后 负帧数+动画长度 得到正数关键帧
问题在于
一   -0 表示正好有问题，使得结果不知道是否要相加。 解决方法：用-1 表示最大负数，所有负数时间再减一，用的时候再矫正回来。

二 动画长度问题。 
因为只有有动画长度才能把负数+动画长度进行转化。
但大部分时候FILTER 都没有设置明确的长度，所以需要进行补足。

方案上动画长度尽量使用PRODUCER的长度，但是PRODUCER的长度，在试验中经常得到的不是裁减过的。这方面需要继续验证。


2 关键帧动态更新的显示
这个还不确定，这版本之前关键帧是有缓冲区，是不可能动态刷新的。

**Comment by hansewu** [comment]
```
int get_length_for_filter(mlt_properties self, int length)
{
//	return length;
//	比较难获得filter对应的producer
	if(length > 0)  return length;

	char *mlt_type = mlt_properties_get( self, "mlt_type" );
	if ( strcmp( mlt_type, "filter" ) != 0)
		return length;

	mlt_service producer_service = (mlt_service)mlt_properties_get_data( self, "service", NULL );
	if(!producer_service)  return length;

	mlt_properties producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
	if(!producer_properties) return length;

	char *filter_name = mlt_properties_get( self, "mlt_service" );

	if(strcmp(filter_name, "dynamictext")==0)
	{
		mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter length = %d\n", length);
	}
	else return length;  
 /* 
	if(mlt_properties_get_int( producer_properties , "_cut" ))
	{
        mlt_producer parent =  (mlt_producer)mlt_properties_get_data( producer_properties, "_cut_child", NULL);//"_cut_parent", NULL );
		if(parent)
		{
			producer_service = MLT_PRODUCER_SERVICE(parent);
			producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
		}
	}
*/	
	mlt_position pos_in 	= mlt_properties_get_position( producer_properties, "in" );
	mlt_position pos_out 	= mlt_properties_get_position( producer_properties, "out" );

	if(strcmp(filter_name, "dynamictext")==0)
	{
		mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter length = %d\n", pos_out - pos_in +1);
	}  

	if(pos_out > 0)
	{
		if(strcmp(filter_name, "dynamictext")==0)
		{
			mlt_properties_set_position( self, "in", pos_in );
			mlt_properties_set_position( self, "out", pos_out );
		}
		return pos_out - pos_in +1;
	} 
	return length;
	
}
```

**Comment by hansewu** [comment]
测试的问题是PRODUCER得到的长度和工程保存的入店出点不一致，变短了，不能实时更新。一直为一固定数据。

**Comment by hansewu** [comment]
建立了一套新机制解决此问题：

一 动画模板添加新的标志，标识时码的含义

过去时码只是表示CLIP PRODUCER的时码，和文件剪辑的入点时间和出点时间无关。
如： trans_fix_rotate_x=00:00:01.000=180
若对应的是 1.mp4 的滤镜参数， 表示的是这个文件在00:00:01.000的滤镜参数时码。即使这个文件编辑裁剪后头几秒裁掉，仍然如此。

为了让滤镜跟随裁剪头部或者尾部移动分别，在滤镜前面添加了h 和 t
如： trans_fix_rotate_x=h00:00:01.000=180
表示这个滤镜对应PRODUCER入点的1秒后的值。

trans_fix_rotate_x=t00:00:01.000=180
表示这个滤镜对应PRODUCER离出点还有1秒时的值。

二 添加了一些函数，直接支持设置时码位置信息
如：
int mlt_property_anim_set_int_pos_type( mlt_property self, int value, double fps, locale_t locale,
	int position, int length, mlt_keyframe_type keyframe_type , int frame_in, mlt_keyframe_pos_type keyframe_pos_type );
对应原先的
int mlt_property_anim_set_int( mlt_property self, int value, double fps, locale_t locale,
	int position, int length, mlt_keyframe_type keyframe_type );

增加了producer入点时间, int frame_in, 和时码类型 mlt_keyframe_pos_type keyframe_pos_type。

其中mlt_keyframe_pos_type 意义如下：
typedef enum {
	mlt_keyframe_pos_producer = 0, /**和PRODUCER 对应的时间 */
	mlt_keyframe_pos_from_head,       /** 和PRODUCER ENTRY in 相差的时间*/
	mlt_keyframe_pos_from_tail,        /**和PRODUCER ENTRY out 相差的时间 */
	mlt_keyframe_pos_auto_head_tail,   /*临时状态，根据位置自动判断使用mlt_keyframe_pos_from_head 或者 mlt_keyframe_pos_from_tail*/
}mlt_keyframe_pos_type;

**Comment by hpuzj** [comment]
“尾巴关键帧能自动跟踪”未见该效果

**Comment by hpuzj** [comment]
2.6.2测试，文字滤镜position animation,无出点动画模板，测试时只有Windows版本，没有Mac版本
![7](https://user-images.githubusercontent.com/48675877/60717561-bab4ef80-9f54-11e9-9aa2-f1920538d594.png)
![8](https://user-images.githubusercontent.com/48675877/60717573-bf79a380-9f54-11e9-909d-cf5365bf95c3.png)

**Comment by hansewu** [comment]
好，截屏一看就知道原因了。
