### ISSUE TITLE
2.6.1 在OS10.10.4上 无法导入音视频和预览

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#370]
打开软件，预览区域是一块绿屏，在桌面上拖动窗口还忽闪忽闪的；
预览图片也是花屏；
导入视频和音频没有反应，媒体库——分类里只有images，其它都没有
![Screen Shot 2019-06-17 at 11 23 09 AM](https://user-images.githubusercontent.com/37360104/59576524-bf734a00-90f2-11e9-8cba-1bb56f648850.png)

**Comment by vgawen** [comment]
Duplicate of #274
