### ISSUE TITLE
2.6.1 网吧测试 文字滤镜 clip切分后，除了首段，其余片段，增加position animation,不显示关键帧标识(或只显示1个)，无动画效果

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#376]
![61560762881_ pic_hd](https://user-images.githubusercontent.com/48675877/59599229-9c678b00-9130-11e9-9b3c-3fb8e44ee8b1.jpg)
2.6.1 网站版

**Comment by hansewu** [comment]
在MLT filter LOAD PROPERTIES 时， 自动根据FILTER对应的PRODUCER ENTRY FRAME IN/OUT， 重新设置关键帧的时间。

测试发现，重新对文件设置FRAME IN/OUT后，关键帧又不对了，需要有其他动画机制进行保证。
