### ISSUE TITLE
2.6.1 网吧测试  撤销有崩溃现象

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#377]
2.6.1 网站版
复现步骤：
1.clip1切分后，删除后面片段并关闭缝隙，后面衔接的是其他clip ，
2. 向后拖动 clip1 剩余部分的 “] ”，会和后面的clip形成转场，
3. 然后删除转场，继续向下操作（例如插入片段，或其他clip增加旋滤镜等等），
4. 撤销的时候，撤销到刚才的转场部分程序就会崩溃（撤销不用太快）

**Comment by pisceshsu** [comment]
2.6.4版本未复现，先关闭
