### ISSUE TITLE
调研覆盖率检测工具

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#379]
### 要求：
1.支持C/C++检测；
2. 可以检测到dylib或lib文件中的代码
3. 最好能集成到Qt Creator

**Comment by pisceshsu** [comment]
### Github开源工具：
1.OpenCppCoverage  276star
 https://github.com/OpenCppCoverage/OpenCppCoverage  

Features:
	•	Visual Studio support: Support compiler with program database file (.pdb).
	•	Non intrusive: Just run your program with OpenCppCoverage, no need to recompile your application.
	•	HTML reporting
	•	Line coverage.
	•	Run as Visual Studio Plugin: See here for more information.
	•	Jenkins support: See here for more information.
	•	Support optimized build.
	•	Exclude a line based on a regular expression.
	•	Child processes coverage.
	•	Coverage aggregation: Run several code co

Requirements
	•	Windows Vista or higher.
	•	Microsoft Visual Studio 2008 or higher all editions including Express edition. It should also work with previous version of Visual Studio.

FAQ:  https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ


2.Oovaide   137star
https://github.com/animatedb/oovaide
C++ and Java automated analysis, class, component and sequence UML diagramming IDE tool, test coverage, complexity, duplicate code, analysis statistics 

官网： http://oovaide.sourceforge.net/ 

支持系统： Windows， Linux

**Comment by hpuzj** [comment]
### **COVTOOL**
COVTOOL is an open source test coverage analyzer for C++ programs. It lets you dynamically instrument your source code as you compile. An instrumented program keeps track of the lines of code that were executed during its run and produces a log of the same upon program termination. Multiple program runs will produce multiple logs. 

网址：http://covtool.sourceforge.net/
支持系统：Linux(需进一步验证是否可以在Mac上使用)
