### ISSUE TITLE
试用覆盖率检测工具

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#380]

**Comment by hpuzj** [comment]
### **gcov试用：**

1. 编译mlt
mlt根目录下的config.mak 文件中添加

CXXFLAGS += -fprofile-arcs -ftest-coverage 
CFLAGS+= -fprofile-arcs -ftest-coverage 
LDFLAGS+= -fprofile-arcs -ftest-coverage

2. 运行moviemator
src.pro 中添加：

QMAKE_CXXFLAGS += -fprofile-arcs -ftest-coverage -o
QMAKE_CFLAGS+= -fprofile-arcs -ftest-coverage -o
QMAKE_LFLAGS+= -fprofile-arcs -ftest-coverage -o

构建环境中添加
LIBS = -lgcov

3. 构建moviemator
编译的时候会在生成*.gcno文件,那么在执行程序时会生成*.gcda文件，这两个文件必须在同一个文件夹内

4. 终端运行
1）/usr/bin/gcov  /Users/apple/Downloads/MovieMator-github/MovieMator/src/MovieMator/src/abstractproducerwidget.cpp

会生成：abstractproducerwidget.h.gcov

2）vim abstractproducerwidget.h.gcov可查看函数调用情况
![屏幕快照 2019-06-19 下午4 54 37](https://user-images.githubusercontent.com/48675877/59751709-9b129b80-92b3-11e9-8425-66456c526665.png)
其中带#####符号的是未调用到的行
3）使用lcov可生成html 文件，因遇到下面问题未解决，无法继续
![屏幕快照 2019-06-19 下午5 01 26](https://user-images.githubusercontent.com/48675877/59751901-ed53bc80-92b3-11e9-8d62-14dc9b66384a.png)

**Comment by hpuzj** [comment]
gcov+lcov试用情况：
1. mlt编译（此处不做详细说明，同上）
2.编译moviemator

1）除了在src.pro中添加参数之外，还要在AudioFilterDock.pro、Breakpad.pro、CommonUilt.pro等所有的.pro文件中添加一下参数
QMAKE_CXXFLAGS += -fprofile-arcs -ftest-coverage -o
QMAKE_CFLAGS+= -fprofile-arcs -ftest-coverage -o
QMAKE_LFLAGS+= -fprofile-arcs -ftest-coverage -o
注：在Breakpad.pro文件中添加参数报错：
![屏幕快照 2019-06-20 下午2 21 06](https://user-images.githubusercontent.com/48675877/59825518-cefac900-9366-11e9-8f30-cb709b1a4b8d.png)

2）构建环境中添加：LIBS = -lgcov

3.重新构建moviemator，构建完成后，运行程序，进行测试操作；关闭程序时，会在底层mlt以及moviemator中生成.gcda文件，.gcon文件是编译时生成的文件

4.  终端命令生成覆盖率
1）cd  ../MovieMator-github/MovieMator/src
2)  /usr/local/Cellar/lcov/1.14/bin/lcov --directory . --capture --output-file test.info
   注：如果未安装lcov,应该先brew install lcov
会在src目录下生成test.info文件，该文件包含覆盖率信息
3）获取 HTML 输出
  /usr/local/Cellar/lcov/1.14/bin/genhtml -o  results  test.info
 生成results 文件夹
4）浏览器打开index.html ,查看覆盖率信息
![屏幕快照 2019-06-20 下午2 33 28](https://user-images.githubusercontent.com/48675877/59826277-96f48580-9368-11e9-9f23-60e5c55e533a.png)
![屏幕快照 2019-06-20 下午2 36 36](https://user-images.githubusercontent.com/48675877/59826437-e33fc580-9368-11e9-878c-dbec7852c0fe.png)
5)单击，查看代码覆盖率信息包含的文件，此处以 MovieMator/QmlUtilities 为例：
![屏幕快照 2019-06-20 下午2 38 15](https://user-images.githubusercontent.com/48675877/59826547-197d4500-9369-11e9-880d-ac9af2bc43bf.png)
6.单击查看代码调用情况：../MovieMator/QmlUtilities - qmlmetadata.cpp,红色部分未是未调用（测试未覆盖）到的代码
![屏幕快照 2019-06-20 下午2 45 35](https://user-images.githubusercontent.com/48675877/59827045-3ebe8300-936a-11e9-9fce-acc5d16557d0.png)
5.查看mlt 代码覆盖率
1）cd  ../mlt
2)  重复4中的操作即可,目前可覆盖到 framework、mlt++、modules、System，还有usr中的include部分内容、Cellar中的ffmpeg等
![屏幕快照 2019-06-20 下午2 53 32](https://user-images.githubusercontent.com/48675877/59827409-33b82280-936b-11e9-9070-6f4515e1ad93.png)

**Comment by pisceshsu** [comment]
gcov, lcov，目前满足覆盖率的测试需求
