### ISSUE TITLE
音频轨道增加波形图

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#386]

**Comment by Dragon-S** [comment]
实现效果如下：
![捕获](https://user-images.githubusercontent.com/36149358/64165522-d9156980-ce77-11e9-8cff-a0f1a4281b85.PNG)

目前存在问题：
（1）比较长的视频音频波形显示较慢（1小时左右的视频，波形是逐步显示完的）

**Comment by hpuzj** [comment]
9.06日跟测结果：
clip长度大于2分钟左右的时候，鼠标放大clip的显示长度，后半部分不显示波形图 #783
