### ISSUE TITLE
MOVIEMATOR 视频输出可靠性测试方案

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#387]
MOVIEMATOR 视频输出可靠性测试方案

注意：

1 重点测试各种复杂工程输入后的视频转换输出，测试各种输出格式并非重点（不同格式输出覆盖的代码都在FFMPEG）

2 使用GOOGLE各种侦测工具

**Comment by hansewu** [comment]
MOVIEMATOR 视频输出可靠性， 用户还经常说有问题。 应该跟工程有关系，可能有些工程在MOVIEMATOR能解析，在QMELT不能解析。这个要仔细测试一下。就像上次的文本阴影特效，MOVIEMATOR没问题， QMELT 就有问题。高东彪, 8:49 AM嗯嗯 Xu, 8:49 AM嗯需要把输出的问题整理一下，再看看怎么展开测试8:50 AM这个另外之所以容易有问题，是因为MOVIEMATOR里面有很多自定义属性等存储到工程后，这些自定义属性都丢失了Xu, 8:52 AM哦，自定义的属性，是指producer, consumer的属性吗？ 8:52 AM另外，我昨天也遇到，存储工程的确还是容易有点问题的，存储的有问题，打开，转换就都容易出错。很多临时中间属性 moviemator::... 的这种Xu, 8:53 AM嗯，好8:54 AM输出不要去重点测试各种输出高东彪, 8:54 AM嗯 这种在qmelt里面就不起作用8:54 AM格式 重点测试各种复杂工程输入后的视频转换输出，测试各种输出格式并非重点（不同格式输出覆盖的代码都在FFMPEG）测试用例主要要放在各种工程的制作上面各种格式一个个测试太多没有意义那个输入弄对了，结果都是进入FFMPEG 的格式问题重点都是输入输出问题，本质也是输入问题造成的工程错了，就会出错Xu, 8:57 AM“重点测试各种复杂工程输入后的视频转换输出” --》视频转换输出，这个还不是很明白8:58 AM复杂工程就是制作很多多轨道，多滤镜，多TRANSITION， 中间多UNDO/REDO 的，时间长的工程。各种滤镜， 各种裁剪，复制，粘贴等等都用上Xu, 8:59 AM嗯高东彪, 8:59 AM嗯 Xu, 9:00 AM视频转换输出 --》这个呢？ 是输出不同的格式？9:00 AM视频输出就是视频转换说的时同一个东西Xu, 9:01 AM嗯嗯，

**Comment by pisceshsu** [comment]
### 1 测试目标

1.1 保证复杂工程预览和输出的一致性
测试输出视频与工程预览不一致的情况，比如，音视频不同步，部分属性丢失，部分资源预览显示白屏或黑屏、工程文件打开崩溃及其他错误等等

1.2 测试可靠性、易用性方面的缺陷
      1) 界面视觉设计上的缺陷，
         主要包括：界面控件大小，对齐，布局，颜色搭配是否合理
      2) 令人困惑的用户体验
         主要包括：功能引导是否合理，操作是否有歧义，功能操作流程是否易于理解
      3) 功能bug
         主要包括：各个功能是否正确实现
1.3 测试线程、指针、内存安全隐患
     用Google Thread/Address/Leak Sanitizer工具测试moviemator/mlt/qmelt模块，并整理测试报告

1.4 测试重复代码
     用重复代码检测工具Simian检测重复代码，并整理测试报告

1.5 检测圈复杂度高的函数
     用SourceMerge工具检测函数复杂度，并整理出复杂度高的函数，便于开发有针对性的修改复杂度高的函数

### 2 测试流程
      
2.1制作复杂工程
2.1.1要求
1) 制作的工程需要贴合用户真实使用场景，比如，
   -- 为视频添加字幕，
   -- 从拍摄的视频中切分需要的镜头
   -- 制作照片slideshow+各种转场
   -- 制作课程演示视频

2) 需包括基本的操作流程：
    导入，剪切(时间线各种操作)，调色，转场，调速，字幕，功能滤镜(裁减/改变大小/旋转/防抖动)，关键帧动画，导出。

2.2.2 具体操作步骤(见pdf文档)

2.2 编辑用户工程
根据用户提供的工程文件，进行如下操作：
1.打开工程文件，不替换文件直接点击ok
2.Windows系统的工程在Mac系统打开（反之亦然）
3.替换用户工程文件的内容
  1）替换用户提供的视频、音频或图片
  2）替换其他的视频、音频或图片
4.将用户的工程导出为不同格式的视频，查看输出与工程预览是否一致

2.3 使用google thread/address/leak sanitizer 测试代码的可靠性
2.4 用重复代码检测工具Simian检测重复代码
2.5 用SourceMerge工具检测函数复杂度
