### ISSUE TITLE
Semantic Issue - warning: padding size of 'Application' with 7 bytes to alignment boundary

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#390]
Semantic Issue - warning: padding size of 'Application' with 7 bytes to alignment boundary
main.cpp中的警告
class Application : public QApplication
{
public:
    MainWindow* mainWindow;
    QTranslator qtTranslator;
    QTranslator qtBaseTranslator;
    QTranslator shotcutTranslator;
    QString resourceArg;
    bool isFullScreen;
...
}

**Comment by Dragon-S** [comment]
类似问题：
C:\Projects\moviemator-github-sourcecode\src\MovieMator\MltController\sharedframe.cpp:27: warning: padding class 'FrameData' with 4 bytes to align 'f'

**Comment by Dragon-S** [comment]
字节对齐三规则：
其实字节对齐的细节和具体编译器实现相关，但一般而言，满足三个准则： 
1) 结构体变量的首地址能够被其最宽基本类型成员的大小所整除； 
2) 结构体每个成员相对于结构体首地址的偏移量都是成员大小的整数倍，如有需要编译器会在成员之间加上填充字节；例如上面第二个结构体变量的地址空间。 
3) 结构体的总大小为结构体最宽基本类型成员大小的整数倍，如有需要编译器会在最末一个成员之后加上填充字节。

https://blog.csdn.net/gaoyi221119/article/details/77989522
https://www.jianshu.com/p/d994731f658d
https://blog.csdn.net/magiclyj/article/details/72922150

一般消除警告的方法是，手动填充或者使用个#pragma pack()

**Comment by Dragon-S** [comment]
https://evpo.wordpress.com/2014/01/25/memory-alignment-of-structures-and-classes-in-c-2/
https://www.cs.uaf.edu/2009/fall/cs301/lecture/10_30_structs.html
https://www.geeksforgeeks.org/structure-member-alignment-padding-and-data-packing/
https://www.cs.uaf.edu/2009/fall/cs301/lecture/10_30_structs.html
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4820?view=vs-2019
https://forum.qt.io/topic/79485/alignment-boundary-issue/2
https://stackoverflow.com/questions/20184259/what-does-the-padding-class-tester-with-4-bytes-warning-mean
https://lists.qt-project.org/pipermail/qt-creator/2016-March/005505.html
