### ISSUE TITLE
预览滤镜后，再添加滤镜，右上角滤镜列表只会选中第一个滤镜

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#396]

**Comment by WanYuanCN** [comment]
目前的处理方案是在multitrackmodel中添加要给成员变量m_selectedProducer，用来保存当前时间线上被选中的clip，只在预览后添加滤镜使用，没有其他任何用途，在mainwindow中调用m_timelineDock->emitSelectedFromSelection()前判断m_selectedProducer跟时间线上选中的是否一致，若一致则不调用m_timelineDock->emitSelectedFromSelection()。也就是屏蔽掉刷新滤镜列表的功能。
