### ISSUE TITLE
MovieMator易用性Bugs与建议

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#423]
易用性测试：
1.新用户能否在5分钟之内导出一个短视频，掌握软件的基本用法；
2.和movavi, flomora相比，同一段视频，哪个软件用最短的时间做出来，并思考后面的原因

**Comment by hpuzj** [comment]
建议：
1.像素化滤镜：添加参数可以给视频中的某个部位进行像素化（马赛克）
2.建议视频轨道宽度可以进行调节
3.资源库『文件』为空时，建议在「文件」界面添加一个代表文件的图标（如果从来没使用过任何视频编辑软件的人，都不知道文件添加到哪）
4.资源库视频预览时，鼠标点击进度条快进，视频不自动播放，需要点击「开始播放」才能继续播放，建议此时改为自动播放
5.添加文件到资源库，建议不要自动预览

**Comment by pisceshsu** [comment]
1. 导入资源和工程设置(基于2.6.1)
   1) 各种资源操作方式的一致性，这样用户更容易理解，比如，都可以通过拖放添加到时间线。
       目前添加滤镜到时间线是通过双击或点击右上角的+号，和文件、贴图的操作不一致。这样用户在添加文件和滤镜操作中切换时，容易有一种乱的感觉。

   2) 视频滤镜的预览，如果能直接作用在当前帧会更好
       -- 目前的滤镜预览方式是对比示例图片的前后效果，这种预览方式存在一个问题：由于图片背景和颜色的差异，示例图片上选好的滤镜，添加到clip后，整体搭配效果可能和预览效果不一致。
       -- 改成作用于当前帧：用户通过切换滤镜可以很直观的知道自己要哪个，不需要示例图片的过渡；


  3) 工程设置信息(分辨率，宽高比，帧率等等)最好在一开始就让用户知道或设置
       -- 目前的工程设置默认是 1280x720，是在菜单“视频模式中”，比较隐蔽, 表述也偏专业。而且现在比较常用的分辨率应该是1920x1080；
       -- 用户在编辑之前，一般都会知道视频将会如何传播出去，是上传到视频网站，还是输出到某种设备。也就知道相关网站或设备对视频的格式要求。提前让用户设置工程参数，可以避免最后导出时才发现参数不对，返回去修改。MovieMator修改模式后，还需要重新启动程序，比较麻烦；

  4) 资源预览时的属性参数应该是不修改的状态；或者就设计成对资源预编辑的窗口，比如切分镜头，“属性”名字也要改一下
      -- 文件(视频/音频/图片)的属性中的参数，目前是可以修改的状态，用户会认为可以在这里修改一些参数。
      -- 视频滤镜，在属性窗口中显示的是示例图片的信息，而不是滤镜的参数信息；
      -- 属性窗口的“应用”按钮，容易让用户误解为应用到当前clip

  5) “文件”窗口中的文件应该按工程分类，或者可以让用户自己创建分类，避免工程增多时，不方便查找和管理文件   
      目前是所有工程的文件都放在一起，工程越多，文件越多，管理和查找文件都不是很方便

  6) 所有资源增加搜索功能，可以帮助老用户更快的查找资源，节约时间

  7) 文件只有缩略图预览，可以增加其他预览方式，比如详细信息

**Comment by vgawen** [comment]
把之前的调研结果，整理成文档，同 #470

**Comment by pisceshsu** [comment]
文档已提交，参见：https://github.com/hansewu/Yifang-Document/blob/master/%E6%B5%8B%E8%AF%95%E7%BB%84/7%E6%9C%88/%E5%BC%A0%E9%9D%99/MovieMator%E6%98%93%E7%94%A8%E6%80%A7Bugs%E5%92%8C%E5%BB%BA%E8%AE%AE_%E5%BC%A0%E9%9D%99_20190718.pdf
