### ISSUE TITLE
MovieMator导出可靠性测试结果

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#424]
目前，已覆盖的测试有：
1.视频/音频滤镜/贴图各参数，操作可正常输出；
2.时间线轨道/clip/右键菜单操作，操作可以正常输出；

**Comment by hpuzj** [comment]
1.添加「预调色彩」滤镜，开启关键帧，然后再关闭关键帧，程序卡死。100%
2.添加「图像网络」时，会遇到程序卡死问题
3.预调色彩：关闭关键帧时，程序卡死强制退出，重启程序打开工程文件，程序崩溃，再次打开工程正常。（程序无法复现的崩溃逐渐开始增多）
4.添加关键帧功能时，在clip的开头或结尾部位添加关键帧，步骤：
   1）点击「开启关键帧」，clip的开始和结束位置显示关键帧标识，但是开启关键帧前面的对号没有勾选
   2）需要再次点击「开启关键帧」前面的“口”，关键帧才可以开启并定位

**Comment by pisceshsu** [comment]
目前，已覆盖的测试有：
1.视频/音频滤镜/贴图各参数，操作可正常输出；
2.时间线轨道/clip/右键菜单操作，操作可以正常输出；

**Comment by hpuzj** [comment]
thread/address的测试结果
[MovieMator2.6.2输出代码可靠性测试报告.pdf](https://github.com/hansewu/MovieMator/files/3360865/MovieMator2.6.2.pdf)
