### ISSUE TITLE
滤镜预览播放图片改进

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#425]
1  将图片改成灰暗一点的色调， 使得一些颜色滤镜效果更显著。
2  将滤镜缺省图标对应的图片用SUPER PHOTOCUT PRO扣下来贴到调色过的图片上。注意色调上的一致性。

**Comment by vvyan** [comment]
原图：
![滤镜预览图](https://user-images.githubusercontent.com/37361188/60649383-77834f80-9e74-11e9-8451-2dc74b02a043.jpg)


滤镜改进图：
![滤镜预览改进图](https://user-images.githubusercontent.com/37361188/60649409-823de480-9e74-11e9-8152-5d4879e81587.jpg)

**Comment by hansewu** [comment]
1 需要叠加一张前景图在前面：
“2 将滤镜缺省图标对应的图片用SUPER PHOTOCUT PRO扣下来贴到调色过的图片上。注意色调上的一致性。”
2 降低图片对比度。

**Comment by vvyan** [comment]
![滤镜改进图](https://user-images.githubusercontent.com/37361188/61191332-b9fe2500-a6db-11e9-83a2-4a84a70ab6e5.jpg)

**Comment by hpuzj** [comment]
2019.07.15日跟测结果：
“叠加一张前景图”的图片暂未替换，资源上传后再继续跟测。

**Comment by hpuzj** [comment]
跟测完成
视频滤镜预览图片已替换。
