### ISSUE TITLE
QQ 3038147064 反馈视频导出后音频前移/后移

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#426]
![image](https://user-images.githubusercontent.com/37360104/60248610-970afd00-98f5-11e9-826c-a5a0d058bac6.png)
“播放时本来应该在这一部分放音频  但导出的视频  音频跑到下一段了”，导出直接对应错了，对应到了下一段（4.游戏部分.flv）的开头；
“编码质量改为100%  分辨率改了下   视频改为30帧   视频模式HD 1080P 30FPS”
![image](https://user-images.githubusercontent.com/37360104/60248674-b6a22580-98f5-11e9-823a-f6bd64ecbe9d.png)
“这个下面的页面.flv 起始处跑到电视（电视没信号的那个界面）那段了”
音频出现前移或者后移的问题，且错位得比较明显，差了数秒以上。

xyy用V2.6.1在win10上测出同样的问题，导出设置为：视频模式HD 1080P 30FPS；导出格式MP4(H264); 100%编码质量；帧速率30帧
遇到的问题：1.音频滞后20秒左右
2.导出的视频画面不正常，画面的下半部分很多杂乱的方块；不知道是导出问题还是播放器问题
![F83974AEA0BE5CB04144CF6E9C0DCD16](https://user-images.githubusercontent.com/37360104/60253484-d12ccc80-98fe-11e9-9903-9c678cc69d43.jpg)

项目文件和源文件已发送给xjp（用户未提供项目文件和视频，以上资源是xyy测试时使用的）

**Comment by pisceshsu** [comment]
6.28  继续验证音视频不同步问题

目前的测试结果是：
不同步是由一个 1920x1080  30fps的视频引起的，用户看到输入视频是30fps, 希望输出也是30fps, 所以导出的时候修改帧率未30，导致不音频轨道滞后20s才播放。
1. 若把输出帧率改回24, 没有延迟
2. 若把出错视频中的41s-50s这一段切分并删除，没有延迟。 
3. 若把出错视频用TVC pRO转换为H264 MP4, MPEG MP4, FLV格式，导出30fps时，没有延迟。


其他测试的情况有：
1.把出错视频随机切分多次，不删除片段，导出30fps，延迟20s
2.把出错视频前后分别切分一段10s片段，删除，导出30fps，延迟20s
3.出错视频后面加或不加其他视频，导出30fps, 延迟20s

**Comment by pisceshsu** [comment]
已发送转换后的视频给xyy，等待用户反馈

**Comment by pisceshsu** [comment]
2.6.4已解决，和鼠标拖拽文件到时间线有关
