### ISSUE TITLE
steam V2.6.1 在win10上，预览区时长显示错误

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#427]
![wrongtimecode](https://user-images.githubusercontent.com/37360104/60253908-83649400-98ff-11e9-84ba-5eed8cd444fd.png)
视频3分多钟，预览区显示4分多钟
视频已发送给xjp

**Comment by hpuzj** [comment]
播放器下面的进度条显示的时长是轨道上clip的总时长，而属性位置显示的时长是当前选中clip的时长
如上图：
用户选中的是中间clip，右上角的属性：起始时间是00：00：00：00，结束时间是00：03：28：17，说明轨道选中clip的时长的03：28：17
但是如果轨道上只有一段clip，且clip放在轨道开始位置，此时播放器下面的时长比右上角属性显示的时长多一帧
