### ISSUE TITLE
steam V2.6.1 在win10上语言设置为中文，滤镜的名称基本都是中文

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#429]
语言是中文，但是滤镜分类和名称基本是中文
![image](https://user-images.githubusercontent.com/37360104/60258410-adba4f80-9907-11e9-9ea3-403aac9af1d7.png)

**Comment by debelliszhu** [comment]
感觉字敲错了。应该是用的是英文版软件，滤镜名字基本都是中文 这个意思吧

**Comment by pisceshsu** [comment]
2.6.4已解决
