### ISSUE TITLE
V 2.6.1 steam版，在win10上打开项目文件出错退出

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#432]
用户发送的项目文件：
[untitled.mmp.zip](https://github.com/hansewu/MovieMator/files/3337788/untitled.mmp.zip)

点击打开——选择项目文件——直接点ok，出现runtime error的提示——点确定——软件卡住几秒后，提示遇到故障需要退出
![image](https://user-images.githubusercontent.com/37360104/60321507-8fa82a00-99af-11e9-8ae8-fa3ebbeb84bf.png)

**Comment by hansewu** [comment]
没有资源，我这用2.6.2 可以打开。也可以成功转换。

如果能联系上，发一个最新版本让其试验。

**Comment by AliciaMoris** [comment]
在win10上使用新版本2.6.2可以打开了
