### ISSUE TITLE
右上角TAB 高度增加，并且增大字体

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#433]
![image](https://user-images.githubusercontent.com/17918660/60334696-aad66200-99ce-11e9-92b4-0295d29a078d.png)

右上角TAB 高度增加，并且增大字体

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/60576571-3de91080-9db0-11e9-96ef-f5b85b6c4039.png)
![图片](https://user-images.githubusercontent.com/44854531/60576593-4e00f000-9db0-11e9-9fe5-d4197a9b205e.png)

字体变大了，宽度也需要增加一点，字号14，宽115，高45，原来字号11，宽90，高35

**Comment by hpuzj** [comment]
跟测完成
与之前版本进行对比，右上角TAB高度、宽度、字体等都比之前版本略大
![屏幕快照 2019-07-15 下午2 13 53](https://user-images.githubusercontent.com/48675877/61198097-e5e4cf00-a70a-11e9-9acb-e0aad21eb261.png)
