### ISSUE TITLE
2.6.2 win7测试  增加轨道快捷键ctrl+Y  ctrl+U 无效

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#436]

**Comment by Dragon-S** [comment]
实际问题是，当播放器widget被激活时，当前的键盘事件被播放器widget拦截，并且没有转发，造成非播放器界面的快捷键都失效。

修改方法：

void Player::keyPressEvent(QKeyEvent *event)
{
    switch (event->key())
    {
        case Qt::Key_Escape:
            if (isFullScreen())
                toggleFullScreen();
            break;
    }
}

改为：

void Player::keyPressEvent(QKeyEvent *event)
{
    switch (event->key())
    {
        case Qt::Key_Escape:
            if (isFullScreen())
                toggleFullScreen();
            break;
        default:
            QWidget::keyPressEvent(event);
            break;
    }
}
