### ISSUE TITLE
2.6.2 滤镜分类下拉列表，中英文状态都是英文显示，且英文超出列表左右范围

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#438]
英文状态超出列表左右范围
滤镜列表中的滤镜分类未翻译
![2](https://user-images.githubusercontent.com/48675877/60337333-5aaece00-99d5-11e9-9050-a0778fdeaf1f.png)

**Comment by hpuzj** [comment]
英文状态下，贴图的动画效果及贴图分类，中文显示
![英文版贴图分类名称是中文](https://user-images.githubusercontent.com/48675877/60407664-367a0980-9bee-11e9-94f8-0c7bc2c80685.png)

**Comment by WanYuanCN** [comment]
英文状态下显示为中文，是因为这些内容的翻译不是通过qt的tr()翻译的，是根据当前的语言设置来读取对应的内容，修改语言使用软件的设置->语言的值来判定。

**Comment by WanYuanCN** [comment]
软件的设置->语言在软件首次打开的情况下，如果不手动设置的话会使用系统默认的语言，也就是中文情况下是"zh_CN"，但是手动设置的值却是"zh"，这样在判断Settings.language()=="zh"的情况下就会有问题，明明是中文但是却不是"zh"而是"zh_CN"，只使用了"zh"判断的代码就会出错，导致文字显示不正确。
