### ISSUE TITLE
资源库文件列表，音频文件缩略图为白色

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#44]
### **问题：**
资源库文件列表，音频文件缩略图为白色
![10](https://user-images.githubusercontent.com/48675877/56182432-c4f5da80-6044-11e9-875a-ba8035b52080.png)
### **来源：**
Mac 0.1.6版本测试

**Comment by WanYuanCN** [comment]
现在的音频文件缩略图替换为音频滤镜中的图片Audio.png；原先显示为白色的图片是mlt底层在获取图片失败时自动生成的图片，不好修改，所以现在只是把音频文件的缩略图替换成一张固定图片。
