### ISSUE TITLE
2.6.2  变换滤镜，开启关键帧，将大小模式改为「变形」，给出提示选择yes,视频预览黑屏。

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#446]
添加变换滤镜，此时参数中的「大小模式」为填充，开启关键帧功能，将大小模式改为「变形」，给出提示，选择yes,视频黑屏，预览也黑屏。

**Comment by vgawen** [comment]
开启关键帧后会不停的调用filter.syncCacheToProject，同时会刷参数界面，导致参数设置失败。
