### ISSUE TITLE
左上角资源增加text分类

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#449]

**Comment by Dragon-S** [comment]
基本功能已经完成，如下图
![捕获](https://user-images.githubusercontent.com/36149358/60760273-57ff4900-a065-11e9-90f5-cae2a150b6df.PNG)

暂时还存在的问题：
（1）界面未翻译
（2）目前提供的模板部分存在崩溃
（3）模板的效果待改进
（4）模板缩略图

**Comment by Dragon-S** [comment]
文字模板存放位置：
C:\Projects\MovieMator\template\text

资源已上传资源仓库：
https://github.com/hansewu/MovieMator-Resource

文字模板资源：
[text.zip](https://github.com/hansewu/MovieMator/files/3364961/text.zip)

**Comment by hpuzj** [comment]
跟测结果
https://github.com/hansewu/MovieMator/issues/535
https://github.com/hansewu/MovieMator/issues/536
https://github.com/hansewu/MovieMator/issues/540
