### ISSUE TITLE
剪大师扁平化效果图设计

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#450]

**Comment by vvyan** [comment]
![剪大师扁平化设计20190704汪艳](https://user-images.githubusercontent.com/37361188/60649585-db0d7d00-9e74-11e9-98f7-5af5711d9988.png)

**Comment by hansewu** [comment]
[](https://user-images.githubusercontent.com/17918660/60695708-4e66cb80-9f15-11e9-9c15-d421fa6632c8.png)
如图，几个改进建议。

**Comment by vvyan** [comment]
![剪大师扁平化设计](https://user-images.githubusercontent.com/37361188/61029644-17e5f080-a3ee-11e9-806c-1e6b992b1a5b.png)

还需继续改进：
1 扁平效果的质感没有出来
2 界面大大小小比较杂乱
3 部分还未扁平化 如左上角按钮

**Comment by vgawen** [comment]
下一阶段改进转到 #525
