### ISSUE TITLE
2.6.2 undo、redo 问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#453]
步骤：
1. 轨道添加clip，clip切分后，选取中间一段，添加滤镜（添加或不添加关键帧都可以），其余片段可删掉
2.再向轨道添加clip，切分后选取中间片段
3.点击undo，直到撤销到第1步中的滤镜消失
4.点击redo,只能恢复到第1步中的添加滤镜（如果添加的是多个滤镜，只能恢复第一个滤镜，关键帧也无法恢复）
5.第一步中「添加滤镜」后的操作全部不能恢复，此时redo按钮置灰

**Comment by fuyunhuaxin** [comment]
关闭掉滤镜初始化的set操作，这个情况就不会出现了
