### ISSUE TITLE
文件Dock支持点击右上角加号图标添加

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#456]

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/60633606-117bd580-9e3e-11e9-8367-7bff79a16f23.png)
文件dock点击出现右上角加号按钮

**Comment by hpuzj** [comment]
跟测结果。
点击文件右上角的”+“，向轨道添加clip，clip追加到轨道的最后位置。
但是通过”+“添加到轨道上的clip不是选中状态，点击播放按钮，播放器下面的进度条向前移动，但是游标不动，即使点击时间轴移动游标位置，预览时游标仍然不动。必须选中clip。
![播放问题](https://user-images.githubusercontent.com/48675877/61206832-1f770380-a726-11e9-99ec-9b6731cd0cbe.gif)

**Comment by hpuzj** [comment]
跟测结果：点击”+“会显示虚线的正方形，应该去掉这个虚线的正方形
![屏幕快照 2019-07-16 上午11 24 28](https://user-images.githubusercontent.com/48675877/61263668-716a6880-a7bc-11e9-9e61-9d331b08a6ab.png)

**Comment by WanYuanCN** [comment]
按钮的虚线框已去除
