### ISSUE TITLE
贴图Dock支持点击右上角加号图标添加

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#457]

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/60633655-4f78f980-9e3e-11e9-97d2-4111ae313299.png)
贴图dock鼠标悬浮出现右上角加号按钮

**Comment by hpuzj** [comment]
跟测结果：
贴图右上角已经添加”+“按钮，但是点击”+“后，会显示一个虚线的倒三角，如图：
![屏幕快照 2019-07-16 上午11 20 29](https://user-images.githubusercontent.com/48675877/61263557-edb07c00-a7bb-11e9-83f5-26b11285f5ba.png)

**Comment by WanYuanCN** [comment]
虚线框已去除
