### ISSUE TITLE
视音频滤镜Dock支持拖拽添加滤镜

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#458]

**Comment by Dragon-S** [comment]
目前的两个滤镜dock是使用qml实现的，实现拖拽功能比较简单，但是低版本的qml目前没有找到实现拖拽过程显示缩略图的方法，目前只能实现拖拽过程显示文字。qml5.8引入了sourceimagepath属性，可支持拖拽过程显示缩略图。为了各dock风格及操作统一，初步考虑用C++从新实现滤镜dock

**Comment by Dragon-S** [comment]
用C++实现滤镜dock——完成了基本的结构。由于之前其他的dock写的比较散，封装不够，目前重新尝试写了一下，进展没有想的那么快，要封装几个数据结构，还要适配原来的功能（把qml功能用c++实现）。初步考虑先沿用effectdock，后期在整体抽象成一个dock基类。从目前的理解来看，需要适配滤镜数据，以及滤镜的功能及操作。目前正基于effectdcok实现

**Comment by Dragon-S** [comment]
用droparea的keys过滤需要的拖拽源
timeline.qml中droparea的keys
keys: ["application/mlt+xml", "application/x-qabstractitemmodeldatalist", "text/uri-list"]

解决重叠的timeline和clip接收自己感兴趣的拖拽源

**Comment by hpuzj** [comment]
根测结果：通过拖拽添加滤镜目前存在两个问题：
1.拖拽添加滤镜，松开鼠标时，滤镜缩略图会向左上角回弹， https://github.com/hansewu/MovieMator/issues/542
2. 通过拖拽添加滤镜后，播放器显示的是滤镜的预览效果，而不是clip添加滤镜后的效果https://github.com/hansewu/MovieMator/issues/551
