### ISSUE TITLE
2.6.2 clip添加「环形边框」滤镜，播放器白屏，且继续向下任意一步操作程序卡死，只能强制退出

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#463]
添加滤镜前：
![3](https://user-images.githubusercontent.com/48675877/60415130-d9418080-9c0c-11e9-91cc-b3e30c6a14c2.png)
添加滤镜后：
![4](https://user-images.githubusercontent.com/48675877/60415149-e52d4280-9c0c-11e9-840f-831ebce33930.png)

**Comment by vgawen** [comment]
mlt_properties_anim_get里面加了返回没有退出临界区导致。
	if(!value) return NULL;
        改为：
	if(!value)
	{
		leave_security_guard(&( ( ( property_list * )self->local )->guard));
		return NULL;
	}
