### ISSUE TITLE
2.6.2 「视频模式」界面需要优化

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#465]
1. 界面标题不能使用 Dialog,可以改为视频模式
2.Video Mode 最后的e显示不全，被下拉菜单框遮挡
3.翻译问题：中文状态下界面元素显示的全部是英文
4.默认窗口大小，视频模式下拉菜单展开后，最下面边与该窗口界面的最下边重合，看起来很不好看
5.通过鼠标拉伸，修改视频模式窗口大小
 1）拉长使界面增大，界面元素，不跟着变化，还是在原来的位置
 2）缩小，就只剩下标题栏中的“？”“X”

![5](https://user-images.githubusercontent.com/48675877/60418764-5ae9dc00-9c16-11e9-98bf-d2175fc5beee.png)

**Comment by pisceshsu** [comment]
2.6.4发布版本已解决
