### ISSUE TITLE
MovieMator与喵影工厂在短视频上的易用性差异 

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#470]
对比MovieMator与喵影工厂在制作一个短于5分钟视频上的易用性差异(哪个会更快完成，为什么？)

**Comment by pisceshsu** [comment]
镜头切分功能对比：
MovieMator:
1.缺点
  1) 长视频clip只有首尾有缩略图，中间没有缩略图，不方便镜头的粗略定位。只能在时间线点击做不精确的定位
  2) 切分后的clip缩略图与内容不符，不利于后期较快速的找到clip。 Clip缩略图做得好，也相当于标记功能。

2.优点
   1) 播放头到时间线末端时，时间线会自动往左移动。
       喵影工厂没有这个功能，感觉很不方便，需要移动滚动条来实现。但滚动条的移动往往不精确，滚动条移动一点点，时间线会移动很长一段。

**Comment by hpuzj** [comment]
使用MovieMator和喵影工厂做同样一段视频，却做不出同样的效果
Moviemator 可以实现的部分功能，喵影工厂不能实现
喵影工厂可以实现的部分功能，MovieMator实现不了

1.滤镜
1.1. 滤镜名称
 喵影工厂的滤镜名称比MovieMator更通俗，而MovieMator的滤镜名称对于普通用户太过专业，例如：中值滤波、阀值、动态阀值、3级阀值等等
1.2. 滤镜效果
1.1 滤镜直接预览更喜欢喵影工厂的滤镜预览效果，原因有两点：
  1)滤镜直接预览时，给出一段视频进行预览，效果比MovieMator的图片预览要好
  2) 当轨道上有clip时，滤镜预览直接取的是当前游标所在位置的图像进行预览，比MovieMator效果更直观
1.3.增加或删除滤镜，MovieMator更友好
Clip添加多个滤镜，删除滤镜时互相不影响，而是用喵影工厂是删除效果，只要是拖动到clip上的滤镜和修改的速度，全部被删除

2. 喵影工厂，轨道clip，右键显示的菜单功能比较全面，可以作为以后MovieMator优化右键菜单功能的一个参考（旋转90度、倒放、显示时长、复制效果）
 
3. 轨道clip不能多选真是硬伤，太不方便了。制作工程文件的过程中，大部分时间都是浪费在一个一个拖动clip上了。

4.界面功能按钮的友好性不够，该置灰的时候不置灰
1）选择音频后，工具栏中的 改变大小、旋转、裁剪应该置灰
2）轨道无clip时，或无任何选中状态，删除、切分、缩放到合适 也应该置灰

5.MovieMator的轨道关闭音频功能比音频分离更方便

6. 导出
1）喵影工厂导出界面比较简洁，MovieMator需要把视频分类收起来，而不是视频分类全部展开，界面看起来既乱又不方便用户预览。
2）moviemator不支持GIF格式的输出
3）喵影工程导出时，除了导出窗口上的进度条和渲染画面，电脑桌面程序坞中的图标上也显示导出进度百分比，对用户来说很方便。

**Comment by vgawen** [comment]
和 #423 一起，把之前的调研结果，整理成文档

**Comment by pisceshsu** [comment]
文档已提交，参见： https://github.com/hansewu/Yifang-Document/blob/master/%E6%B5%8B%E8%AF%95%E7%BB%84/7%E6%9C%88/%E5%BC%A0%E9%9D%99/MovieMator%E6%98%93%E7%94%A8%E6%80%A7Bugs%E5%92%8C%E5%BB%BA%E8%AE%AE_%E5%BC%A0%E9%9D%99_20190718.pdf
