### ISSUE TITLE
Address Sanitizer测试, 大部分视频滤镜预览会引起程序崩溃，并报stack-buffer-overflow错误

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#471]
1. 绝大部分视频滤镜预览时，存在stack-buffer-overflow问题，报同一个错误
透视变换、翻转、上下黑边、上色、饱和度等等
[stack-buffer-overflow.pdf](https://github.com/hansewu/MovieMator/files/3352986/stack-buffer-overflow.pdf)

**Comment by hpuzj** [comment]
### **代码：**
![屏幕快照 2019-07-08 下午5 19 56](https://user-images.githubusercontent.com/48675877/60798912-af580300-a1a4-11e9-884f-09c56e36e8ca.png)

### **详细报告：**
==16394==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7000045f2af8 at pc 0x0001223e6ff1 bp 0x7000045f19b0 sp 0x7000045f19a8
READ of size 8 at 0x7000045f2af8 thread T193
    #0 0x1223e6ff0 in process_frei0r_item frei0r_helper.c:186
    #1 0x1223e4d7c in filter_get_image filter_frei0r.c:39
    #2 0x107855245 in mlt_frame_get_image mlt_frame.c:672
    #3 0x1078b9956 in consumer_read_ahead_thread mlt_consumer.c:1007
    #4 0x10744d7b5 in Mlt::RenderThread::run() glwidget.cpp:829
    #5 0x10870d539 in QThreadPrivate::start(void*) (QtCore:x86_64+0x29539)
    #6 0x7fff7fcf633c in _pthread_body (libsystem_pthread.dylib:x86_64+0x333c)
    #7 0x7fff7fcf92a6 in _pthread_start (libsystem_pthread.dylib:x86_64+0x62a6)
    #8 0x7fff7fcf5424 in thread_start (libsystem_pthread.dylib:x86_64+0x2424)
 
Address 0x7000045f2af8 is located in stack of thread T193 at offset 120 in frame
    #0 0x1078b85bf in consumer_read_ahead_thread mlt_consumer.c:807
 
  This frame has 6 object(s):
    [32, 36) 'width' (line 818)
    [48, 52) 'height' (line 819)
    [64, 68) 'samples' (line 827)
    [80, 88) 'audio' (line 828)
    [112, 120) 'image' (line 835) <== Memory access at offset 120 overflows this variable
    [144, 160) 'ante' (line 838)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T193 created by T192 here:
    #0 0x1099ad00d in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4d00d)
    #1 0x10870dd48 in QThread::start(QThread::Priority) (QtCore:x86_64+0x29d48)
    #2 0x107448868 in Mlt::GLWidget::createThread(Mlt::RenderThread**, void* (*)(void*), void*) glwidget.cpp:542
    #3 0x10744bdab in onThreadCreate(mlt_properties_s*, Mlt::GLWidget*, Mlt::RenderThread**, int*, void* (*)(void*), void*) glwidget.cpp:551
    #4 0x1078b3751 in transmit_thread_create mlt_consumer.c:1956
    #5 0x10788ebf1 in mlt_events_fire mlt_events.c:231
    #6 0x1078b8430 in mlt_thread_create mlt_consumer.c:1991
    #7 0x1078b7153 in consumer_read_ahead_start mlt_consumer.c:1265
    #8 0x1078b6bd6 in mlt_consumer_rt_frame mlt_consumer.c:1754
    #9 0x11c4eebed in consumer_thread consumer_sdl_audio.c:571
    #10 0x7fff7fcf633c in _pthread_body (libsystem_pthread.dylib:x86_64+0x333c)
    #11 0x7fff7fcf92a6 in _pthread_start (libsystem_pthread.dylib:x86_64+0x62a6)
    #12 0x7fff7fcf5424 in thread_start (libsystem_pthread.dylib:x86_64+0x2424)
 
Thread T192 created by T0 here:
    #0 0x1099ad00d in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4d00d)
    #1 0x11c4ee0a1 in consumer_start consumer_sdl_audio.c:190
    #2 0x1078b4fd6 in mlt_consumer_start mlt_consumer.c:647
    #3 0x1077f805b in Mlt::Consumer::start() MltConsumer.cpp:113
    #4 0x1074229d8 in Mlt::Controller::play(double) mltcontroller.cpp:256
    #5 0x107465c60 in Mlt::GLWidget::play(double) glwidget.h:71
    #6 0x10742e3b0 in Mlt::TransportControl::play(double) mltcontroller.cpp:929
    #7 0x107462061 in Mlt::TransportControl::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) moc_mltcontroller.cpp:104
    #8 0x1088fb15f in QMetaObject::activate(QObject*, int, int, void**) (QtCore:x86_64+0x21715f)
    #9 0x10427d7f0 in Player::played(double) moc_player.cpp:575
    #10 0x103df61df in Player::play(double) player.cpp:641
    #11 0x10427be0b in Player::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) moc_player.cpp:324
    #12 0x1088fb15f in QMetaObject::activate(QObject*, int, int, void**) (QtCore:x86_64+0x21715f)
    #13 0x1089027ea in QSingleShotTimer::timerEvent(QTimerEvent*) (QtCore:x86_64+0x21e7ea)
    #14 0x1088f419f in QObject::event(QEvent*) (QtCore:x86_64+0x21019f)
    #15 0x1079e2ec5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (QtWidgets:x86_64+0x11ec5)
    #16 0x1079e5984 in QApplication::notify(QObject*, QEvent*) (QtWidgets:x86_64+0x14984)
    #17 0x1088c7f23 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (QtCore:x86_64+0x1e3f23)
    #18 0x10891f151 in QTimerInfoList::activateTimers() (QtCore:x86_64+0x23b151)
    #19 0x10f485da1 in QCocoaEventDispatcherPrivate::activateTimersSourceCallback(void*) (libqcocoa.dylib:x86_64+0x21da1)
    #20 0x7fff529ee128 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (CoreFoundation:x86_64+0x58128)
    #21 0x7fff529ee0ce in __CFRunLoopDoSource0 (CoreFoundation:x86_64+0x580ce)
    #22 0x7fff529d1f6f in __CFRunLoopDoSources0 (CoreFoundation:x86_64+0x3bf6f)
    #23 0x7fff529d1516 in __CFRunLoopRun (CoreFoundation:x86_64+0x3b516)
    #24 0x7fff529d0df9 in CFRunLoopRunSpecific (CoreFoundation:x86_64+0x3adf9)
    #25 0x7fff51c5c894 in RunCurrentEventLoopInMode (HIToolbox:x86_64+0xa894)
    #26 0x7fff51c5c5ca in ReceiveNextEventCommon (HIToolbox:x86_64+0xa5ca)
    #27 0x7fff51c5c347 in _BlockUntilNextEventMatchingListInModeWithFilter (HIToolbox:x86_64+0xa347)
    #28 0x7fff4ff1995a in _DPSNextEvent (AppKit:x86_64+0x1a95a)
    #29 0x7fff4ff186f9 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (AppKit:x86_64+0x196f9)
    #30 0x7fff4ff1275c in -[NSApplication run] (AppKit:x86_64+0x1375c)
    #31 0x10f4869bc in QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (libqcocoa.dylib:x86_64+0x229bc)
    #32 0x1088c42f0 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (QtCore:x86_64+0x1e02f0)
    #33 0x1088c8594 in QCoreApplication::exec() (QtCore:x86_64+0x1e4594)
    #34 0x103c4edb4 in main main.cpp:591
    #35 0x7fff7fb04084 in start (libdyld.dylib:x86_64+0x17084)
 
SUMMARY: AddressSanitizer: stack-buffer-overflow frei0r_helper.c:186 in process_frei0r_item

**Comment by vgawen** [comment]
所有AddressSanitizer问题都测试了一遍。f4v视频预览崩溃没有复现。新发现插入轨道崩溃。目前只解决了插入轨道崩溃。其他的还没找到原因。

**Comment by hpuzj** [comment]
跟测完成。
对于启用Address Sanitizer后,插入轨道闪退问题已解决。
插入音频轨道和视频轨道，均无闪退问题。

**Comment by vgawen** [comment]
滤镜预览崩溃问题已解决。

**Comment by hpuzj** [comment]
跟测完成
1.启用Address Sanitizer后，将所有滤镜全部预览一遍，均无崩溃问题。
