### ISSUE TITLE
添加Crop滤镜，调整参数值，undo到去掉Crop滤镜。再一直redo，参数值并没有redo回来。

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#475]

**Comment by fuyunhuaxin** [comment]
添加滤镜的command的redo中是新生成一个filter。当undo将滤镜去掉之后，redo回来时用的又是新的filter了，但是之前滤镜set操作的command里面存的是老的filter，所以此时redo来set滤镜参数并不能起效果。
