### ISSUE TITLE
V2.6.1 win10 导出视频部分白屏

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#476]
录制的视频约5G，时长30分钟左右，本来是打算让视频加背景音乐的，当视频导出后，视频容量从5G左右变成14G左右，播放时前12分钟左右基本没问题，但后面的时间全是白屏，只余下背景音乐；

录制视频是MP4，用win10xbox录制，分辨率1920*1080，只有在最近几十秒里音乐多出来的时间才切分删除了——steam用户，已给差评

**Comment by pisceshsu** [comment]
测试组在win10上下载一个xbox，试一下

**Comment by hpuzj** [comment]
使用win10自带的xbox录屏工具录制视频，导入程序，为视频添加3段背景音乐，背景音乐之间不挨着，全部留有空隙，导出的视频总时长为19：14，从15:10分开始，后面的全部为同一个画面
原视频帧率为30.0077
导出视频帧率为60帧/秒

**Comment by pisceshsu** [comment]
2.6.4版本已解决
