### ISSUE TITLE
V2.6.1 steam win用户再次反馈改变帧速率时导出视频黑屏

### ISSUE THREAD

**Issue by AliciaMoris** [hansewu/MovieMator#477]
文件资源和问题细节：
http://58.221.58.161:81/forum.php?mod=viewthread&tid=2713&extra=page%3D1

用户反馈视频模式设置为自动或者30fps时，导出仍然黑屏，问题没有得到解决
用户认为软件应该识别最合适的视频模式，设置为自动的视频模式时，导出不应该出现错误

**Comment by pisceshsu** [comment]
2.6.4发布版本解决
