### ISSUE TITLE
文字滤镜和变换滤镜添加时还会设置参数

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#482]

**Comment by fuyunhuaxin** [comment]
1 resetproperty导致每次set之前都会把老的值清空成一个无效值，导致undo的时候回不回来。
2 push命令之前会判断老的值和新值是否相同，并且判断老的值是否有效。刚好判断是否有效的那个函数有问题，所以setRect的push命令一直有问题。

**Comment by pisceshsu** [comment]
2019.7.12跟测结果：
添加后需要undo多次才能撤销的问题基本解决，还有以下四个滤镜需要再修改一下：
1.添加后，需要undo2次
   1) 叠加     
   2） Rutt-Etra-lzer 
  3) 视频淡出

2.添加后，需要undo5次才能删除
   1） 3D文字

**Comment by fuyunhuaxin** [comment]
1 个别滤镜需要根据视频或者音频本身的长度等参数来设置初始化的值，不能直接使用默认配置的初始化值，所以初始化的时候必然要设置一下。

**Comment by vgawen** [comment]
> 添加后需要undo多次才能撤销的问题基本解决，还有以下四个滤镜需要再修改一下：
> 1.添加后，需要undo2次
> 
>     1. 叠加
>        2） Rutt-Etra-lzer
> 
>     2. 视频淡出
> 
> 
> 2.添加后，需要undo5次才能删除
> 1） 3D文字

#539
