### ISSUE TITLE
工具栏中的声音滤镜，添加关键帧后，调整参数仍然无声音

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#49]
### **问题:**
工具栏中的声音滤镜，添加关键帧后，无声音，调整参数仍然无声音

### **来源：**
Mac 测试，Steam用户也反馈过该问题
### **版本：**
MovieMator Pro  2.5.4

**Comment by pisceshsu** [comment]
建议解决方法：去掉”声音“滤镜的关键帧设置

**Comment by pisceshsu** [comment]
去掉关键帧后，调整Gain参数，声音无变化
