### ISSUE TITLE
WINDOWS版本文字滤镜position animation,无出点动画模板

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#490]
2.6.2测试，文字滤镜position animation,无出点动画模板，图中是windows上所有的模板
测试时只有Windows版本，没有Mac版本
![7](https://user-images.githubusercontent.com/48675877/60717561-bab4ef80-9f54-11e9-9aa2-f1920538d594.png)
![8](https://user-images.githubusercontent.com/48675877/60717573-bf79a380-9f54-11e9-909d-cf5365bf95c3.png)

**Comment by Dragon-S** [comment]
主要原因时测试的版本出点动画模板资源未添加。
