### ISSUE TITLE
添加文字滤镜，选择Position Animation后文字变小了。

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#494]

**Comment by fuyunhuaxin** [comment]
添加关键帧之后，任何非动画的set都会将动画数据清除掉，所以只能获取getAnimate数据传回并用来作为添加关键帧的参数。但是在添加了首位关键帧之后，立马通过getAnimate获取到的动画数据却是获取不到，导致写回到界面的参数也是非法的。

**Comment by fuyunhuaxin** [comment]
滤镜添加的时候会对各种参数进行set设置操作，在没有设置默认值的时候，这个set操作会push一个命令，这样导致undo需要undo很多次，解决undo很多次这个问题的时候，是给滤镜的参数通过在meta文件里面添加默认参数来解决，但是这样就会把这个参数同样设置成关键帧参数，刚好dynamictext的size这个参数不能当成关键帧设置，因为没有control UI控件，导致数据没办法回写（从底层拿数据然后设置到UI控件上面）现在解决的办法是把这个size参数类型设置为‘*’ 。这样各种关键帧操作就不会影响到size这个参数了。

**Comment by pisceshsu** [comment]
跟测完成，问题已解决
