### ISSUE TITLE
文字滤镜界面分组显示和清晰化

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#495]
文字滤镜界面分组和清晰化

将文字滤镜界面分成3-4组，采用分组显示，点击后才显示详细信息的方法进行显示。

**Comment by hansewu** [comment]
分为2组：一组文字风格，一组文字动画

详细信息未使用图片按钮。

左边文字占空间大小还未研究清楚。

**Comment by pisceshsu** [comment]
2019.7.23跟测完成
界面分组后，参数的作用更加清晰
