### ISSUE TITLE
旋转滤镜参数范围修改，方便用于动画制作

### ISSUE THREAD

**Issue by hansewu** [hansewu/MovieMator#497]
旋转滤镜参数范围修改，方便用于动画制作。

旋转角度，OX, OY 范围都太窄。

**Comment by pisceshsu** [comment]
2019.7.15跟测完成：
OX, OY值的范围都扩大到(-1000, 1000)

**Comment by hansewu** [comment]
旋转 -360 到 360  （原 0到360）
OX, OY （-2000， 2000）
放大倍数到800 （8倍）

**Comment by pisceshsu** [comment]
2019.7.17跟测完成：
旋转滤镜的值的范围与预期相符：
旋转: -360 到 360 （原 0到360）
X向偏移, Y向偏移： （-2000， 2000）
缩放：0到800 （8倍）(原 200)
