### ISSUE TITLE
使用Resize滤镜后预览问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#51]
### **问题描述：**
 1）2.5.5播放到使用 resize 滤镜的那一瞬间，画面尺寸和位置是有问题的，和设置的不一 样，一帧后恢复正常
     2）2.5.5视频中间会有多次画面闪烁(用户视频已发，见 github(https://github.com/hansewu/Yifang- Document/tree/master/%E6%8E%A8%E5%B9%BF%E7%BB%84/3%E6%9C%88/xyy)- “MovieMator 的 resize 滤镜 bug 视频”-“ 1video.mp4.zip”)

### **来源:**
用户反馈

### **版本：**
MovieMator Pro2.5.5

**Comment by pisceshsu** [comment]
2.6.4 已解决
