### ISSUE TITLE
文字dock优化

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#510]
文字dock优化
（1）缺少dock图标
（2）缺少分类（名字）
（3）文字模板名字修改
（4）去掉标题
（5）缺少缩略图
（6）检查修改内存泄露

**Comment by WanYuanCN** [comment]
修改了文件的加载方式，但是通过openFile()生成的文件有问题，无法读取资源路径，也就导致了文件的属性、滤镜等无法显示。

**Comment by hpuzj** [comment]
跟测结果。
https://github.com/hansewu/MovieMator/issues/535
https://github.com/hansewu/MovieMator/issues/536
https://github.com/hansewu/MovieMator/issues/540
