### ISSUE TITLE
滤镜dock优化

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#511]
滤镜dock优化
（1）缩略图改为和原来的一样（长方形）
（2）检查修改内存泄漏

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/60931807-a0309c80-a2ed-11e9-8cad-8a205b32a19f.png)
在没有选中时间线clip的情况下添加滤镜会弹出一个提示框，单击提示框OK后，添加的滤镜不会取消红底背景，也就是说多次添加不同滤镜失败的话会有很多滤镜有被选中效果，实际上是没有取消这个滤镜的鼠标悬浮效果。

**Comment by WanYuanCN** [comment]
添加滤镜失败后会出现类似多选效果，实际上不是滤镜的listview的悬浮效果，是添加按钮的悬浮效果，会导致listview也出现悬浮效果，目前的处理方式是出现失败警告后隐藏按钮，这样按钮的悬浮效果就会失效，listview的悬浮效果也就没有了。

**Comment by hpuzj** [comment]
跟测结果
https://github.com/hansewu/MovieMator/issues/534

**Comment by hpuzj** [comment]
7.16日跟测结果
视频滤镜和音频滤镜，名称字体太小，看不清楚。https://github.com/hansewu/MovieMator/issues/550
