### ISSUE TITLE
左侧资源dock基类详细设计方案（主要是在现有的五个dock上提取基类）

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#512]
执行人员：sll（Dragon-S）
审核人员：gdb（vgawen）

主要是在现有的五个dock上提取基类

**Comment by Dragon-S** [comment]
提却设计基类dock已经基本完成，主要是将相同界面和相同操作提交到基类，使用模板方法，在子类实现对应操作的具体功能。，目前文档还未完成。

初步的基类
class BaseDockWidget : public QDockWidget
{
    Q_OBJECT

public:
    explicit BaseDockWidget(QWidget *parent = nullptr);
    ~BaseDockWidget();

    void addItemToDock(QString itemClass, QStandardItem *item);
    void setupUi();

protected:
    virtual void resizeEvent(QResizeEvent *event);
    virtual void setupOtherUi();
    virtual QMap<QString, QStandardItemModel *> *createAllClassesItemModel() = 0;
    virtual bool hasClass() = 0;
    virtual void addToTimeline(const QStandardItem *item) = 0;
    virtual void preview(const QStandardItem *item) = 0;

private slots:
    virtual void addItemToTimeline(const QModelIndex &index);
    virtual void clickedItem(const QModelIndex &index);

private:
    void setupListView();
    void createAllClassesListView(QMap<QString, QStandardItemModel *> *allClassesItemModel,
                                  bool hasClass = true);
    BaseListView *createListView(QStandardItemModel *itemModel);
    void createClassesNameWidget(const QString &className);
    void createClassCombox();

protected:
    Ui::BaseDockWidget *ui;

private:
    //保存所有的分类listview，主要用于从combox切换分类时跳转到对应分类的listview，
    //key为分类名，value为对应的listview
    QMap<QString, BaseListView *> *m_allClassesListView;
};

测试子类：
class TextDockWidget : public BaseDockWidget
{
    Q_OBJECT

public:
    // 构造函数
    explicit TextDockWidget(MainInterface *main = nullptr, QWidget *parent = nullptr);
    ~TextDockWidget();

protected:
    QMap<QString, QStandardItemModel *> *createAllClassesItemModel();
    bool hasClass();
    void addToTimeline(const QStandardItem *item);
    void preview(const QStandardItem *item);

private:
    MainInterface *m_mainInterface;
};

**Comment by Dragon-S** [comment]
初步文档已完成：
[资源Dock功能统一性设计方案V1.0.pdf](https://github.com/hansewu/MovieMator/files/3396868/Dock.V1.0.pdf)

**Comment by Dragon-S** [comment]
[MovieMator资源Dock生成模块详细设计方案V1.1_史龙龙_20190804.pdf](https://github.com/hansewu/MovieMator/files/3475030/MovieMator.Dock.V1.1_._20190804.pdf)

**Comment by Dragon-S** [comment]
[MovieMator资源Dock生成模块详细设计方案V1.2_史龙龙_20190809.pdf](https://github.com/hansewu/MovieMator/files/3485204/MovieMator.Dock.V1.2_._20190809.pdf)

**Comment by vgawen** [comment]
确认
