### ISSUE TITLE
文字添加关键帧后自动变小

### ISSUE THREAD

**Issue by vvyan** [hansewu/MovieMator#519]
1.文字添加
![屏幕快照 2019-07-10 下午2 49 24](https://user-images.githubusercontent.com/37361188/60947263-b9a00b80-a322-11e9-91ff-784cfdedd872.png)
关键帧后自动变小，并且无法再拉大。
2.可以给文字添加预设好的动画，但取消关键帧的话文字也会变小并且无法再拉大。

**Comment by vgawen** [comment]
Duplicate of #494

**Comment by pisceshsu** [comment]
#494 已解决，该issue关闭
