### ISSUE TITLE
tim.bolin@gmail.com:不能通过点击时间轴来移动移动游标了

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#520]
win10
2.6.1版本
更新后，不能通过点击时间轴来移动移动游标了
before the last update, one could click or drag on the time bar above the timeline to reposition the playback head, as one would expect. this no longer works. only the scrubber under the preview, and the manual timecode entry, works now.

![unnamed-2](https://user-images.githubusercontent.com/37359992/60952540-063d1400-a32e-11e9-81d0-78b4391114f8.png)

**Comment by hpuzj** [comment]
无法复现该用户的问题，使用鼠标点击时间轴，游标也会跟着移动

测试系统：
win 10、Mac10.14  2.6.1版本以及2.6.2测试版

**Comment by hpuzj** [comment]
2.6.4 已经解决，因切换资源文件导致的游标无法移动问题
