### ISSUE TITLE
修改导出时的帧率，引起的问题汇总

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#521]
1.导出视频黑屏： https://github.com/hansewu/MovieMator/issues/477

2.导出视频白屏： https://github.com/hansewu/MovieMator/issues/476

3.部分clip内容丢失，或资源错位：https://github.com/hansewu/MovieMator/issues/437

4.音频前移/后移： https://github.com/hansewu/MovieMator/issues/426

5.导出视频长度变短： https://github.com/hansewu/MovieMator/issues/27  ，

**Comment by pisceshsu** [comment]
2019.7.31
导出变短问题原因定位测试结果：是由从资源库拖拽文件到时间线操作引起的

1.拖到到时间线的clip，输出修改为60帧时，会引起视频长度变短的问题
2.用“追加”，“插入”按钮，或“从外部直接拖入时间线”操作，导出60fps视频是正常的，到导出的视频大小有差异，如下图所示：
  
![屏幕快照 2019-07-31 下午4 37 51](https://user-images.githubusercontent.com/6078647/62197880-3f0f5c80-b3b3-11e9-85b6-a2831ee647da.png)

3.“从资源库拖拽”和“追加”操作的临时工程文件差异，在于producer的时间码，如下图黄色方框所示：
    1）左边是“从资源库拖拽”的临时工程文件，时间码是：297
    2)   右边是“追加”操作的临时工程文件，时间码是：00:00:09:27
![工程文件差异](https://user-images.githubusercontent.com/6078647/62198057-8695e880-b3b3-11e9-8908-b30bc7c3013d.png)

**Comment by hpuzj** [comment]
跟测结果
1.新建两个一样的工程文件，一个使用从资源库拖拽clip，另一个使用工具栏「追加」资源
1）文件格式
  视频格式webm、3gp、mp4; 
  图片格式jpg; 
  音频mp3
2）使用滤镜： 变换、裁剪、旋转、卡通特效、模糊、图像网格
3）改变其中两段不同格式的播放速度
2.导出结果
 1）使用拖拽资源库clip到时间线的工程文件，导出视频后，有视频丢失、图片错位问题
 2）使用「追加」按钮添加资源到时间线的工程文件，导出视频正常

**Comment by hpuzj** [comment]
2.6.4版本已经解决了上面描述的与导出相关的问题
