### ISSUE TITLE
时间轴鼠标滚轮缩放到一定程度后，没反应了

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#522]
时间轴鼠标滚轮缩放到一定程度后，鼠标再滚动就没反应了。只能点击右上脚的 +  - 按钮来缩放了。

![屏幕快照 2019-07-10 下午9 57 34](https://user-images.githubusercontent.com/37359992/60975166-14a32400-a35e-11e9-98e5-537cbe2ea1f2.png)

![屏幕快照 2019-07-10 下午9 57 25](https://user-images.githubusercontent.com/37359992/60975177-179e1480-a35e-11e9-8bc9-f5bc67bc64b0.png)

**Comment by pisceshsu** [comment]
与 https://github.com/hansewu/MovieMator/issues/232 重复
