### ISSUE TITLE
剪大师界面效果图优化

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#525]
还需继续改进：
1 扁平效果的质感没有出来
2 界面大大小小比较杂乱
3 部分还未扁平化 如左上角按钮

颜色方面，我感觉文字太白，然后黑色不够黑
质感所以没有
可以研究下瞄影工厂的颜色具体数值是多少

**Comment by vvyan** [comment]
![剪大师扁平化设计719版本一](https://user-images.githubusercontent.com/37361188/61527337-c32a2180-aa4e-11e9-8377-04fd3614cb96.png)

**Comment by vvyan** [comment]
[剪大师界面优化三张20190720汪艳.zip](https://github.com/hansewu/MovieMator/files/3415259/20190720.zip)
