### ISSUE TITLE
文字模版命名和分类

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#530]

**Comment by vvyan** [comment]
分类：
所有
标题
片尾
艺术（含有贴图的文字模板）
字幕

命名以分类来，如艺术，命名为艺术1、艺术2、艺术3.....

**Comment by hpuzj** [comment]
跟测完成
目前文字模板的分类：艺术、片尾、字幕、标题
艺术分为：艺术1，艺术2......
