### ISSUE TITLE
MOVAVI，VIDEOPAD和MOVIEMATOR功能对比

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#531]

**Comment by pisceshsu** [comment]
### MOVAVI:
1.资源库
   1) 可添加文件，添加文件夹，但添加后的文件都被自动添加到主视频轨道, 这种自动添加的操作让人不能理解
   2) 可录像, 录好的视频也是会自动加到主视频轨道
   3) 音效文件，默认不可用，需要下载
   4) 库存视频，比如电影倒计时，胶片，火焰等，需要下载
   5) 背景，一些精选的图片，比如爱，海滨，渐进红色，需要下载
   6) 简介视频，可以用来做片头，片尾，需要下载

2.视频滤镜，没有参数编辑，

3.播放器有一个宽高比的设置:  16:9, 4:3, 1:1, 9:16, X:Y

4.时间线工具栏
   1) 有一个“剪辑属性”功能，分“视频“，”音频“；
     — ”视频“页中，可以调节颜色，大小，位置，动画等参数，几乎可以调节视频相关的所有参数
     — ”音频“页中，可以设置音量，淡入，淡出，均衡器，噪音消除， 音频效果(相当于Moviemator的音频滤镜)
   2) 录音，开始录制后，会在音频轨的播放头位置开始放置clip， 随着时间的推移，clip越来越长，直到录制介绍。 在同一位置录多段时，会在音频轨慢慢往上叠加clip.

   3) 标记功能, 点击后，在播放头位置增加一个标记，可设置和修改名称。鼠标放在标记上时，会显示名称。

6.时间线轨道
   1) 视频轨，包含视频，照片以及他们之间的过渡
       还可放文字，贴图，箭头等clip
        移动视频轨上的clip时，其上面的覆盖轨，文字轨都跟着移动，这样不用担心错位
       不能删除
   2）覆盖轨：包含显示在视频上方的重叠照片或视频， 不能添加转场，文字，贴图，箭头clip
   3） 片头轨：可以添加片头文字，贴图，箭头clip
   4) 关联音频轨，连接至视频剪辑，并与视频轨道同步。试了一下，视频clip右键菜单中点“分离音频”，音频会自动添加到该轨道
   5) 音频轨，独立与视频轨，
   
7.时间线操作
    1）删除视频轨的clip时，后面的clip及对应的覆盖轨和文字轨的clip都自动往前移动
    2) 删除覆盖轨的clip， 删除后保留空隙，其他clip位置不变
    3）覆盖轨，文字轨的clip不会重叠，可以有多层，
    4) 音频轨也可以有多层
    5) clip右键菜单中有“在文件夹中显示”，点击后，会打开clip文件所在文件夹
    6) 有冻结帧的功能，自动提取一帧静止的图片，时长4s

8.过渡，
   不会缩短clip长度 
    不能用鼠标改变长度，


9.导出分类：
   默认输出1920x1080， 修改格式和设备后，分辨率不变，只有xbox时改为1080x720

   1) 视频格式： MP4, AVI, MOV, MPEG-1, MPEG-2, WMV, MKV, FLV, M2TS(H264), WebM， OGV, SWF, DVD(NTSC), DVD(PAL), GIF
   2) 音频格式：MP3, WAV, AAC, FLAC, OGG, WMA
   3) 设备：iPhone,  iPad/iPad mini, Android, Galaxy S6/S7, Nexus 6/Pixel, Playstation, Xbox 360
   4) TV: Samsung 1080p, Sony, LG, Panasonic, Philips, Apple Tv, 
   5）视频网站：youtube, Google Drive, Vimeo,(没有中国的网站)

**Comment by hpuzj** [comment]
### **Movavi Video Editor** 

### **1.登录程序**
登录程序后，会有个阅读指南的弹窗提醒，对于初次使用的用户很友好
### **2. 资源库**
1）添加文件分为添加媒体文件和添加文件夹两种，但是添加的媒体文件只显示在主视频轨道上，并不在资源库显示，使用很不方便
2）提供声音、音乐、库存视频（倒计时等）、背景图片、简介视频的下载
### **3. 视频滤镜**
通过拖拽进行添加，但是不提供任何参数的修改。
### **4.转场**
1）通过拖拽直接添加到两段clip之间，不需要移动clip添加过渡
2）时间线工具栏提供「过渡导向」功能，可以选择转场样式、修改持续时间等参数，为主视频轨道上所有的clip批量添加转场
### **5.文字模板**
1）文字模板只能添加到文字轨道上
2）添加到轨道上后，可以通过拉伸文字图层修改长度
### **6.贴图**
除了贴图之外还有标注,包括箭头、图形（三角、圆等）、叹号、问号等，箭头可以通过鼠标在播放器修改方向和大小。
### **7.提供商店功能**
除了程序默认提供的滤镜、转场、文字、贴图效果之外，还可以通过点击「商店」无网站购买其他效果。
### **8.播放器**
提供宽高比设置：除了默认的16：9、4：3、1：1等，还可以进行自定义，自定义时提供分辨率和宽高比的修改。
### **9.时间线工具栏**
1）将undo、redo按钮，放置在了该工具栏
2）旋转功能：可将选中的clip旋转90度，旋转后任意方向都不会被裁剪
3）裁剪功能：通过调整播放器中裁剪框的大小，进行裁剪，同时可以旋转图片的角度，从-45度到45度
4）颜色调整：
自动调整: 提供4中自动调整模板，自动设置对比度、自动饱和、自动白平衡、魔术增强；
手动调整：修改亮度、对比度、饱和度、突出显示、Gamma、阴影、色调、色温、淡色参数
5）录音功能：主要作用是录制旁白，
点击「开始录制」，从游标位置开始，会在音频轨道上生成一段clip，clip的长度随着时间增加而增长
### **10.轨道和轨道操作**
1)  轨道分为片头轨、重叠轨、视频轨、音频轨
2）片头轨只能放置文字图层、贴图、标注，不能放视频、音频、图片
3）重叠轨、片头轨、音频轨一个轨道可以放置多排clip
4）除了主视频轨道，其他轨道的轨道头上有「关联曲目」功能，关联曲目后，移动与之关联的主视频轨道上的clip时，文字图层、音频、重叠轨上的clip也跟着移动。
4) 不仅能对一整个轨道上的clip进行隐藏，还可以对轨道上单个clip进行隐藏
5) 轨道支持多选, 支持冻结帧功能、支持视频分离音频，但分离音频后不支持合并音频
6）鼠标缩放轨道必须按住command键，不支持快捷键删除clip
7）音轨上的音频clip可以通过在任意位置添加音节点（类似关键帧的作用）,可以调节音频任意位置音量的大小
8）音频显示波形，具有自动检测音频节拍功能
9）右击轨道上的clip，具有「在文件夹显示」功能
### **11.视频导出**
1）视频导出时，不仅显示进度，还会显示所用时间，以及剩余时间
2）导出完成后，会弹窗提示是否打开导出文件，点击确定会在访达中直接显示
3)  导出格式：除了视频、音频、设备之外，还支持分享功能
4）导出速度比较快，
同样一段视频，都添加了模糊滤镜，moviemator未修改参数，导出分辨率为2160*2160，Movavi导出完成时，MovieMator只导出了21%

### **总结:**

1.导出速度快
2.自动释放内存，轨道操作很长时间，内存消耗增大，当删除轨道上所有的内容时，会自动释放大部分内存
3.界面简洁，模块区域划分为资源库、播放器和时间轴，与喵影工厂类似
4.时间线操作复杂，容易导致视频混乱
5.资源库不显示导入的文件资源，使用不方便

**Comment by hpuzj** [comment]
### **菜单栏**
1. 主页：主要显示常用的功能、例如打开文件，保存工程，导出视频，添加文件、对象、文字、标题，添加滤镜，转场，删除，undo、redo，字幕等等
1）添加对象包括：
添加简单的文字：文字需要自己在弹出的文字编辑窗口输入
添加动画标题
添加空白背景
添加覆盖图像：直接覆盖到除V1轨道外其他的轨道上。
2）添加字幕
在添加字幕窗口，通过调节“【 】”位置，来确定字幕的时长
字幕在画面中的位置、字体大小、字体格式等都可以调节
每添加一段字幕就需要点击一次add按钮，继续添加下一段字幕
2. clips:  添加文件、文字和空白背景、为资源库添加文件夹等等
3. 序列：主要功能是为时间线添加新的序列
4. Audio:  添加文件、CD、添加各种音效、文字转换成语音
1）音效需要下载，给出的音效非常多，例如警报、动物、自然、喜剧、枪等等二十几种音效，每种音效下又分为很多种。
2）文字转换成语音：该功能需要自己输入文字，目前不支持中文转换成语音
5.导出:
1）支持导出为DVD、蓝光、设备、无损输出、3D视频等等
2）支持分享到网站：youtube、facebook、 Flickr、Dropbox  Google drive网站
### **资源库**
1. 只显示文件，文件的显示分为两种显示方式,缩略图显示和列表显示。
2. 将资源库某个文件添加到轨道上时，会在文件缩略图上显示一个绿色的“√”，用以区分哪些clip添加到了轨道上。
3. 支持新建文件夹功能，可用来存放制作某一个工程文件时，使用的所有图片、视频、音频资源。
4. 资源库文件可直接添加视频或音频滤镜
### **视频滤镜**
1.鼠标放在视频缩略图上时，缩略图显示为动画模式
2.滤镜支持关键帧功能
3.添加滤镜后会弹出独立的编辑窗口，可参数修改添加关键帧，关键帧显示状态类似Pr,
4.关键帧位置可上下左右移动
5.关键帧位置的游标与剪辑预览播放器游标相对应

### **播放器**
播放器两种预览显示模式，剪辑预览和序列预览
1. 剪辑预览: 
1）用来预览和剪辑资源库文件以及轨道上选中的单个clip
2）开始和结束功能：可通过拉伸“[ ]”，调节clip的长度
3）view 功能：预览轨道的clip时可选择3种预览方式，预览选中clip、预览选中clip+背景、预览序列
4）unlink和relink功能：分离音频、重新链接
2. 序列预览: 对轨道上的序列进行预览，既一个序列里轨道所有的clip
3. 切分功能
切分选中的clip、切分所有轨道上的clip、只切分视频轨道、切分音频轨道、可以选择切分任意轨道
4. 具有快照功能，截取的图片可直接在资源库显示
5. 360全景功能：直接将视频转换成全景视频

### **时间线及轨道操作**
1.轨道clip有两种展现形式：时间线和故事版
2.添加多个clip到轨道上，clip之间会自动添加转场标识，单击标识，弹出添加转场窗口可为clip添加转场
3.每个视频轨道的第一个文件开始位置，自动显示「fade in」标识，单击可修改淡入时间
4.每段clip上会显示FX标识，单击可为clip添加视频滤镜效果，音轨添加音频clip
5.可在时间轴上添加新的序列，保存工程时保存在同一个工程里，序列与序列之间互不影响
6. 支持音频分离功能
7.音轨上的clip，可调节音量大小以及左右耳声道

总结：
1. 软件的布局偏复杂，不容易上手
2.将绝大部分功能按钮集中在界面顶部的菜单栏，使用不习惯
3.界面同一个地方，两种预览方式剪辑预览和序列预览，对于不熟悉的用户容易混淆
4.添加滤镜、字幕、添加文字等等都是以独立窗口的形式展现

**Comment by pisceshsu** [comment]
### VideoPad Video Editor
### 资源管理器
有操作提示, Click ‘Add File(s)’ or drag and drop files here
三种资源分类，Video files, Audio files, Images

### 工具栏
1.有6个分类， Home, Clips, Sequence, Audio, Export, Custom
2.每个分类有对应的操作按钮
3.主要的按钮有：添加文字，黑场资源，带动画的标题，字幕，视频滤镜，音频滤镜，转场，undo/redo

### 播放器
1.片段预览，
   -- 可粗剪，截图，旋转, 
   -- 裁减后，通过按钮添加到时间线
   
2.整体预览
   -- 预览整个工程
   -- 播放/暂停， 
   -- 上/下一帧
   -- 上/下一个clip的edge
   -- 最开始/末尾


### 时间线Timeline
1.轨道可折叠
2.三种轨道
   -- Video Track, 可放置图片，视频
   -- Audio Track，可放置音频，加到video track的视频会把音频自动显示在audio track
   -- Video Track Overlay，可放置字幕，图片，视频
3.视频拖入时间后，图像和声音被自动放在了VideoTrack1和AudioTrack1,  VideoTrak2和AudioTrack2
   缺点：VideoTrack2不与AudioTrack2相邻，中间隔了VideoTrack1和AudioTrack2，
4.clip右键菜单“Change clip file”,可以直接从finder替换新的同类文件

### 转场
有两种模式
1.前后两个clip长度不变，
2.clip长度变短

   
### 故事板Storyboard
1.没有了时间线，显示的只有Video Track1和Audio Track1的信息，看不到Video Track2和AudioTrack2
2.显示每个clp的第一帧缩略图，时长，音频波形，
3.可修改转场，滤镜，音量
  
### 导出
1.Video file
2.Lossless Video
3.3D Video file
4.Portable Video(iphone各代机型，android, psp, etc)
5.Blu-ray(Blu-ray Data Disk, Blu-ray Movie Disk)
6.DVD
7.Image Sequence
8.Social Media（Youtube, Facebook, Flickr）
9.Dropbox
10.Google Drive
 

总结：
1.界面布局重点不突出，布局不太合理，整体给人一种比较乱的感觉
2.时间线模式，不能任意添加轨道，
3.时间线模式，图像和音频分离，但VideoTrack2和AudioTrack2不相邻，
4.导出种类多，还包含3D Video, Blu-ray，

**Comment by pisceshsu** [comment]
### 总结 - MovieMator可借鉴的功能

### 资源管理器
1.无文件时，操作提示
2.视频/音频/文字模板后续支持在线下载功能
3.隐藏右上角属性窗口
4.增加一些好的背景音乐模板


### 时间线
1.音频轨道显示波形图
2.尽可能多的显示缩略图，帮助用户快速定位, 有一种标记的作用
3.增加标记功能
4.增加“在文件夹中显示”功能，快速定位clip在电脑中的路径
5.可调整轨道高度，方便多轨道时，针对一个轨道进行放大编辑，缩略图可以看到更清楚，波形图也可以看到更细致


### 过渡
MovieMator，缩短Clip长度，感觉比MOVAVI, VIDEOPAD更好理解


### 导出
1.增加GIF, 3D video输出
2.增加中国几个大的视频网站的输出，如，bilibili，iqiyi, youku，抖音等等
