### ISSUE TITLE
2.7.0 跟测  左上角的视频滤镜和音频滤镜无名称(如图)

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#534]
![屏幕快照 2019-07-15 下午2 04 04](https://user-images.githubusercontent.com/48675877/61197871-a8337680-a709-11e9-9f54-8f1ec86e1ff5.png)

**Comment by Dragon-S** [comment]
此问题实在mac上出现，主要是由于文件命名及翻译js文件的滤镜错误造成

**Comment by hpuzj** [comment]
跟测完成。
视频、音频滤镜的名称已经显示。
Mac系统显示的名称文字太小，在#511中提过文字太小的根测结果，此处不再重复提交。
