### ISSUE TITLE
还存在部分滤镜添加后需要undo多次才能撤销

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#539]
添加后需要undo多次才能撤销的问题基本解决，还有以下四个滤镜需要再修改一下：
1.添加后，需要undo2次
（1）叠加
（2）Rutt-Etra-lzer
（3）视频淡出
2.添加后，需要undo5次才能删除
（1）3D文字

**Comment by fuyunhuaxin** [comment]
基本都是滤镜的 in和out参数初始化引起的。现在改为直接调用filter的setInAndOut函数设置，这个函数不push命令。
