### ISSUE TITLE
左上角的Text资源tab图标，使用的是“贴图”tab的图标，且Text未翻译

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#540]
目前该位置使用的图片，应该改为与“贴图”“视频滤镜”等同样的格式
![屏幕快照 2019-07-15 下午3 05 25](https://user-images.githubusercontent.com/48675877/61199877-2431bc80-a712-11e9-84d3-8bfaaef9b716.png)

**Comment by pisceshsu** [comment]
已在  https://github.com/hansewu/MovieMator/issues/547  处理
