### ISSUE TITLE
切换到资源播放后，再切换回时间线播放。时间线指针不动。

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#541]

**Comment by WanYuanCN** [comment]
由之前修改的“预览滤镜后，再添加滤镜，右上角滤镜列表只会选中第一个滤镜”引起的。从资源列表切到时间线没有刷新时间线上的clip，导致游标不会移动。

**Comment by WanYuanCN** [comment]
游标不会移动和滤镜预览后再添加会选中第一个滤镜都已改好。
