### ISSUE TITLE
通过拖拽向轨道clip添加滤镜，松开鼠标时滤镜的缩略图不应该再向左上角回弹

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#542]
Mac系统
拖拽滤镜时，滤镜缩略图向左上角回弹会被认为是没添上。（实际滤镜已经添加上了）
![回弹1](https://user-images.githubusercontent.com/48675877/61274819-23b32780-a7df-11e9-9339-9cf41f03f8b4.gif)

**Comment by hpuzj** [comment]
https://github.com/hansewu/MovieMator/issues/631

**Comment by WanYuanCN** [comment]
Mac下目标区域禁止拖放也就是拖放失败会有这个回弹效果；在拖放并成功添加滤镜后使用
drop.acceptProposedAction()
表示对象可以拖拽到目标区域上，就不会有回弹效果了。

**Comment by hpuzj** [comment]
跟测完成
滤镜添加成功，无缩略图回弹问题
滤镜添加到空白轨道上时（滤镜添加失败），才会有回弹
