### ISSUE TITLE
文件列表中添加黑场资源

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#546]

**Comment by WanYuanCN** [comment]
生成了4个黑场视频（黑底、白底、绿底、蓝底）

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/61599652-9a2bab80-ac5d-11e9-9124-f44fa81a18c4.png)
黑场视频

**Comment by hpuzj** [comment]
跟测结果：
1.名称0X000000ff等，应该改为与背景视频匹配的名称
2.资源库视频或音频等Remove all的时候，背景视频也被删除

**Comment by hpuzj** [comment]
8.12日跟测完成
1.缩略图名称已修改
2.Remove all的时候，背景视频不会被删除
