### ISSUE TITLE
文字模版Dock图标、缩略图资源替换，翻译处理

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#547]

**Comment by WanYuanCN** [comment]
tab图标已替换更新

**Comment by Dragon-S** [comment]
更新文字dock缩略图

**Comment by Dragon-S** [comment]
![捕获](https://user-images.githubusercontent.com/36149358/61600515-926f0580-ac63-11e9-9503-a4c364a93ecf.PNG)

**Comment by hpuzj** [comment]
跟测结果：
1.文字图标处的Text未翻译
![屏幕快照 2019-07-26 下午4 34 05](https://user-images.githubusercontent.com/48675877/61938283-4d303800-afc3-11e9-9c62-bb06f7c2f8e8.png)
2. 文字模板缩略图偏大https://github.com/hansewu/MovieMator/issues/577
3. 文字标题需要问题 https://github.com/hansewu/MovieMator/issues/575
