### ISSUE TITLE
视频/音频滤镜、贴图、文字模板，缩略图下对应的文字太小（如图）

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#550]
Mac系统
文件：
![屏幕快照 2019-07-16 上午11 07 07](https://user-images.githubusercontent.com/48675877/61263171-88a85680-a7ba-11e9-8930-91c4f2818fe7.png)
音频滤镜：
![屏幕快照 2019-07-16 上午11 07 19](https://user-images.githubusercontent.com/48675877/61263178-91992800-a7ba-11e9-94a5-1dfb43db2330.png)
视频滤镜：
![屏幕快照 2019-07-16 上午11 07 30](https://user-images.githubusercontent.com/48675877/61263194-9eb61700-a7ba-11e9-8f7d-1d2c776a2b3f.png)
贴图：
![屏幕快照 2019-07-16 上午11 07 38](https://user-images.githubusercontent.com/48675877/61263208-a7a6e880-a7ba-11e9-8148-163f0cb64e00.png)
文字模板：
![屏幕快照 2019-07-16 上午11 07 52](https://user-images.githubusercontent.com/48675877/61263216-ad9cc980-a7ba-11e9-9919-95084d064e95.png)

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
Mac上设置字体大小为8号后，看上去特别小，正常大小的话需要设置为13号，而13号在Windows下又很大，但是如果设为默认大小也就是不显示设置字号的话，Mac和Windows上的文字看上去效果都比较好。
