### ISSUE TITLE
将文字模板添加到轨道上，文字模板的名称不要用*.png来表示

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#559]
如果用*.png命名，都不知道自己添加的哪个模板，最好显示文字模板的名称

![屏幕快照 2019-07-17 上午10 43 08](https://user-images.githubusercontent.com/48675877/61343332-ef437800-a87f-11e9-8cf4-3c87317456a1.png)

**Comment by Dragon-S** [comment]
#631

**Comment by Dragon-S** [comment]
解决方法：
在模板producer中加入模板名字属性，在显示的时候解析出来，重置clip名字为模板名字。

代码已提交，待审核

**Comment by Dragon-S** [comment]
讨论后，确定不手动在模板producer中添加属性，而是直接修改模板文件，在其中添加"moviemator:textTemplateName"这个属性。

**Comment by Dragon-S** [comment]
现有producer已经有一个扩展名属性，而其在时间线上显示的时候，首先判断的就是是否存在此扩展名，如果有就显示，因此在producer中添加"moviemator:textTemplateName"，直接修改xml文件即可。

**Comment by hpuzj** [comment]
跟测结果
文字模板添加到轨道到，显示的名称已经修改为文字模板名称。
