### ISSUE TITLE
鼠标放置在文件、视频滤镜、音频滤镜、贴图、文字模板的缩略图上时，显示的注释为灰底黑字，看不清文字

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#562]
Mac 10.14系统

![屏幕快照 2019-07-17 下午4 41 13](https://user-images.githubusercontent.com/48675877/61361002-30ed1680-a8b2-11e9-93e8-76d60a33d317.png)

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
Mac下ToolTip的背景色受到了ScrollArea的影响，导致和ScrollArea的背景色一样，单独设置了tooltip的背景样式。

**Comment by hpuzj** [comment]
跟测完成
目前已更改为白底黑字，可以看清文字内容。
