### ISSUE TITLE
添加滤镜后未修改参数，undo次数不对

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#57]
### **问题描述:**

添加滤镜后，不修改参数，点击undo，滤镜并未撤销而是滤镜参数发生变化，导致undo与redo次数不一致。不同滤镜，撤销次数也不相同。 文字、3D文字、Rutt-etra-lzer滤镜需要点6、7次undo，才能撤销滤镜;色彩分级需要撤销16次;添加镜像滤镜，点击一下“撤销”，图像直接显示为左右对称的图像效果。
### **来源：**
Mac测试

**Comment by pisceshsu** [comment]
2.6.4 已解决
