### ISSUE TITLE
2.6.3 自测：动画贴图拖到时间线上动画不起作用

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#571]
滤镜设置了动画，保存工程，再打开也有该问题

**Comment by vgawen** [comment]
滤镜时间不对，引起的问题，一是从string生成animation对象，从animation到string 都会有问题，流程还没理解清楚。

**Comment by pisceshsu** [comment]
2019.7.26 跟测完成
切换动画后，可以正常预览
