### ISSUE TITLE
文字模板缩略图偏大

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#577]
Mac系统：
与Windows系统比较，Mac缩略图显示比Windows显示要大一些（Windows感觉正好）
会导致资源库界面右侧在默认窗口大小下，显示空白
![屏幕快照 2019-08-01 下午3 49 54](https://user-images.githubusercontent.com/48675877/62275342-52363100-b474-11e9-89eb-261febaf8bd1.png)

文字模板缩略图：
![屏幕快照 2019-07-20 下午2 49 57](https://user-images.githubusercontent.com/48675877/61575383-b57fa500-aafd-11e9-8983-3bc3bdd8ea4c.png)

**Comment by Dragon-S** [comment]
#631

**Comment by hpuzj** [comment]
已修改
