### ISSUE TITLE
“色彩分级”滤镜问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#58]
### **问题描述：**
添加“色彩分级”滤镜时，显示的参数不是默认参数，阴影、中间调、高光参数全部在红色区域，全部恢复默认设置，预览时，阴影参数自动移动到红色区域。

### **来源：**
Mac0.1.2版本测试

**Comment by pisceshsu** [comment]
2.6.4 已重新设置滤镜参数
