### ISSUE TITLE
参考好的软件和网站，分析剪大师差距

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#582]
1、主要参考Procreate。其他的Aurora HDR等，再找2-3款好的软件和网站做参考。
2、分析差距，背景颜色、图标颜色、图标形状、选中处理、字体颜色、大小、粗细、亮度等方面进行对比分析。需要写分析报告文档。
3、根据分析结果制定剪大师改进方案

**Comment by vvyan** [comment]
[剪大师界面分析与参考20190725汪艳.pdf](https://github.com/hansewu/MovieMator/files/3430398/20190725.pdf)
