### ISSUE TITLE
剪大师界面设计修改

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#583]
要求达到参考目标的水平。

**Comment by vvyan** [comment]
![剪大师扁平化设计85](https://user-images.githubusercontent.com/37361188/62432317-9caffa00-b761-11e9-982c-f69ac5ba2a45.png)

**Comment by vgawen** [comment]
![剪大师扁平化设计893](https://user-images.githubusercontent.com/6801552/62819709-7936e600-bb8b-11e9-85a3-d832a04b6058.png)

**Comment by vvyan** [comment]
![剪大师扁平化设计817](https://user-images.githubusercontent.com/37361188/63659286-314acc80-c7e3-11e9-8af6-b1de27fa43f1.png)
![剪大师扁平化设计817控件2](https://user-images.githubusercontent.com/37361188/63659287-327bf980-c7e3-11e9-907e-36e966669555.png)
![剪大师扁平化设计817控件3](https://user-images.githubusercontent.com/37361188/63659288-327bf980-c7e3-11e9-9a32-fd9d2c289472.png)
![剪大师扁平化设计817控件4](https://user-images.githubusercontent.com/37361188/63659289-33149000-c7e3-11e9-9b81-0cd9e7090d9c.png)
![剪大师扁平化设计817控件5](https://user-images.githubusercontent.com/37361188/63659291-33149000-c7e3-11e9-8584-9fcd7006c1d3.png)
![剪大师扁平化设计817控件6](https://user-images.githubusercontent.com/37361188/63659292-33ad2680-c7e3-11e9-809d-0000a2030d72.png)
![剪大师扁平化设计817控件7](https://user-images.githubusercontent.com/37361188/63659294-33ad2680-c7e3-11e9-9525-72cfbddbe0e3.png)
![剪大师扁平化设计817控件8](https://user-images.githubusercontent.com/37361188/63659295-34de5380-c7e3-11e9-869d-f622d892a436.png)

**Comment by vvyan** [comment]
![剪大师扁平化设计830效果图](https://user-images.githubusercontent.com/37361188/64014992-1c10cd80-cb56-11e9-90a8-2871b1f60a48.png)
![剪大师扁平化设计830-1280*720](https://user-images.githubusercontent.com/37361188/64014993-1ca96400-cb56-11e9-87da-19ea6c525c64.png)
