### ISSUE TITLE
基于基类Dock实现文件Dock

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#592]

**Comment by WanYuanCN** [comment]
界面已能够显示，功能正在处理。

**Comment by WanYuanCN** [comment]
![图片](https://user-images.githubusercontent.com/44854531/61865753-5b6c4e80-af06-11e9-8943-7e80858b5a13.png)
文件Dock的界面及搜索过滤、添加、删除、右键等功能已经完成，接下来就是界面样式等修改；

**Comment by WanYuanCN** [comment]
功能细节、界面样式已修改，代码已提交，等待审核。

**Comment by Dragon-S** [comment]
代码已经初步审核，目前还存在问题，请完成修改后在继续提交。具体审核内容及建议见：
#618

**Comment by WanYuanCN** [comment]
代码已经优化了存在的问题，已提交审核。
