### ISSUE TITLE
学习剖面图绘制方法

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#596]
### 参考：
1.基于运行剖面的测试用例自动生成方法：
   https://www.ixueshu.com/document/7ff643913658301d.html  
2.基于AOP的操作剖面估算方法：
    https://www.doc88.com/p-2791068780628.html
3.有限状态图在图像界面软件可靠性测试操作剖面表示中的应用研究（内含记事本操作剖面绘制过程）
   https://www.doc88.com/p-1751663746090.html 
4.软件可靠性测试操作剖面构建方法研究及其应用
     https://www.doc88.com/p-0773881543156.html
5.软件可靠性工程中的操作剖面开发(内含客户剖面，用户剖面，系统模式剖面，功能剖面，操作剖面实例)
    https://www.doc88.com/p-8166979477889.html
6.操作剖面与软件可靠性(含操作剖面构造图和操作剖面实例)
    https://www.doc88.com/p-5147141300131.html
7.ATM软件可靠性操作剖面实验报告
   https://www.doc88.com/p-5147141300131.html 
(运行剖面参考)
8.基于运行剖面的测试用例选择改进算法(含运行剖面构造方法及实例)
   https://www.doc88.com/p-3015348157857.html 
9.软件可靠性操作剖面报告讲解：  
  https://wenku.baidu.com/view/2a28ea33f4335a8102d276a20029bd64783e620c.html

**Comment by pisceshsu** [comment]
### 软件可靠性
1.软件可靠性：是指在规定的条件下和规定的时间间隔内，软件系统能正确运行的概率。规定的条件包括环境、使用、维护和维修等条件和操作技术。规定的时间是指软件系统 的可靠性是相对一定的时间间隔而言的。 正确运行，是指系统具有规定的各项技术性能，完成规定任务，运行程序不被破坏或停止，程序按规定的要求运行，运行的结果正确，执行时间在规定限度范围内。

2.软件可靠性测试，是指在有代表性的使用环境中，使用有代表性的测试用例，在一个较长的时间内，对该软件系统进行的实际运行性的测试。 
目的：为了验证在给定的统计置信度下，软件当前的可靠性水平是否满足用户的需求而进行的测试。

3..可靠性测试方法
要有基于使用模型的统计测试（Markov 模型是最主要的使用模
型表达方式）和基于操作剖面的可靠性测试


### 剖面
1.分类：客户剖面，用户剖面，系统模式剖面，操作剖面，功能剖面，运行剖面


### 操作剖面
1.定义
1）是软件质量管理的概念，是操作的集合以及他们出现的概率
2) 将提供用户如何部署所建产品的信息，

2.从操作剖面图到测试用例的步骤：
系统-》剖面-》变量-》操作-》生成用例

3.运行剖面分析的构造过程
获取功能点的起点和终点-》提取操作点-》建立操作点之间的关系-》分配操作概率


4.使用剖面是在操作剖面的基础上添加时序和限制条件



### 运行剖面
1.在构造运行剖面时， 需要充分分析使用软件的各种模式和各种功能，分析完成这些功能相应的输入数据，同时要分析在使用软件时各种系统模式和功能发生的概率

2.构造软件的运行剖面的方法
- 按照层次结构， 自顶向下地把使用软件的输入空间划分为系统模式剖面，
- 把系统模式剖面划分为功能剖面，
- 再把功能剖面划分为运行剖面


3.步骤：
1).确定运行剖面的起点和终点，保证起点和终点的确定和实际软件的使用场景一致
2).操作点的提取，
   -- 一个功能点可以是一个操作，也可能包含若干个操作。
   -- 每一个操作点就是改软件实现过程中最基本的单位
   -- 如果操作点为有条件执行，还需要为操作点设置前置约束条件
   --   操作点的属性，操作名，前置约束，输入变量
3).为剖面建立使用关系，即操作点之间的转移关系
4).为操作点之间的转移关系分配概率，如何分配概率是一个重要的，也是有争议的问题
5). 研究表示剖面模型方法，
6). 通过自动化生产可靠性测试数据

**Comment by hpuzj** [comment]
### **软件的可靠性**
1. 软件可靠性测试的特点：
1）一定要在一段时间内连续运行。
2）测试用例一定要具有代表性
3）测试数据强调输入数据和使用环境
4）准确记录并分析结果
2.  软件可靠性参数度量: 初始故障数、剩余故障数、可靠度、失效概率、失效率、平均无失效时间、与平均失效间隔
3.  软件可靠性测试包括的环节：构建操作剖面、生成测试用例、测试执行、执行过程数据收集、可靠性评估

### **操作剖面**

1. 操作剖面是一个对系统使用的定量描述，包含对系统一系列操作的集合以及它们发生的概率。
2. Musa 操作剖面由5步构成：
  1） 构造客户剖面：来源软件开发过程的需求文档
  2）构造用户剖面：用户是具体使用软件产品的人
  3）构造系统模式剖面：描述用户使用软件的方法
  4）构造功能剖面：分析完成该系统模式所有的功能及其概率
  5）构造操作剖面：将操作执行划分为运行、确定输入空间、确定每个操作的发生概率
3. 运行剖面的分析构造过程：
1）需求确认：将系统的基本功能点和详细使用过程了解清楚
2）模式分析: 结合具体的使用情况进行分析，以获取功能点（将能够直接从软件文档中获得的最小功能命名为功能点）
3）运行剖面构造：用来描述软件的实际使用情况
  确定运行剖面的起点和终点
  操作点的提取，操作点的属性信息：包括操作名、前置约束、输入变量、每一个操作点的确立都是以这三个属性信息的确立为标志。
  为剖面建立使用关系，既操作点之间的转移关系
  分配操作概率：既主要操作点与次要操作点的概率分配

个人理解，以MovieMator添加滤镜为例：
操作名：添加视频滤镜
操作前置约束：轨道必须有被选中的clip
输入变量：添加方式（拖拽或点击右上角的“+”）、哪种滤镜
变量前置约束：轨道clip的分类，视频、音频或图片

4.前置约束条件处理
  1）变量前置条件约束
  2）操作前置条件约束
  3）时间约束，动作与动作之间的反应时间
5. 操作剖面中的状态属性;
状态名称：
状态描述
当前状态下可执行的操作
指向当前状态的操作
等待时间
界面信息
操作名称
操作描述
操作类型
操作前等待时间
操作后等待时间
操作隶属状态
操作指向的状态
动作列表
输入剖面
操作概率
