### ISSUE TITLE
clip添加滤镜后，参数调整界面，滤镜缩略图显示问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#61]
### **问题描述：**
V1轨道上clip多次切分后，为其中一段clip连续添加同一个滤镜，并为最后一个滤镜开启关键帧，再为其他clip添加滤镜时，只显示参数，不显示滤镜名。开启关键帧时会显示滤镜名。添加几个滤镜后，删除前面的滤镜，后面的滤镜缩略图不向前移动。
![3](https://user-images.githubusercontent.com/48675877/56187655-e4e1ca00-6055-11e9-932d-0ee65efffa73.png)
![4](https://user-images.githubusercontent.com/48675877/56187662-e8755100-6055-11e9-8b3e-f5b76a7b9378.png)

### **来源：**
Mac 0.2.1版本测试

**Comment by pisceshsu** [comment]
2.6.4 已解决
