### ISSUE TITLE
滤镜缺省参数机制修改详细设计方案

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#623]
执行人员：chenxing（fuyunhuaxin）
审核人员：gdb（vgawen）

**Comment by fuyunhuaxin** [comment]
所有mlt的滤镜参数在mlt代码当中写死的地方，几乎都是在滤镜的init函数里面，并且写死的值都是和yml文件当中的配置是完全一样的，而且只是在滤镜生成的时候用一次，由于我们的c++代码中生成滤镜之后会set一遍，所以这个问题对于我们的方案暂时没有影响。

**Comment by fuyunhuaxin** [comment]
[滤镜参数机制优化设计方案_陈兴_20190719.pdf](https://github.com/hansewu/MovieMator/files/3490979/_._20190719.pdf)

**Comment by fuyunhuaxin** [comment]
[滤镜参数机制优化设计方案_陈兴_20190719.pdf](https://github.com/hansewu/MovieMator/files/3495172/_._20190719.pdf)

**Comment by fuyunhuaxin** [comment]
[滤镜参数机制优化设计方案_陈兴_20190719.pdf](https://github.com/hansewu/MovieMator/files/3503876/_._20190719.pdf)

**Comment by vgawen** [comment]
确认
