### ISSUE TITLE
绘制视频教程加字幕场景操作剖面图

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#628]

**Comment by hpuzj** [comment]
[Uploading 视频教程 字幕场景.pdf…]()
目前为初步版本，下一步需要进行完善修改：
![屏幕快照 2019-08-01 下午5 08 11](https://user-images.githubusercontent.com/48675877/62280922-66cbf680-b47f-11e9-9a9e-1ab380c2b0d4.png)
![屏幕快照 2019-08-01 下午5 09 14](https://user-images.githubusercontent.com/48675877/62280934-6c294100-b47f-11e9-8dcb-2967519f9223.png)

**Comment by pisceshsu** [comment]
任务先取消，先完成一个场景的剖面图绘制
