### ISSUE TITLE
绘制MovieMator功能剖面图

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#629]

**Comment by pisceshsu** [comment]
要求：
1.先绘制正确的操作流程图
2.再计算每个操作的概率

**Comment by pisceshsu** [comment]
电子相册+背景音乐操作流程图：
![屏幕快照 2019-08-01 下午5 15 22](https://user-images.githubusercontent.com/6078647/62281688-cb3b8580-b480-11e9-9593-de54cf90932d.png)

**Comment by hpuzj** [comment]
初期流程图，待后面逐步完善：
思路：
1.因MovieMator的操作流程相对复杂一些，初期的思路是界面模块+操作流程+实际操作点
2.后期简化后为主流程+围绕主流程的所有操作点
![屏幕快照 2019-08-01 下午5 51 49](https://user-images.githubusercontent.com/48675877/62285435-29b83200-b488-11e9-8a54-a13ee2bf49d9.png)
![屏幕快照 2019-08-01 下午5 53 08](https://user-images.githubusercontent.com/48675877/62285469-3b013e80-b488-11e9-9f87-390f368d28b4.png)
![屏幕快照 2019-08-01 下午5 53 54](https://user-images.githubusercontent.com/48675877/62285515-54a28600-b488-11e9-8e47-06f3eb94b86b.png)

**Comment by pisceshsu** [comment]
功能剖面图，和软件需求规格书结合在一起了
