### ISSUE TITLE
滤镜参数显示问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#63]
### **问题描述;**
    1）为clip添加滤镜效果，如果首先添加旋转滤镜，此时缩放的默认参数是100% ;  若先添加其他滤镜再添加旋转滤镜，此时缩放的默认参数是200%
    2)旋转滤镜，“旋转”“缩放”参数的值显示不全，鼠标点击缩放的进度条，不显示百位，183.9%显示为83.9%。（旋转、锐化、裁剪、Rutt-Etra-Izer等都有该问题）

### **来源：**
Mac、Windows 0.1.9版本测试问题

**Comment by pisceshsu** [comment]
2.6.4 已解决
