### ISSUE TITLE
自测整理新资源dock存在的问题

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#630]

**Comment by WanYuanCN** [comment]
目前发现的问题：
1、分类名称：名称使用数字进行排序；
2、界面内容未翻译；
3、黑场视频拖放到时间线显示的名称不是文件名（blackvideo）而是资源名（0xffffffff）；
字幕文件也是，显示的是资源名不是字幕名；
4、拖放时鼠标的图标不是小缩略图而是item，这样放置到时间线上时看不清具体的位置；
5、是否允许删除黑场视频；
6、清除搜索后没有跳转到当前列表位置；
7、滤镜、text、贴图dock切换时排列有问题；
8、界面文字被遮挡；
9、界面风格不统一；
10、item上的添加按钮没有点击效果；

**Comment by Dragon-S** [comment]
#616
