### ISSUE TITLE
资源/视频滤镜dock分类名称使用数字进行排序

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#638]
资源/视频滤镜dock分类名称使用数字进行排序
![图片](https://user-images.githubusercontent.com/44854531/62178587-30598300-b37c-11e9-87e7-8089e99c2047.png)

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
QMap<QString, T>会自动根据 key值排序，也就是在dock中是根据 QString的值来排序的。有三种解决方案。
①使用std::map<QString, T, _Compare>，_Compare是map的排序根据，在这里重写可以让map按照自定义的规则进行排序；
②使用std::unordered_map<QString, T>，不会自动排序，比较方便；
③重写QString的比较规则，使用一个自定义的类继承自QString，重写 <：
class UnSortedString : public QString
{
public:
    explicit UnSortedString(QString str) : QString(str) {}
    bool operator <(const UnSortedString &other) const { return (*this != other); }
};
只需要把文件中的QMap<QString, T>改成 QMap<UnSortedString, T>即可。
方案①和②需要额外引用map和unordered_map头文件，并且使用了QMap的部分函数将不能使用，需要修改一些调用函数。

**Comment by WanYuanCN** [comment]
暂时不做修改，可能要修改QMap为其他容器；

**Comment by WanYuanCN** [comment]
由于各dock的翻译方式不一致，文本、动画、滤镜dock的排序目前没有处理，只是使用了新的map类；文件dock的排序取消了加数字的方式，可以按照我们给定的顺序进行排序。
