### ISSUE TITLE
拖放dock文件时鼠标的图标不是小缩略图而是item，这样放置到时间线上时看不清具体的位置

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#640]
拖放时鼠标的图标不是小缩略图而是item，这样放置到时间线上时看不清具体的位置
![图片](https://user-images.githubusercontent.com/44854531/62178717-a362f980-b37c-11e9-93a8-976fff258cfd.png)

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
已修改，代码还未提交；

**Comment by hpuzj** [comment]
跟测完成。
将文件拖动到轨道上时，显示的缩略图
![屏幕快照 2019-08-05 下午5 12 26](https://user-images.githubusercontent.com/48675877/62453123-41ebc200-b7a4-11e9-8c4c-02a3b0452e98.png)
