### ISSUE TITLE
资源Dock清除搜索后没有跳转到当前列表位置

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#642]
资源Dock清除搜索后没有跳转到当前列表位置
![图片](https://user-images.githubusercontent.com/44854531/62178808-f0df6680-b37c-11e9-8704-90aad9a44c35.png)

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
搜索框内容改变后通过下拉列表使 scrollview跳转到对应的分类列表的 y坐标位置，但是每次跳转到的 y坐标都是搜索框内容改变前的分类列表的 y坐标，导致不能跳转到对应的分类列表；但是手动点击下拉列表又可以正确跳转。目前的一种思路是启用一个定时器，在几十毫秒之后调用一次激活下拉列表序号的函数，相当于手动点一次下拉列表，毫秒数太长就会有一个界面刷新的效果。

**Comment by WanYuanCN** [comment]
目前还没找到部件y坐标不更新的原因，还需继续研究；

**Comment by Dragon-S** [comment]
通过用线程监听需要的wideget的y坐标，确实是各一段时间才会更新，但具体什么时候跟新，暂时没有找到方法。
目前找到一个函数resize，可以立即刷新dock中的widget，进行一次重绘，这样可以在resizeevent中得到刷新后的dock中各个widget的坐标。原理是仿制一次dock大小改变，触发resizeevent。此种处理方法要好于定时器，在不同的电脑上，更新widget坐标的时间可能不同，因此定时器的时间不好设置。
代码如下：
    //实现当搜索框中的关键此被清空时，依然能跳转到搜索前分类的位置
    //实际上可以直接调用onClassComboBoxActivated函数进行跳转：onClassComboBoxActivated(ui->comboBox_class->currentIndex());
    //但是由于在清除搜索框内容时，会不断的刷新可显示item（增加或者删除），更新需要一定的时间，但目前无法知道什么时候完成，
    //造成在直接调用onClassComboBoxActivated跳转时，dock中的widget位置还未刷新完成，从而跳转失败（之前的位置）
    //由于dock的resize操作可以立即重绘dock中的控件，因此目前模拟了一个dock resize的操作，先改变一个像素，然后在复原，主要用于触发resizeevent事件.进行立即重绘
    //备注：也尝试过定时器，用一个大约10毫秒的定时器也可解决此问题，但由于设备性能不同，刷新完成时间不好确定，定时器方法不可缺
    QSize originSize = size();
    resize(originSize.width() + 1, originSize.height());
    resize(originSize);
}

**Comment by Dragon-S** [comment]
代码已提交，待审核
