### ISSUE TITLE
滤镜、text、贴图dock切换时排列有问题

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#643]
滤镜、text、贴图dock切换时排列有问题，刚切换到dock时，dock显示的文件列表不完整；

**Comment by Dragon-S** [comment]
#631

**Comment by WanYuanCN** [comment]
已修改，代码还未提交

**Comment by hpuzj** [comment]
跟测结果。
文件、音视频滤镜、文字dock,首次进入时是两列显示，切换到贴图dock后为3列显示，且切换到贴图dock后，再切换到其他dock，均无法再两列显示。
原因是因为贴图界面标题太长，如果贴图界面缩略图两列显示，会遮挡贴图dock界面的标题文字。
