### ISSUE TITLE
贴图和文件dock界面标题栏风格不统一

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#645]
贴图和文件dock界面标题栏风格不统一
![图片](https://user-images.githubusercontent.com/44854531/62178901-36039880-b37d-11e9-82fe-490a71df7c03.png)
![图片](https://user-images.githubusercontent.com/44854531/62178909-40be2d80-b37d-11e9-854c-d402a1bc9046.png)

**Comment by Dragon-S** [comment]
#631

**Comment by hpuzj** [comment]
跟测完成。
贴图dock界面标题风格按照文件dock界面风格进行修改。
