### ISSUE TITLE
2.6.3 滤镜预览代码重构详细设计方案

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#647]
执行人员：fuyunhuaxin
审核人员：vgawen

问题：
1 新增滤镜预览 - 代码重复、参数不合理、放在maininterface不合适。
maininterface里面的定义的是通用接口，滤镜预览只是针对filterdock的，mlt文件的操作可以放在filterdock中，然后调用mainterface接口创建producer，播放。

2 滤镜参数设置代码
代码风格
设置缺省参数代码可以单独一个函数
拿到property为空就使用序号，加个说明，为什么这么处理
.html参数的处理也要加个说明，还要考虑下这么处理是否合理？还有没有其他类似的参数。

3 Undo redo测试代码
保存xml文件的代码，可以作为一个公用函数
m_originalXml，m_currentXml这两个获取的时候也应该用宏包起来。
现在测试实际上没有起到作用。应该先屏蔽掉。

问题1 需要写一下修改方案

**Comment by fuyunhuaxin** [comment]
[滤镜预览代码重构设计方案_陈兴_20190806.pdf](https://github.com/hansewu/MovieMator/files/3484307/_._20190806.pdf)

**Comment by fuyunhuaxin** [comment]
[滤镜预览代码重构设计方案_陈兴_20190806.pdf](https://github.com/hansewu/MovieMator/files/3484925/_._20190806.pdf)

**Comment by vgawen** [comment]
确认
