### ISSUE TITLE
拖放滤镜到时间线添加滤镜到非选中的clip上会添加到当前选中的clip上

### ISSUE THREAD

**Issue by WanYuanCN** [hansewu/MovieMator#651]
拖放滤镜到时间线添加滤镜到非选中的clip位置上会添加到当前选中的clip上
![图片](https://user-images.githubusercontent.com/44854531/62263783-08d3ea80-b450-11e9-8579-12a73faec8f7.png)
![图片](https://user-images.githubusercontent.com/44854531/62263801-138e7f80-b450-11e9-8504-3aa7e72339df.png)
![图片](https://user-images.githubusercontent.com/44854531/62263817-1d17e780-b450-11e9-8d0c-745e9a83d177.png)

**Comment by Dragon-S** [comment]
主要解决方法是：
当放下时如果clip未选中，怎先选中在添加滤镜
并且将光标跳到当前选中的clip上。

修改代码为qml，gdb完成初步审核，代码已提交

**Comment by hpuzj** [comment]
跟测完成
将滤镜拖放到轨道未选中状态的clip上，clip自动选中并添加滤镜
