### ISSUE TITLE
新dock界面优化

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#676]
（1）字体、字体大小（主要是mac上和windows不一致）
（2）翻译

**Comment by WanYuanCN** [comment]
Mac上设置字体大小为8号后，看上去特别小，正常大小的话需要设置为13号，而13号在Windows下又很大，但是如果设为默认大小也就是不显示设置字号的话，Mac和Windows上的文字看上去效果都比较好。

**Comment by WanYuanCN** [comment]
界面的 tr 翻译已完成
