### ISSUE TITLE
文字滤镜设置关键帧后，字间距，轮廓颜色/宽度，背景颜色/宽度 设置无效。

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#69]
### **问题描述：**
带动画的预设设置关键帧后，字间距，轮廓颜色/宽度，背景颜色/宽度 设置无效。
（2.5.5用户反馈：文本编辑功能有问题，框选关键帧后，文字颜⾊⽆法改变 ）

### **来源：**
测试和steam用户反馈

### **版本：**
Pro2.5.5

**Comment by hansewu** [comment]
和 https://github.com/hansewu/MovieMator/issues/197 类似
