### ISSUE TITLE
文字滤镜预设格式的中“从左侧渐入”问题

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#70]
### **问题描述：**
如果文字是从左侧渐入，那么文字的顺序应该是从右往左念，应该是“MovieMator to Welcome”，而不是“Welcome to MovieMator”，希望可以增加这种预设和字体方向的设置，允许文字垂直显示。
### **来源：**
steam用户反馈

**Comment by pisceshsu** [comment]
2.6.4 文字预设已更换，无该问题了
