### ISSUE TITLE
Win2.7.0 贴图，“氛围”和“边框"分类，贴图边框位置不对

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#704]
贴图 ，“边框”分类预览时图片不是显示在视频的边框，“氛围”也是一样（2.6.1自动配置，不知是进行了修改还是出错了）

**Comment by hpuzj** [comment]
跟测完成
目前将“边框”“氛围”贴图添加到轨道上后，贴图自动匹配播放器的大小
