### ISSUE TITLE
Mac 2.6.4 时间线工具栏“音量”按钮，点击后程序崩溃

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#712]
Mac 2.6.4 时间线工具栏“音量”按钮，点击后程序崩溃。 从音频滤镜资源里添加“音量”滤镜，不会崩溃

**Comment by fuyunhuaxin** [comment]
metadataForUniqueId("Volume");
以前时间线工具栏“音量”按钮添加音量滤镜时直接用“Volume”查找的。
而查找方式是：
if (!objectName().isEmpty()) {
        return objectName();
    } else {
        return mlt_service();
    }
有objectName就用objectName，没有的话就用mlt_service。
刚好之前该滤镜没有objectName，这次添加了，并且为"audioGainVolume"。所以就找不到了
