### ISSUE TITLE
Mac2.6.4 添加变换滤镜后，「大小模式」没有初始值，会导致鼠标拖动外框时，框和图像大小不一致

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#719]
Mac2.6.4 添加变换滤镜后，「大小模式」没有初始化值，会导致鼠标拖动外框时，框和图像大小不一致。

4种拉伸模式，没有选中状态

![屏幕快照 2019-08-17 上午8 40 48](https://user-images.githubusercontent.com/48675877/63204505-dfab8f00-c0ca-11e9-9190-042dbae49f62.png)

**Comment by fuyunhuaxin** [comment]
新的滤镜参数机制用上之后配置正确即可

**Comment by pisceshsu** [comment]
2019.9.3 跟测完成
已正确设置初始值
