### ISSUE TITLE
win 2.6.4 启动程序后，选择视频插入到轨道上，会在A2轨道下面的空白处（无轨道）自动生成名为V1的clip,点击崩溃

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#723]
启动程序，插入音频到音轨，会生成A1 clip，点击也崩溃。
重启程序后，空白处（无轨道）地方，自动生成的clip还在原来的位置。
![21566043146_ pic](https://user-images.githubusercontent.com/48675877/63211433-7dce4200-c129-11e9-9fb8-24b7ab750a1b.jpg)

**Comment by vgawen** [comment]
MultitrackModel 的m_nIndexOfSelectedClip 未初始化引起的
