### ISSUE TITLE
Win 2.6.4 文字滤镜添加后，需要undo2~3次才能删除

### ISSUE THREAD

**Issue by pisceshsu** [hansewu/MovieMator#724]
MacBook Pro WIN10, 文字滤镜添加后，默认字体是Verdana,  第一次undo，改变了文字大小，第二次undo字体变成了Sans, 第三次undo滤镜被删除；

HP Win7 需要undo两次，第一次undo，字体变成了Sans, 第二次undo滤镜被删除；

**Comment by vgawen** [comment]
Duplicate of #695

**Comment by pisceshsu** [comment]
跟测结果：已解决
