### ISSUE TITLE
win 10  2.6.4 ，安装时未遇到，但是点击「教程」遇到360拦截（公司电脑也未遇到，家里的电脑遇到的）

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#726]
每次点击「教程」按钮都会遇到

![31566095876_ pic](https://user-images.githubusercontent.com/48675877/63219563-b5c79a80-c1a6-11e9-9043-0ffa097f1c15.jpg)

**Comment by debelliszhu** [comment]
每更新一个版本，都需要提交360测试审核的。 一般需要1-3天。2.6.4版本刚刚通过了审核并在360管家上线。
