### ISSUE TITLE
音频淡入淡出问题

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#727]
I'm trying to use the audio fade out filter and no matter what I try I can't seem to get it to work. I have an audio track in the timeline and have it selected. I apply an "audio fade out filter" but no matter what duration I set in the properties it never seems to work and the time keeps resetting to zero. Can you help me please?

I've also tried adding both an audio fade in and fade out to no effect. I only seem to be able to get it to work at the start of an audio clip but never the end (Which is where you would most commonly use it). The duration number doesn't seem to tally up with the timeline number and this feature just seems broken in this build.

**Comment by pisceshsu** [comment]
关联issues: https://github.com/hansewu/MovieMator/issues/619

**Comment by debelliszhu** [comment]
I am using Win 10 Pro.

更多的用户反馈此问题了：
elihu0303@gmail.com:
Win10; The 'Fade In Audio' & 'Fade Out Audio' effects haven't been applied since a few days.
附上操作视频
['Fade In Audio' & 'Fade Out Audio' effects error vedio.mp4.zip](https://github.com/hansewu/MovieMator/files/3539765/Fade.In.Audio.Fade.Out.Audio.effects.error.vedio.mp4.zip)

zerokenshiro@gmail.com:
I have been using the MovieMator product  and I have been very impressed by its value. The Only thing I can't seem to make work is the Fade Out Audio Filter. The duration is always reset to 0 after i change it to a different value the and the fade out effect never seems to work. I am using version 2.6.4 and have reinstalled it twice already. This is true both in preview and in export mode.

**Comment by debelliszhu** [comment]
2.6.4版本

**Comment by vgawen** [comment]
相关issue #619  #567 #733

**Comment by fuyunhuaxin** [comment]
问题已经找到，是两个滤镜的gain和end参数没设置好所置的，之前在解决undo问题的时候去掉了，在新的滤镜参数机制设置好就可以了。刚好淡入淡出两个滤镜共用了一个mlt_service,需要拆分成两个。
