### ISSUE TITLE
2.6.4   修改其他滤镜参数后，再修改"视频淡出"滤镜参数，无淡出效果，且切换滤镜后，淡出滤镜参数变为默认值

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#733]
1.clip同时添加视频淡出滤镜+其他任意可修改参数的滤镜
2.先修改其他滤镜的参数，再修改视频淡出滤镜的参数
3.预览无淡出效果
4.在右上角，切换其他滤镜，再切换成视频淡出滤镜，参数还原成默认值
5.勾选视频淡出参数中的 Adjust opacity instead of fade with black,自动开启关键帧（淡入无该问题）

![shipindanchu](https://user-images.githubusercontent.com/48675877/63681430-5a418080-c828-11e9-9f79-75376b9161a1.gif)

**Comment by pisceshsu** [comment]
跟测完成，2.8.0回归测试1已解决
