### ISSUE TITLE
文字模板拉伸后，拉长部分不显示文字

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#754]
1.将文字模板添加到轨道上
2.使用鼠标拉伸文字模板后面的"]",使文字模板变长
3.预览时，拉伸部分不显示文字

1）添加文字模板，并修改文字
![屏幕快照 2019-08-30 下午2 25 21](https://user-images.githubusercontent.com/48675877/63997827-35078780-cb32-11e9-9379-22c7b11f514c.png)
2）模板拉伸后，被拉长部分不显示文字
![屏幕快照 2019-08-30 下午2 25 40](https://user-images.githubusercontent.com/48675877/63997849-4a7cb180-cb32-11e9-8a66-0fb063e25419.png)
3）移动模板位置后，关键帧标识自动跟踪，但拉长部分依旧不显示文字
![屏幕快照 2019-08-30 下午2 26 16](https://user-images.githubusercontent.com/48675877/63997887-6aac7080-cb32-11e9-971c-9197385b9e7f.png)

**Comment by Dragon-S** [comment]
主要原因是，在拉长后对producer上的滤镜的in、out未更新造成，滤镜作用时长还是原来的。代码如下：
        // Adjust all filters that have an explicit duration.
        int n = info->producer->filter_count();
        for (int j = 0; j < n; j++) {
            Mlt::Filter* filter = info->producer->filter(j);
            if (filter && filter->is_valid() && filter->get_length() > 0) {
                if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeOut")
                        || QString(filter->get("mlt_service")) == "webvfx")
                {
                    filter->set_in_and_out(out - filter->get_length() + 1, out);
                }
            }
            delete filter;
        }

目前的代码只是最webvfx和fadeout作业处理，其他滤镜都没有重新设置in、out

**Comment by Dragon-S** [comment]
> 
> 
> 主要原因是，在拉长后对producer上的滤镜的in、out未更新造成，滤镜作用时长还是原来的。代码如下：
> // Adjust all filters that have an explicit duration.
> int n = info->producer->filter_count();
> for (int j = 0; j < n; j++) {
> Mlt::Filter* filter = info->producer->filter(j);
> if (filter && filter->is_valid() && filter->get_length() > 0) {
> if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeOut")
> || QString(filter->get("mlt_service")) == "webvfx")
> {
> filter->set_in_and_out(out - filter->get_length() + 1, out);
> }
> }
> delete filter;
> }
> 
> 目前的代码只是最webvfx和fadeout作业处理，其他滤镜都没有重新设置in、out

上述条件去掉后设置text filter的out值，也同样是不行的，因为底层代码中，有重新将原来的值设置回来了，目前还没弄懂原因

int get_length_for_filter(mlt_properties self, int in_length, int *out_length, int *out_frame_in)
{
//	return length;
//	比较难获得filter对应的producer
//	if(length > 0)  return length;

	char *mlt_type = mlt_properties_get( self, "mlt_type" );
	if ( strcmp( mlt_type, "filter" ) != 0)
	{
		*out_length = in_length;
		return -1;
	}

	mlt_service producer_service = (mlt_service)mlt_properties_get_data( self, "service", NULL );
	if(!producer_service)  
	{
		*out_length = in_length;
		return -1;
	}

	mlt_playlist playlist = (mlt_playlist)mlt_properties_get_data(MLT_SERVICE_PROPERTIES(producer_service), "__ef_playlist", NULL);
	if(playlist)
	{
		mlt_properties_set_data(self, "__ef_service_at_track",  producer_service, 0, NULL, NULL);
		mlt_properties_set_data(self, "__ef_playlist",  playlist, 0, NULL, NULL);
	}
	else
	{
		mlt_service service_at_track = (mlt_service)mlt_properties_get_data( self, "__ef_service_at_track", NULL );
		if(service_at_track)  
		{
			producer_service = service_at_track;
		}
	}
	
	mlt_properties producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
	if(!producer_properties) 	{
		*out_length = in_length;
		return -1;
	}

	char *filter_name = mlt_properties_get( self, "mlt_service" );

	if(strcmp(filter_name, "dynamictext")==0)
	{
	//	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter properties");
	//	mlt_properties_debug( self, "filter_properties", stderr );
	//	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties");
	//	mlt_properties_debug( producer_properties, "producer_properties", stderr );
	//	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter length = %d\n", length);
	}
	else 	
	{
		*out_length = in_length;
		return -1;
	} 

	mlt_position pos_in=0, pos_out=0;
	if(mlt_producer_frame_pos(producer_service, &pos_in, &pos_out) == 0)
	{
		//mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter]  producer at track length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
		*out_frame_in = pos_in;
		*out_length = pos_out - pos_in +1;
		return 0;
	}

	pos_in 	= mlt_properties_get_position( producer_properties, "in" );
	pos_out 	= mlt_properties_get_position( producer_properties, "out" );


	//if(mlt_properties_get_int( producer_properties , "_cut" )) //比较奇怪, 对应的_cut_child 才有 "_cut"
	{
		mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties cut");
        mlt_producer parent =  (mlt_producer)mlt_properties_get_data( producer_properties, "_cut_child", NULL);//"_cut_parent", NULL );
		if(parent)
		{
			producer_service = MLT_PRODUCER_SERVICE(parent);
			producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
			//mlt_properties_debug( producer_properties, "producer_properties", stderr );
		}
	}
	
	pos_in 	= mlt_properties_get_position( producer_properties, "in" );
	pos_out 	= mlt_properties_get_position( producer_properties, "out" );

	if(strcmp(filter_name, "dynamictext")==0)
	{
		mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
	}  

	if(pos_out > 0)
	{
		if(strcmp(filter_name, "dynamictext")==0)
		{
			 **### mlt_properties_set_position( self, "in", pos_in );
			 mlt_properties_set_position( self, "out", pos_out );**
		}
		*out_frame_in = pos_in;
		*out_length = pos_out - pos_in +1;
		return 0;
	} 
	*out_length = 0;
	return -1;
	
}

**Comment by Dragon-S** [comment]
> 
> 
> > 主要原因是，在拉长后对producer上的滤镜的in、out未更新造成，滤镜作用时长还是原来的。代码如下：
> > // Adjust all filters that have an explicit duration.
> > int n = info->producer->filter_count();
> > for (int j = 0; j < n; j++) {
> > Mlt::Filter* filter = info->producer->filter(j);
> > if (filter && filter->is_valid() && filter->get_length() > 0) {
> > if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeOut")
> > || QString(filter->get("mlt_service")) == "webvfx")
> > {
> > filter->set_in_and_out(out - filter->get_length() + 1, out);
> > }
> > }
> > delete filter;
> > }
> > 目前的代码只是最webvfx和fadeout作业处理，其他滤镜都没有重新设置in、out
> 
> 上述条件去掉后设置text filter的out值，也同样是不行的，因为底层代码中，有重新将原来的值设置回来了，目前还没弄懂原因
> 
> int get_length_for_filter(mlt_properties self, int in_length, int *out_length, int *out_frame_in)
> {
> // return length;
> // 比较难获得filter对应的producer
> // if(length > 0) return length;
> 
> ```
> char *mlt_type = mlt_properties_get( self, "mlt_type" );
> if ( strcmp( mlt_type, "filter" ) != 0)
> {
> 	*out_length = in_length;
> 	return -1;
> }
> 
> mlt_service producer_service = (mlt_service)mlt_properties_get_data( self, "service", NULL );
> if(!producer_service)  
> {
> 	*out_length = in_length;
> 	return -1;
> }
> 
> mlt_playlist playlist = (mlt_playlist)mlt_properties_get_data(MLT_SERVICE_PROPERTIES(producer_service), "__ef_playlist", NULL);
> if(playlist)
> {
> 	mlt_properties_set_data(self, "__ef_service_at_track",  producer_service, 0, NULL, NULL);
> 	mlt_properties_set_data(self, "__ef_playlist",  playlist, 0, NULL, NULL);
> }
> else
> {
> 	mlt_service service_at_track = (mlt_service)mlt_properties_get_data( self, "__ef_service_at_track", NULL );
> 	if(service_at_track)  
> 	{
> 		producer_service = service_at_track;
> 	}
> }
> 
> mlt_properties producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
> if(!producer_properties) 	{
> 	*out_length = in_length;
> 	return -1;
> }
> 
> char *filter_name = mlt_properties_get( self, "mlt_service" );
> 
> if(strcmp(filter_name, "dynamictext")==0)
> {
> //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter properties");
> //	mlt_properties_debug( self, "filter_properties", stderr );
> //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties");
> //	mlt_properties_debug( producer_properties, "producer_properties", stderr );
> //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter length = %d\n", length);
> }
> else 	
> {
> 	*out_length = in_length;
> 	return -1;
> } 
> 
> mlt_position pos_in=0, pos_out=0;
> if(mlt_producer_frame_pos(producer_service, &pos_in, &pos_out) == 0)
> {
> 	//mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter]  producer at track length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
> 	*out_frame_in = pos_in;
> 	*out_length = pos_out - pos_in +1;
> 	return 0;
> }
> 
> pos_in 	= mlt_properties_get_position( producer_properties, "in" );
> pos_out 	= mlt_properties_get_position( producer_properties, "out" );
> 
> 
> //if(mlt_properties_get_int( producer_properties , "_cut" )) //比较奇怪, 对应的_cut_child 才有 "_cut"
> {
> 	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties cut");
>     mlt_producer parent =  (mlt_producer)mlt_properties_get_data( producer_properties, "_cut_child", NULL);//"_cut_parent", NULL );
> 	if(parent)
> 	{
> 		producer_service = MLT_PRODUCER_SERVICE(parent);
> 		producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
> 		//mlt_properties_debug( producer_properties, "producer_properties", stderr );
> 	}
> }
> 
> pos_in 	= mlt_properties_get_position( producer_properties, "in" );
> pos_out 	= mlt_properties_get_position( producer_properties, "out" );
> 
> if(strcmp(filter_name, "dynamictext")==0)
> {
> 	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
> }  
> 
> if(pos_out > 0)
> {
> 	if(strcmp(filter_name, "dynamictext")==0)
> 	{
> 		 **### mlt_properties_set_position( self, "in", pos_in );
> 		 mlt_properties_set_position( self, "out", pos_out );**
> 	}
> 	*out_frame_in = pos_in;
> 	*out_length = pos_out - pos_in +1;
> 	return 0;
> } 
> *out_length = 0;
> return -1;
> ```
> 
> }


pos_in 	= mlt_properties_get_position( producer_properties, "in" );
pos_out 	= mlt_properties_get_position( producer_properties, "out" );
得到的是旧的out值，还未弄清楚原因

**Comment by Dragon-S** [comment]
> 
> 
> > > 主要原因是，在拉长后对producer上的滤镜的in、out未更新造成，滤镜作用时长还是原来的。代码如下：
> > > // Adjust all filters that have an explicit duration.
> > > int n = info->producer->filter_count();
> > > for (int j = 0; j < n; j++) {
> > > Mlt::Filter* filter = info->producer->filter(j);
> > > if (filter && filter->is_valid() && filter->get_length() > 0) {
> > > if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeOut")
> > > || QString(filter->get("mlt_service")) == "webvfx")
> > > {
> > > filter->set_in_and_out(out - filter->get_length() + 1, out);
> > > }
> > > }
> > > delete filter;
> > > }
> > > 目前的代码只是最webvfx和fadeout作业处理，其他滤镜都没有重新设置in、out
> > 
> > 
> > 上述条件去掉后设置text filter的out值，也同样是不行的，因为底层代码中，有重新将原来的值设置回来了，目前还没弄懂原因
> > int get_length_for_filter(mlt_properties self, int in_length, int *out_length, int *out_frame_in)
> > {
> > // return length;
> > // 比较难获得filter对应的producer
> > // if(length > 0) return length;
> > ```
> > char *mlt_type = mlt_properties_get( self, "mlt_type" );
> > if ( strcmp( mlt_type, "filter" ) != 0)
> > {
> > 	*out_length = in_length;
> > 	return -1;
> > }
> > 
> > mlt_service producer_service = (mlt_service)mlt_properties_get_data( self, "service", NULL );
> > if(!producer_service)  
> > {
> > 	*out_length = in_length;
> > 	return -1;
> > }
> > 
> > mlt_playlist playlist = (mlt_playlist)mlt_properties_get_data(MLT_SERVICE_PROPERTIES(producer_service), "__ef_playlist", NULL);
> > if(playlist)
> > {
> > 	mlt_properties_set_data(self, "__ef_service_at_track",  producer_service, 0, NULL, NULL);
> > 	mlt_properties_set_data(self, "__ef_playlist",  playlist, 0, NULL, NULL);
> > }
> > else
> > {
> > 	mlt_service service_at_track = (mlt_service)mlt_properties_get_data( self, "__ef_service_at_track", NULL );
> > 	if(service_at_track)  
> > 	{
> > 		producer_service = service_at_track;
> > 	}
> > }
> > 
> > mlt_properties producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
> > if(!producer_properties) 	{
> > 	*out_length = in_length;
> > 	return -1;
> > }
> > 
> > char *filter_name = mlt_properties_get( self, "mlt_service" );
> > 
> > if(strcmp(filter_name, "dynamictext")==0)
> > {
> > //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter properties");
> > //	mlt_properties_debug( self, "filter_properties", stderr );
> > //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties");
> > //	mlt_properties_debug( producer_properties, "producer_properties", stderr );
> > //	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq filter length = %d\n", length);
> > }
> > else 	
> > {
> > 	*out_length = in_length;
> > 	return -1;
> > } 
> > 
> > mlt_position pos_in=0, pos_out=0;
> > if(mlt_producer_frame_pos(producer_service, &pos_in, &pos_out) == 0)
> > {
> > 	//mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter]  producer at track length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
> > 	*out_frame_in = pos_in;
> > 	*out_length = pos_out - pos_in +1;
> > 	return 0;
> > }
> > 
> > pos_in 	= mlt_properties_get_position( producer_properties, "in" );
> > pos_out 	= mlt_properties_get_position( producer_properties, "out" );
> > 
> > 
> > //if(mlt_properties_get_int( producer_properties , "_cut" )) //比较奇怪, 对应的_cut_child 才有 "_cut"
> > {
> > 	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer_properties cut");
> >     mlt_producer parent =  (mlt_producer)mlt_properties_get_data( producer_properties, "_cut_child", NULL);//"_cut_parent", NULL );
> > 	if(parent)
> > 	{
> > 		producer_service = MLT_PRODUCER_SERVICE(parent);
> > 		producer_properties = MLT_SERVICE_PROPERTIES( producer_service );
> > 		//mlt_properties_debug( producer_properties, "producer_properties", stderr );
> > 	}
> > }
> > 
> > pos_in 	= mlt_properties_get_position( producer_properties, "in" );
> > pos_out 	= mlt_properties_get_position( producer_properties, "out" );
> > 
> > if(strcmp(filter_name, "dynamictext")==0)
> > {
> > 	mlt_log_verbose( NULL,  "[mlt_properties.c get_length_for_filter] wzq producer length = %d in = %d, out = %d\n", pos_out - pos_in +1, pos_in, pos_out);
> > }  
> > 
> > if(pos_out > 0)
> > {
> > 	if(strcmp(filter_name, "dynamictext")==0)
> > 	{
> > 		 **### mlt_properties_set_position( self, "in", pos_in );
> > 		 mlt_properties_set_position( self, "out", pos_out );**
> > 	}
> > 	*out_frame_in = pos_in;
> > 	*out_length = pos_out - pos_in +1;
> > 	return 0;
> > } 
> > *out_length = 0;
> > return -1;
> > ```
> > 
> > 
> > }
> 
> pos_in = mlt_properties_get_position( producer_properties, "in" );
> pos_out = mlt_properties_get_position( producer_properties, "out" );
> 得到的是旧的out值，还未弄清楚原因

对于文字模板，拉长的时候，在调用get_length_for_filter接口时，当self是dynamicText时，从self获取producer_service，再从producer_service中获取playlist，但playlist时空的，其他滤镜都是对的。因此推测是producer_service有问题，尝试修改为：
mlt_service producer_service = (mlt_service)mlt_properties_get_data( MLT_PRODUCER_PROPERTIES( self ), "_cut_parent", NULL );
文字模板拉长后，工作正常。但会引起其他比较严重的问题，拉长后其他滤镜显示不正确，而且手动给普通clip添加的文字滤镜也会受到影响。

总结起来，目前文字模板拉长后，文字滤镜作用不对主要是get_length_for_filter中获取的producer_service不正确，即：
mlt_service producer_service = (mlt_service)mlt_properties_get_data( self, "service", NULL );

**Comment by Dragon-S** [comment]
问题的根源已经找到，主要是由于在通过工程文件或者模板文件创建的image producer加载到时间线上时，存在滤镜的拷贝，在拷贝滤镜时是的滤镜对应的producer发生了改变，指向了一个临时的producer，使得在get_length_for_filter函数中从filter得到的producer是临时的producer，而不是时间线上对应的producer，从而得不到正确的in、out、length
