### ISSUE TITLE
轨道添加clip，为clip添加滤镜后，界面右上角的视频滤镜参数界面显示白屏

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#757]
并不是每次都出现，但是出现概率很高，经常出现
1.添加「视频淡入」滤镜，出现的白屏的概率较高，其余滤镜也会出现白屏
2.文字模板或贴图添加到轨道上，视频滤镜参数界面也会出现白屏现象
3.每次出现白屏时，Qt都会提示如下警告
[Debug  ] <BaseItemDelegate::sizeHint> sll-----sizeHint---end
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Warning] <> file:///Users/apple/Library/Application Support/effectmatrix/MovieMator Pro/qt_qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qml:368: TypeError: Cannot read property 'flickableItem' of null
[Debug  ] <MainWindow::MainWindow()> setWindowTitle 
[Debug  ] <MainWindow::MainWindow()> end 
[Debug  ] <MainWindow::createMultitrackModelIfNeeded> begin 

**4.回退mlt代码**（mlt的代码回退到2.6.4）
mlt代码回退到no"h"adn"t" time format for the key frame of mlt_keyframe_pos_producer;再进行测试，也会遇到白屏问题。
启动程序，向轨道添加clip，移动clip位置（未添加滤镜）视频滤镜参数界面也会白屏

5.使用发布版本2.6.4的mlt库+2.7.0最新的moviemator代码，同样存在视频滤镜参数界面白屏问题

**Comment by fuyunhuaxin** [comment]
这个问题是在2.7.0分支上，Merge branch ‘2.7.0’ into DockGenerator之后开始出现的

**Comment by fuyunhuaxin** [comment]
与loadmetadata同步/异步加载相关
