### ISSUE TITLE
有两人反馈：10.10.5 花屏，且无法导入文件

### ISSUE THREAD

**Issue by debelliszhu** [hansewu/MovieMator#758]
第1个用户： 2.6.4,剪大师出现花屏，且无法导入视频，重新安装也没有用
![屏幕快照 2019-08-30 下午12 10 37](https://user-images.githubusercontent.com/37359992/64027114-a535fd80-cb72-11e9-8575-475ba0d34786.png)

![屏幕快照 2019-08-30 下午12 10 23](https://user-images.githubusercontent.com/37359992/64026803-11fcc800-cb72-11e9-82d7-cccc9088e102.png)

第2个用户： Unfortunately my MovieMator Editor for Mac after being updated no longer loads my videos or songs when i try up open them. 
2.6.1 running on my Mac. os x yosemite 10.10.5
让用户升级到steam最新版2.6.4及网站版本的2.6.4，仍然不可以用。
I did this yesterday on my mac and still nothing comes up when i try to open media

**Comment by pisceshsu** [comment]
已在MacBook 10.10.4系统复现，
从App Store下载最新的 2.6.4, 启动后，就和用户的情况一样，播放器绿屏；点击Open选择文件后，资源库中不显示文件

**Comment by vgawen** [comment]
测试网站版没有问题，appstore版本重新签名后也没有问题了。
