### ISSUE TITLE
Clip添加多个关键帧，删除中间任意关键帧后，无法定位下一帧

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#76]
### **问题描述：**
Clip添加多个关键帧（未切分），删除中间部分的任意关键帧后，无法定位下一帧，且拖动该clip后关键帧自动关闭。（10.14)
![5](https://user-images.githubusercontent.com/48675877/56190454-d0ed9680-605c-11e9-8327-d7f175cf3120.png)

来源:
Mac0.2.1版本测试

**Comment by wyl1987527** [comment]
去除m_keyFrameList 机制后，暂测试不存在这个问题
