### ISSUE TITLE
双击dock中的item添加资源

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#762]

**Comment by WanYuanCN** [comment]
双击时会触发两次单击和鼠标按下事件，会出现两次预览效果，因此得把单击和双击分开，使用定时器判断鼠标按下间隔，如果两次间隔小于300ms则视为双击，添加item，否则为单击，预览item。

**Comment by hpuzj** [comment]
跟测完成
双击资源dock中的任意item，都可以添加资源
