### ISSUE TITLE
clip切分后，添加多个关键帧，删除中间关键帧，无法定位关键帧

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#77]
### **问题描述;**
clip切分后，任意一小段clip，添加多个关键帧，删除中间部分任意关键帧，上一帧、下一帧按钮置灰，无法定位关键帧，且拖动该clip后关键帧自动关闭。(10.14)
![6](https://user-images.githubusercontent.com/48675877/56190618-27f36b80-605d-11e9-903e-e1059f9603e7.png)

### **来源：**
Mac 0.2.1版本测试

**Comment by vgawen** [comment]
Duplicate of #76
