### ISSUE TITLE
调研并完成工程资源打包功能初步方案

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#771]

**Comment by Dragon-S** [comment]
工程资源没有打包功能，引入的资源会被删除或者移动，造成工程缺失文件无法使用

**Comment by Dragon-S** [comment]
此任务主要是调研整理，并弄清楚功能需求。讨论确定需求

**Comment by WanYuanCN** [comment]
需求分析调研文档
[Moviemator工程资源打包需求分析.pdf](https://github.com/hansewu/MovieMator/files/3650086/Moviemator.pdf)

**Comment by WanYuanCN** [comment]
目前讨论确定的结果是使用压缩包的方式去打包，保存为zip文件，不使用工程文件.mmp的后缀，主要是使用Moviemator打开压缩的.mmp工程时需要先解压把文件保存到硬盘再读取，中间有个解压过程，并且会占用额外的硬盘空间，效率不高。

**Comment by WanYuanCN** [comment]
目前讨论确定的结果是使用压缩包的方式去打包，保存为zip文件，不使用工程文件.mmp的后缀，主要是使用Moviemator打开压缩的.mmp工程时需要先解压把文件保存到硬盘再读取，中间有个解压过程，并且会占用额外的硬盘空间，效率不高。
