### ISSUE TITLE
背景视频拖动到轨道上，右上角属性中选择预设，程序崩溃

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#777]
1.添加背景视频到轨道上
2.然后在右上角选择预设格式，程序崩溃

**Comment by WanYuanCN** [comment]
目前的大致原因找到了，是预设下拉列表激活后发送的信号会立即刷新时间线，然后时间线刷新的时候先删除再插入新的clip，插入时会重新加载属性窗口，加载属性窗口的时候又会发送信号调用时间线刷新clip的函数，就这样造成了一个信号循环发送，槽函数循环响应，最后崩溃。目前尝试延迟发送信号等属性界面加载完成后再刷新时间线就不会崩溃，但是多次操作会导致崩溃在Audiolevelstask的==重载函数里面的QList的isEmpty()函数里。这个原因还在继续确认。

**Comment by WanYuanCN** [comment]
使用异步发送信号后，AudioLevelsTask的重载函数==会出现Qlist崩溃，主要是由于在执行==的时候this已经被线程池释放了，导致Qlist的数据有问题，之前没有这个情况是因为选择预设后就崩溃，无法执行到这一步。如果在AudioLevelsTask里不自动释放，使用setAutoDelete(false)来手动释放，会导致Mac下时间线经常性的无法显示。目前还没有较好的解决办法。
颜色属性界面崩溃主要是发送信号给时间线后会属性界面会删除之前的colorproducerwidget来加载新的colorproducerwidget，而之前的colorproducerwidget本身由于combobox的原因还没有绘制完成却被删除了，于是就产生了崩溃。

**Comment by hpuzj** [comment]
跟测完成，该崩溃已解决，背景视频存在的其他问题，已重新提交issues
