### ISSUE TITLE
切分后的clip 添加关键帧后再删除关键帧，跨轨道拖动后，关键帧自动开启

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#78]
### **问题描述：**
clip切分后，选取中间任意一段clip（首段除外），添加一个关键帧，删除中间只剩下两端的关键帧,此时关闭关键帧，关键帧标识仍然显示，跨轨道拖动后，关键帧自动开启。（10.10、10.14）
![7](https://user-images.githubusercontent.com/48675877/56190788-95070100-605d-11e9-899e-b4d0bf0aba4d.png)

### **来源：**
Mac0.2.1版本测试

**Comment by wyl1987527** [comment]
测试发现 切分后的clip 添加关键帧后再删除关键帧，跨轨道拖动后，关键帧是自动关闭，没有测出自动开启。

**Comment by hpuzj** [comment]
使用2.5.6.5版本重新测试，仍然存在该问题
1）拖动一段clip到轨道上
2）clip切分随机切分，选取中间任意一段（首段除外）
3）添加一个关键帧（测试时分别使用了旋转、改变大小、对比度、亮度滤镜），可在关键帧位置调整参数，也可不调整
4）点击关键帧界面的“—”，删除中间添加的关键帧，然后关闭关键帧，关键帧标识仍然显示
5）拖动clip的位置，「开启关键帧」前面的对号，自动勾选。
