### ISSUE TITLE
html动画实现方案设计、关键技术验证

### ISSUE THREAD

**Issue by vgawen** [hansewu/MovieMator#799]
执行者：fuyunhuaxin
审核者：vgawen

**Comment by fuyunhuaxin** [comment]
设置文字的技术还没有完全突破，不过有3d文字滤镜的样例，实在不行到时可以依样画葫芦

**Comment by fuyunhuaxin** [comment]
[html动画设计方案_陈兴_20191009.pdf](https://github.com/hansewu/MovieMator/files/3705504/html._._20191009.pdf)

**Comment by vgawen** [comment]
确认
