### ISSUE TITLE
网站版本免费修改

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#800]
（1）制定修改方案，讨论确定
（2）实现修改

**Comment by Dragon-S** [comment]
修改注意点：
1 免费版功能上和现在网站PRO版基本一致。免费版暂时不要单独限制功能。
2在标题栏上不要提示为PRO 版本未注册信息。
3 输出时可以提示未注册版本输出右上角有水印。建议注册。

**Comment by WanYuanCN** [comment]
文档的主要内容已完成，对比了喵影工厂和Movavi，免费版的主要修改点：
①不区分注册和未注册版，MovieMator标题栏不显示“未注册”；
②免费版导出依然有水印，没有5分钟时长限制；
③导出时提示免费版有水印，提醒用户注册购买；
④现在的水印感觉有点大，是否需要改小，半透明，增加动画来提示用户关键帧功能;
⑤导出界面是否需要修改，包括文字说明和界面样式，改成像Movavi那样的；
⑥导出完成时是否需要像喵影工厂一样出现“移除水印”按钮提示用户购买；
⑦免费版卸载时是否像Movavi一样显示购买优惠信息提示用户购买；
⑧免费版不限制功能，是否需要限制素材的使用；

**Comment by WanYuanCN** [comment]
目前确定按照以下几点进行修改，并且只修改中国地区的免费版本：
①不区分注册和未注册版，MovieMator标题栏不显示“未注册”；
②免费版导出依然有水印，没有5分钟时长限制；
③导出时提示免费版有水印，提醒用户注册购买；
④现在的水印感觉有点大，是否需要改小，半透明；
