### ISSUE TITLE
贴图类型中的“商务金融”文字不能全部显示

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#83]
### **问题描述：**
贴图类型中的“商务金融”不能全部显示，可能电脑未安装该字体，用户使用时也不会特意去下载安装字体。(仅限Windows )
![9](https://user-images.githubusercontent.com/48675877/56191644-4ce8de00-605f-11e9-9c8c-2dd04f85176d.png)

### **来源;**
windows  0.1.9版本测试

**Comment by pisceshsu** [comment]
2.6.4,该分类已删除
