### ISSUE TITLE
完成工程资源打包详细设计方案草案

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#839]

**Comment by WanYuanCN** [comment]
目前使用quazip实现打包功能，正在实现打包的进度条显示

**Comment by WanYuanCN** [comment]
打包的进度条显示也已完成，可以正常显示进度，QuaZip集成了zlib库，可以把多个文件直接打包成一个zip文件，比将多个文件放到一个文件夹里打包少了一个复制文件的过程。

**Comment by WanYuanCN** [comment]
初稿已经完成，目前的问题是在Windows下打包的zip文件在Mac下不能使用默认软件打开，QuaZip本事是跨平台的，可能在不同平台下打包的方式不一样。

**Comment by WanYuanCN** [comment]
在Mac上测试了下QuaZip的Demo已经通过，Windows下的打包文件在Mac下也能正常打开，工程资源的打包功能初步方案定稿已经完成，还需确认。
