### ISSUE TITLE
工程资源打包详细设计方案草案讨论及修改

### ISSUE THREAD

**Issue by Dragon-S** [hansewu/MovieMator#840]

**Comment by Dragon-S** [comment]
（1）细化打包时同名文件冲突的解决方法（外部资源、系统资源自身同名冲突及相互之间同名冲突），考虑压缩工程存储的标准
（2）考虑含html的资源如何打包
（3）考虑打包相关接口如何安置（放在multitrackmodel或者作为其扩展，或者其他更合适的地方）

**Comment by WanYuanCN** [comment]
文档正在处理回调函数的使用；
关于html的资源打包，如果html资源路径使用相对路径的话，打开mmp工程文件时会报如下错误，应该是MLT解析html文件的路径出来问题：
[Error  ] <MLT> [filter webvfx_circular_frame] "untitled.mmp/webvfx_circular_frame/filter-demo.html" Failed to create WebVfx Effects for resource untitled.mmp/webvfx_circular_frame/filter-demo.html
[Error  ] <MLT> [filter webvfx_circular_frame] "untitled.mmp/webvfx_circular_frame/filter-demo.html" Failed to create WebVfx ServiceManager

**Comment by WanYuanCN** [comment]
int zipPackResourceList(QString &strZipName, QStringList &strListFiles, int (*pProgressAndCancelCallback)(int nValue, void *pUIObject), 
void *pUIObject);
这个打包接口会传入一个回调函数，用来控制packProjectWindow的进度条显示以及接收该进度条是否取消以终止打包。
回调函数pProgressAndCancelCallback()在压缩时调用并得到结果，如果进度条没有取消则继续打包，否则就停止打包，这样打包函数都会正常返回，线程正常结束。打包接口的参数pUIObject用来传递进度条对象给回调函数，用于在回调函数里控制进度条的显示。

**Comment by WanYuanCN** [comment]
方案草案已修改完成，等待确定。

**Comment by WanYuanCN** [comment]
确定方案最终版本。
