### ISSUE TITLE
设置为 24 FPS，声音没有了

### ISSUE THREAD

**Issue by hpuzj** [hansewu/MovieMator#87]
### **问题描述：**
Steam用户2.5.5：设置为 24 FPS，声音没有了(还是“没有音频处理工具”，俄语翻译得不清楚)
Монтаж в 24 ФПС Нет работы со звуком Нет переходов
Лаганый дизайн Удобная обрезка

### **来源**
steam用户反馈

**Comment by pisceshsu** [comment]
问题和#28 类似， https://github.com/hansewu/MovieMator/issues/28
